### ISSUE TITLE
 Cannot run program "Rscript": error=2, No such file or directory when running quay.io COBALT container

### ISSUE THREAD

**Issue by alexiswl** [hartwigmedical/hmftools#118]
Running via toil-cwl-runner on a AWS Parallel cluster (slurm job distributer)

Error logs:

```
[2020-09-07T15:18:38+1000] [MainThread] [I] [toil.worker] ---TOIL WORKER OUTPUT LOG---
[2020-09-07T15:18:38+1000] [MainThread] [I] [toil] Running Toil version 4.2.0-3aa1da130141039cb357efe36d7df9b9f6ae9b5b on host ip-10-2-0-81.
[2020-09-07T15:18:39+1000] [MainThread] [W] [cwltool] [job cobalt-1.8.cwl] Skipping Docker software container '--memory' limit despite presence of ResourceRequirement with ramMin and/or ramMax setting. Consider running with --strict-memory-limit for increased portability assurance.
[2020-09-07T15:18:39+1000] [MainThread] [I] [cwltool] [job cobalt-1.8.cwl] /efs/toil/workdir/node-e334ec44-92fa-44ea-9b56-0c0ff88c0999-e6272377-11fa-467d-9928-543edf7775ff/tmp7qne7dbf/7727655a-0662-4884-b2fb-a62b3242ed4c/tjmlohi1n/tmp-out4hkea9xg$ docker \
    run \
    -i \
    --mount=type=bind,source=/efs/toil/workdir/node-e334ec44-92fa-44ea-9b56-0c0ff88c0999-e6272377-11fa-467d-9928-543edf7775ff/tmp7qne7dbf/7727655a-0662-4884-b2fb-a62b3242ed4c/tjmlohi1n/tmp-out4hkea9xg,target=/BTpTmS \
    --mount=type=bind,source=/efs/toil/workdir/node-e334ec44-92fa-44ea-9b56-0c0ff88c0999-e6272377-11fa-467d-9928-543edf7775ff/tmp7qne7dbf/7727655a-0662-4884-b2fb-a62b3242ed4c/t24g0kk2htlkoefhp,target=/tmp \
    --mount=type=bind,source=/efs/umccr-refdata/hg38/hmf/GC_profile.1000bp.cnp,target=/var/lib/cwl/stgdd31b59f-8640-4fd6-967f-b2f4ef7fed51/GC_profile.1000bp.cnp,readonly \
    --mount=type=bind,source=/efs/input-data/SBJ_seqcii_020.bam,target=/var/lib/cwl/stg816df453-6e1d-447f-a828-5e618a9cbb24/SBJ_seqcii_020.bam,readonly \
    --mount=type=bind,source=/efs/input-data/SBJ_seqcii_020.bam.bai,target=/var/lib/cwl/stg816df453-6e1d-447f-a828-5e618a9cbb24/SBJ_seqcii_020.bam.bai,readonly \
    --mount=type=bind,source=/efs/input-data/SBJ_seqcii_020_tumor.bam,target=/var/lib/cwl/stg104ab0dc-a003-4904-a705-3a73b5c5f17b/SBJ_seqcii_020_tumor.bam,readonly \
    --mount=type=bind,source=/efs/input-data/SBJ_seqcii_020_tumor.bam.bai,target=/var/lib/cwl/stg104ab0dc-a003-4904-a705-3a73b5c5f17b/SBJ_seqcii_020_tumor.bam.bai,readonly \
    --workdir=/BTpTmS \
    --read-only=true \
    --net=host \
    --user=1000:1000 \
    --rm \
    --env=TMPDIR=/tmp \
    --env=HOME=/BTpTmS \
    --cidfile=/efs/toil/workdir/node-e334ec44-92fa-44ea-9b56-0c0ff88c0999-e6272377-11fa-467d-9928-543edf7775ff/tmp7qne7dbf/7727655a-0662-4884-b2fb-a62b3242ed4c/t24g0kk2h44eqqe7u/20200907151839-940240.cid \
    quay.io/biocontainers/hmftools-cobalt:1.8--0 \
    /bin/sh \
    -c \
    'COBALT' '-Xms2000m' '-Xmx14000m' '-gc_profile' '/var/lib/cwl/stgdd31b59f-8640-4fd6-967f-b2f4ef7fed51/GC_profile.1000bp.cnp' '-min_quality' '10' '-output_dir' 'SBJ_seqcii_020_cobalt' '-reference' 'seqcii_N020' '-reference_bam' '/var/lib/cwl/stg816df453-6e1d-447f-a828-5e618a9cbb24/SBJ_seqcii_020.bam' '-threads' '4' '-tumor' 'seqcii_T020' '-tumor_bam' '/var/lib/cwl/stg104ab0dc-a003-4904-a705-3a73b5c5f17b/SBJ_seqcii_020_tumor.bam' '-validation_stringency' 'STRICT'
/usr/local/bin/COBALT: line 6: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8): No such file or directory
05:18:41 - COBALT version: 1.8
05:18:41 - Thread Count: 4, Window Size: 1000, Min Quality 10
05:18:41 - Reading GC Profile
05:18:43 - Calculating Read Count from /var/lib/cwl/stg104ab0dc-a003-4904-a705-3a73b5c5f17b/SBJ_seqcii_020_tumor.bam
05:18:43 - Generating windows on chromosome chr1
05:18:43 - Generating windows on chromosome chr2
05:18:43 - Generating windows on chromosome chr3
05:18:43 - Calculating Read Count from /var/lib/cwl/stg816df453-6e1d-447f-a828-5e618a9cbb24/SBJ_seqcii_020.bam
05:18:43 - Generating windows on chromosome chr4
05:28:31 - Generating windows on chromosome chr5
05:29:00 - Generating windows on chromosome chr6
05:40:24 - Generating windows on chromosome chr7
05:41:07 - Generating windows on chromosome chr8
06:03:41 - Generating windows on chromosome chr9
06:11:18 - Generating windows on chromosome chr10
06:17:07 - Generating windows on chromosome chr11
06:22:09 - Generating windows on chromosome chr12
06:31:49 - Generating windows on chromosome chr13
06:41:27 - Generating windows on chromosome chr14
06:46:56 - Generating windows on chromosome chr15
06:51:38 - Generating windows on chromosome chr16
06:52:35 - Generating windows on chromosome chr17
07:00:12 - Generating windows on chromosome chr18
07:03:47 - Generating windows on chromosome chr19
07:05:55 - Generating windows on chromosome chr20
07:07:35 - Generating windows on chromosome chr21
07:14:29 - Generating windows on chromosome chr22
07:15:38 - Generating windows on chromosome chrX
07:16:02 - Generating windows on chromosome chrY
07:17:23 - Generating windows on chromosome chr1
07:18:35 - Generating windows on chromosome chr2
07:22:58 - Generating windows on chromosome chr3
07:33:01 - Generating windows on chromosome chr4
07:45:45 - Generating windows on chromosome chr5
07:47:10 - Generating windows on chromosome chr6
07:47:38 - Generating windows on chromosome chr7
07:51:39 - Generating windows on chromosome chr8
07:54:24 - Generating windows on chromosome chr9
07:54:39 - Generating windows on chromosome chr10
07:55:05 - Generating windows on chromosome chr11
07:56:37 - Generating windows on chromosome chr12
07:58:54 - Generating windows on chromosome chr13
07:59:19 - Generating windows on chromosome chr14
07:59:39 - Generating windows on chromosome chr15
08:01:16 - Generating windows on chromosome chr16
08:02:22 - Generating windows on chromosome chr17
08:02:36 - Generating windows on chromosome chr18
08:02:51 - Generating windows on chromosome chr19
08:03:27 - Generating windows on chromosome chr20
08:05:01 - Generating windows on chromosome chr21
08:05:03 - Generating windows on chromosome chr22
08:05:30 - Generating windows on chromosome chrX
08:05:30 - Generating windows on chromosome chrY
08:07:02 - Read Count Complete
08:07:04 - Applying ratio gc normalization
08:07:07 - Applying ratio diploid normalization
08:07:17 - Persisting gc read count medians to SBJ_seqcii_020_cobalt
08:07:22 - Persisting cobalt ratios to SBJ_seqcii_020_cobalt/seqcii_T020.cobalt.ratio.tsv
08:07:31 - Executing R script via command: Rscript /tmp/script451828423108624136.R SBJ_seqcii_020_cobalt/seqcii_T020.cobalt.ratio.tsv tumorGCRatio SBJ_seqcii_020_cobalt/seqcii_T020.cobalt.ratio.pcf
08:07:31 - Executing R script via command: Rscript /tmp/script17137064507502695971.R SBJ_seqcii_020_cobalt/seqcii_T020.cobalt.ratio.tsv referenceGCDiploidRatio SBJ_seqcii_020_cobalt/seqcii_N020.cobalt.ratio.pcf
08:07:31 - Complete
Exception in thread "main" java.util.concurrent.ExecutionException: java.io.IOException: Cannot run program "Rscript": error=2, No such file or directory
        at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
        at com.hartwig.hmftools.cobalt.RatioSegmentation.applySegmentation(RatioSegmentation.java:37)
        at com.hartwig.hmftools.cobalt.CountBamLinesApplication.run(CountBamLinesApplication.java:105)
        at com.hartwig.hmftools.cobalt.CountBamLinesApplication.main(CountBamLinesApplication.java:46)
Caused by: java.io.IOException: Cannot run program "Rscript": error=2, No such file or directory
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
        at com.hartwig.hmftools.common.utils.r.RExecutor.executeFromFile(RExecutor.java:63)
        at com.hartwig.hmftools.common.utils.r.RExecutor.executeFromClasspath(RExecutor.java:47)
        at com.hartwig.hmftools.cobalt.RatioSegmentation.ratioSegmentation(RatioSegmentation.java:46)
        at com.hartwig.hmftools.cobalt.RatioSegmentation.lambda$applySegmentation$0(RatioSegmentation.java:33)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.io.IOException: error=2, No such file or directory
        at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
        at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
        at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:271)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
        ... 9 more
[2020-09-07T18:07:32+1000] [MainThread] [I] [cwltool] [job cobalt-1.8.cwl] Max memory used: 7188MiB
[2020-09-07T18:07:32+1000] [MainThread] [W] [cwltool] [job cobalt-1.8.cwl] completed permanentFail
Traceback (most recent call last):
  File "/home/ec2-user/.conda/envs/toil/lib/python3.8/site-packages/toil/worker.py", line 368, in workerScript
    job._runner(jobGraph=jobGraph, jobStore=jobStore, fileStore=fileStore, defer=defer)
  File "/home/ec2-user/.conda/envs/toil/lib/python3.8/site-packages/toil/job.py", line 1424, in _runner
    returnValues = self._run(jobGraph, fileStore)
  File "/home/ec2-user/.conda/envs/toil/lib/python3.8/site-packages/toil/job.py", line 1361, in _run
    return self.run(fileStore)
  File "/home/ec2-user/.conda/envs/toil/lib/python3.8/site-packages/toil/cwl/cwltoil.py", line 988, in run
    raise cwltool.errors.WorkflowException(status)
cwltool.errors.WorkflowException: permanentFail
[2020-09-07T18:07:32+1000] [MainThread] [E] [toil.worker] Exiting the worker because of a failed job on host ip-10-2-0-81

**Comment by alexiswl** [comment]
Furthermore, 

```
$ docker run --rm quay.io/biocontainers/hmftools-cobalt:1.8--0 /bin/sh -c "which Rscript"
```

does not find `Rscript`. With a `find / -name 'Rscript` I could not find it. It would appear that it's not installed in the container.

**Comment by pdiakumis** [comment]
Connected to https://github.com/hartwigmedical/hmftools/issues/113 since there's a missing r-base conda pkg in the COBALT conda build - I'll try to sort it out by tomorrow.

**Comment by pdiakumis** [comment]
Should be fixed now @alexiswl (via https://github.com/bioconda/bioconda-recipes/commit/c01290396c84f0e52688b69216decfdd8eaf9ea1) - just use the `1.8--1` build from <https://quay.io/repository/biocontainers/hmftools-cobalt?tab=tags>:

```
$ docker run --rm quay.io/biocontainers/hmftools-cobalt:1.8--1 /bin/sh -c "which Rscript"                                            <<<
/usr/local/bin/Rscript
```

Let me know if there are any problems.
