### ISSUE TITLE
LINX output visualization

### ISSUE THREAD

**Issue by bynjh007** [hartwigmedical/hmftools#119]
Hi,

I am trying to visualize  linx output with sv-linx_v1.10.jar using following command:

java -cp sv-linx_v1.10.jar com.hartwig.hmftools.linx.visualiser.SvVisualiser -sample test_samp -gene_transcripts_dir hg19/dbs/ensembl_data_cache/ -plot_out linx_vis_plot -data_out linx_vis_data -segment linx_out/CPCTXXXX.linx.vis_segments.tsv -link linx_out/CPCTXXXX.linx.vis_sv_data.tsv -exon linx_out/CPCTXXXX.linx.vis_gene_exon.tsv -cna linx_out/CPCTXXXX.linx.vis_copy_number.tsv -protein_domain linx_out/CPCTXXXX.linx.vis_protein_domain.tsv -fusion linx_out/CPCTXXXX.linx.fusion.tsv -circos /home/j.bhin/.conda/envs/linx/bin/circos -threads 8.

(I obtained the linx output from HMF data request).

And I got the following error message:

10:17:05 - [INFO ] - Loading data
Exception in thread "main" java.lang.NumberFormatException: For input string: "ThreePrimeBreakendId"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.base/java.lang.Integer.parseInt(Integer.java:652)
	at java.base/java.lang.Integer.valueOf(Integer.java:983)
	at com.hartwig.hmftools.linx.visualiser.file.VisFusionFile.fromString(VisFusionFile.java:157)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at com.hartwig.hmftools.linx.visualiser.file.VisFusionFile.fromLines(VisFusionFile.java:97)
	at com.hartwig.hmftools.linx.visualiser.file.VisFusionFile.read(VisFusionFile.java:77)
	at com.hartwig.hmftools.linx.visualiser.data.Fusions.fromFile(Fusions.java:25)
	at com.hartwig.hmftools.linx.visualiser.SvVisualiserConfig.createConfig(SvVisualiserConfig.java:182)
	at com.hartwig.hmftools.linx.visualiser.SvVisualiser.<init>(SvVisualiser.java:91)
	at com.hartwig.hmftools.linx.visualiser.SvVisualiser.main(SvVisualiser.java:67)

It seems like there might be some problem in the "CPCTXXXX.linx.fusion.tsv" file as it contains the column "ThreePrimeBreakendId".

The file seems to include normal information from linx with columns of
"FivePrimeBreakendId | ThreePrimeBreakendId | Name | Reported | ReportedType | Phased | ChainLength | ChainLinks | ChainTerminated | DomainsKept | DomainsLost | SkippedExonsUp | SkippedExonsDown | FusedExonUp | FusedExonDown"

Could you help me how to solve this error?

Thanks

**Comment by jonbaber** [comment]
Looks like you are using the wrong file for the fuions. Should be XXXX.linx.vis_fusion.tsv (ie, with the "vis" in there)
