### ISSUE TITLE
nullpointerexception

### ISSUE THREAD

**Issue by MaXXinee** [hartwigmedical/hmftools#140]
Dear PURPLE team,

I tried running PURPLE on my WES bam with customized snp_vcf file. At the last step of calling purple.jar, it outputs the null pointer exception. Could you please help me with this issue?
Exception in thread "main" java.lang.NullPointerException
	at com.hartwig.hmftools.common.purple.segment.PurpleSegmentFactory.create(PurpleSegmentFactory.java:76)
	at com.hartwig.hmftools.common.purple.segment.PurpleSegmentFactory.create(PurpleSegmentFactory.java:70)
	at com.hartwig.hmftools.common.purple.segment.PurpleSegmentFactory.segmentMap(PurpleSegmentFactory.java:60)
	at com.hartwig.hmftools.common.purple.segment.PurpleSegmentFactory.segmentCluster(PurpleSegmentFactory.java:45)
	at com.hartwig.hmftools.common.purple.segment.PurpleSegmentFactory.segment(PurpleSegmentFactory.java:39)
	at com.hartwig.hmftools.purple.Segmentation.createSegments(Segmentation.java:55)
	at com.hartwig.hmftools.purple.PurityPloidyEstimateApplication.<init>(PurityPloidyEstimateApplication.java:156)
	at com.hartwig.hmftools.purple.PurityPloidyEstimateApplication.main(PurityPloidyEstimateApplication.java:103)

**Comment by DarioS** [comment]
I was going to suggest reading PURPLE's user guide, but it actually doesn't explain that PURPLE doesn't work for exome data and requires whole genome sequencing. It might save confusion if it was explicitly stated in the Input section.

**Comment by jonbaber** [comment]
Hi MaXXinee,

PURPLE does not support WES data nor do we intend to support it any time soon. Sorry I cannot be of more help.

As per @DarioS's suggestion I have made this explicit in the readme.

Jon
