### ISSUE TITLE
ISOFOX - no index error; TPM values zero

### ISSUE THREAD

**Issue by alhafidzhamdan** [hartwigmedical/hmftools#145]
Hi there,

I'm trying your new ISOFOX pipeline as I'm interested in verifying intragenic fusions found by GRIDSS.
Thank you for developing this.

I ran the recommended STAR settings as per:

```
$STAR \
    --runThreadN 20 \
    --genomeDir $STAR_GENOME_DIR \
    --sjdbGTFfile $STAR_GTF \
    --readFilesIn $R1 $R2 \
    --readFilesCommand zcat \
    --outFileNamePrefix $SAMPLE_ID \
    --outSAMtype BAM Unsorted --outSAMunmapped Within --outBAMcompression 0 --outSAMattributes All --outFilterMultimapNmax 10 \
    --outFilterMismatchNmax 3 limitOutSJcollapsed 3000000 -chimSegmentMin 10 --chimOutType WithinBAM SoftClip \
    --chimJunctionOverhangMin 10 --chimSegmentReadGapMax 3 --chimScoreMin 1 --chimScoreDropMax 30 --chimScoreJunctionNonGTAG 0 \
    --chimScoreSeparation 1 --outFilterScoreMinOverLread 0.33 --outFilterMatchNminOverLread 0.33 --outFilterMatchNmin 35 \
    --alignSplicedMateMapLminOverLmate 0.33 --alignSplicedMateMapLmin 35 --alignSJstitchMismatchNmax 5 -1 5 5

```
And that turned out OK, producing the aligned (unsorted) bam file.
I noticed that there is no index aka .bai file.

Then i tried running ISOFOX using this:

```
java $JVM_OPTS $JVM_TMP_DIR -jar $ISOFOX_JAR \
    -sample ${SAMPLE_ID} \
    -functions "TRANSCRIPT_COUNTS;NOVEL_LOCATIONS;FUSIONS" \
    -bam_file ${SAMPLE_ID}Aligned.out.bam \
    -ref_genome $STAR_GENOME \
    -gene_transcripts_dir $HMF_ENSEMBLE \
    -output_dir $STAR_ISOFOX \
    -apply_calc_frag_lengths \
    -apply_exp_rates \
    -single_map_qual 255 \
    -exp_counts_file $ISOFOX_EXPECTED_COUNTS \
    -apply_gc_bias_adjust \
    -exp_gc_ratios_file $ISOFOX_EXPECTED_GC \
    -long_frag_limit 550 \
    -exp_rate_frag_lengths "50-0;75-0;100-0;125-0;150-0;200-0;250-0;300-0;400-0;550-0" \
    -apply_map_qual_adjust \
    -threads 16 
```

But i got an index error:
```
09:45:51 - [ERROR] - task execution error: java.util.concurrent.ExecutionException: htsjdk.samtools.SAMException: No index is available for this BAM file.
java.util.concurrent.ExecutionException: htsjdk.samtools.SAMException: No index is available for this BAM file.
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at com.hartwig.hmftools.isofox.common.TaskExecutor.checkThreadCompletion(TaskExecutor.java:63)
	at com.hartwig.hmftools.isofox.common.TaskExecutor.executeChromosomeTask(TaskExecutor.java:50)
	at com.hartwig.hmftools.isofox.Isofox.allocateBamFragments(Isofox.java:184)
	at com.hartwig.hmftools.isofox.Isofox.runAnalysis(Isofox.java:142)
	at com.hartwig.hmftools.isofox.Isofox.main(Isofox.java:467)
Caused by: htsjdk.samtools.SAMException: No index is available for this BAM file.
	at htsjdk.samtools.BAMFileReader.getIndex(BAMFileReader.java:411)
	at htsjdk.samtools.BAMFileReader.createIndexIterator(BAMFileReader.java:952)
	at htsjdk.samtools.BAMFileReader.query(BAMFileReader.java:612)
	at htsjdk.samtools.SamReader$PrimitiveSamReaderToSamReaderAdapter.query(SamReader.java:533)
	at htsjdk.samtools.SamReader$PrimitiveSamReaderToSamReaderAdapter.queryOverlapping(SamReader.java:405)
	at com.hartwig.hmftools.isofox.common.BamSlicer.slice(BamSlicer.java:42)
	at com.hartwig.hmftools.isofox.BamFragmentAllocator.produceBamCounts(BamFragmentAllocator.java:242)
	at com.hartwig.hmftools.isofox.BamFragmentReader.analyseBamReads(BamFragmentReader.java:357)
	at com.hartwig.hmftools.isofox.BamFragmentReader.assignTranscriptCounts(BamFragmentReader.java:239)
	at com.hartwig.hmftools.isofox.BamFragmentReader.call(BamFragmentReader.java:167)
	at com.hartwig.hmftools.isofox.BamFragmentReader.call(BamFragmentReader.java:48)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:844)
```

I figured then i should sort and index the bam file.
Once i did that ISOFOX ran to completion.

However I noticed that all my TPM values are zero.

```
head  G328_CL_S87.isf.gene_data.csv 
GeneId,GeneName,Chromosome,GeneLength,IntronicLength,TranscriptCount,GeneSetId,SplicedFragments,UnsplicedFragments,AdjTPM,RawTPM,FitResiduals,LowMapQualFrags
ENSG00000236875,DDX11L5,chr9,1649,1001,1,chr9_0,0,0,0.000e+00,0.000e+00,0.0,0.0
ENSG00000181404,WASHC1,chr9,59390,57088,2,chr9_1,100,569,0.000e+00,0.000e+00,267.6,2059.7
ENSG00000227518,AL928970.1,chr9,3234,313,1,chr9_1,2,1,0.000e+00,0.000e+00,14.6,2.7
ENSG00000283921,MIR1302-9,chr9,137,0,1,chr9_1,0,0,0.000e+00,0.000e+00,0.6,0.0
ENSG00000218839,FAM138C,chr9,2875,1567,3,chr9_1,0,0,0.000e+00,0.000e+00,13.0,0.0
ENSG00000284986,AL449043.2,chr9,20922,20530,1,chr9_1,0,0,0.000e+00,0.000e+00,94.3,0.0
```

Btw, my read length is 135ish.

Could you please help me troubleshoot?
Thanks in advance.

A

**Comment by charlesshale** [comment]
Could you tell me which cached files you were using - ie $ISOFOX_EXPECTED_COUNTS and $ISOFOX_EXPECTED_GC?

Are you able to share the log file from this run? The other useful files to look at are the summary and gene_collection files - they have raw counts by type.

Looks like you are using either HG19 or HG38, given the 'chr' prefix. Since GRCh37 is the default, you also need to specify ref_genome_version (eg -ref_genome_version HG38).

Email me directly if easier - c.shale@hartwigmedicalfoundation.nl

thanks,

Charles

**Comment by alhafidzhamdan** [comment]
Hey Charles- emailed.
