### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by jennyp76** [hartwigmedical/hmftools#149]
Thank you for the awesome tools! 
As your team have recommended I am dealing with 7 WGS data from 2 different patients. I used the GRIDSS and Strelka for the optional input data. 
I had no trouble running 6 WGS datas but when running a data from FFPE, I keep on facing a "NullPointerException" error. The error code pops up after "Loading somatic variants" from Strelka 

Thanks,
Jen

<ERROR LOG FILE>
 thread "main" java.lang.NullPointerException
        at com.hartwig.hmftools.common.variant.AllelicDepth.containsAllelicDepth(AllelicDepth.java:20)
        at com.hartwig.hmftools.common.variant.SomaticVariantFactory.createVariant(SomaticVariantFactory.java:126)
        at com.hartwig.hmftools.common.variant.SomaticVariantFactory.createVariant(SomaticVariantFactory.java:118)
        at com.hartwig.hmftools.purple.PurityPloidyEstimateApplication.lambda$somaticVariants$0(PurityPloidyEstimateApplication.java:391)
        at com.hartwig.hmftools.common.variant.enrich.VariantHotspotEnrichment.accept(VariantHotspotEnrichment.java:38)
        at com.hartwig.hmftools.purple.PurityPloidyEstimateApplication.somaticVariants(PurityPloidyEstimateApplication.java:399)
        at com.hartwig.hmftools.purple.PurityPloidyEstimateApplication.<init>(PurityPloidyEstimateApplication.java:149)
        at com.hartwig.hmftools.purple.PurityPloidyEstimateApplication.main(PurityPloidyEstimateApplication.java:103)

**Comment by tea-kostic** [comment]
Hi!

I am experiencing the same issue when running Purple 2.51 with somatic VCF file from Strelka that was preprocessed using the steps explained in the readme. What is this error suggesting and how can it be resolved?

Thanks,
Tea

**Comment by alvinwt** [comment]
Hi, I have the same issue using Purple 2.51 and I wonder if it is the same error. Would anyone have ideas on how it can be resolved?

**Comment by alvinwt** [comment]
Perhaps for someone else with the issue. The issue was the sample names in the SNV VCF did not match the PURPLE sample names and changing that fixed the issue.

**Comment by charlesshale** [comment]
The crash occurs when a sample name cannot be found in the VCF's genetype(s). Purple will now skip over those records.

Fixed in Purple 3.2, currently a beta release:

https://github.com/hartwigmedical/hmftools/releases/tag/purple-v3.2_beta

**Comment by charlesshale** [comment]
If you can attached a snippet your VCF then I can confirm what data is missing / expected.

thanks
