### ISSUE TITLE
Purple error when fitting purity - Exception in thread "main" java.lang.IllegalArgumentException: No enum constant com.hartwig.hmftools.common.genome.chromosome.HumanChromosome._M

### ISSUE THREAD

**Issue by alexiswl** [hartwigmedical/hmftools#165]
Hello running purple from gridss output v2.10.2 with gripss v 1.9, amber 3.5 and cobalt 1.11  with the hg38 alt reference

## Command
```
docker \
    run \
    -i \
    --mount=type=bind,source=/fsx/cwl-local/intermediate-outputs/9ipl81my,target=/sYPfbz \
    --mount=type=bind,source=/fsx/cwl-local/temp/p20c_9an,target=/tmp \
    --mount=type=bind,source=/fsx/cwl-local/intermediate-outputs/a41bjj0m/SBJ00689_amber,target=/var/lib/cwl/stg4e6a5189-b107-4774-bd43-1f7955b104dd/SBJ00689_amber,readonly \
    --mount=type=bind,source=/fsx/cwl-local/intermediate-outputs/or9gq8xj/SBJ00689_cobalt,target=/var/lib/cwl/stgd6540df9-cdb4-4a2e-8daf-8d4dfc53b299/SBJ00689_cobalt,readonly \
    --mount=type=bind,source=/fsx/reference-data/hartwig-nextcloud/hg38_alt/dbs/gc/GC_profile.1000bp.cnp,target=/var/lib/cwl/stg906175d3-a2fc-4a0f-b01a-714ea8dced4d/GC_profile.1000bp.cnp,readonly \
    --mount=type=bind,source=/fsx/input-data/L2100109/SBJ00689__SBJ00689_MDX210034_L2100109-somatic.vcf.gz,target=/var/lib/cwl/stg6957f9e2-04dc-4da3-b1bf-bcc91ee4f2ca/SBJ00689__SBJ00689_MDX210034_L2100109-somatic.vcf.gz,readonly \
    --mount=type=bind,source=/fsx/input-data/L2100109/SBJ00689__SBJ00689_MDX210034_L2100109-somatic.vcf.gz.tbi,target=/var/lib/cwl/stg6957f9e2-04dc-4da3-b1bf-bcc91ee4f2ca/SBJ00689__SBJ00689_MDX210034_L2100109-somatic.vcf.gz.tbi,readonly \
    --mount=type=bind,source=/fsx/cwl-local/intermediate-outputs/9yd0x1g4/SBJ00689.gripss.somatic.filtered.vcf.gz,target=/var/lib/cwl/stg73837edf-69fc-46cf-9580-9a72fef9909f/SBJ00689.gripss.somatic.filtered.vcf.gz,readonly \
    --mount=type=bind,source=/fsx/cwl-local/intermediate-outputs/9yd0x1g4/SBJ00689.gripss.somatic.filtered.vcf.gz.tbi,target=/var/lib/cwl/stg73837edf-69fc-46cf-9580-9a72fef9909f/SBJ00689.gripss.somatic.filtered.vcf.gz.tbi,readonly \
    --mount=type=bind,source=/fsx/cwl-local/intermediate-outputs/7qsbay8d/SBJ00689.gripss.somatic.vcf.gz,target=/var/lib/cwl/stg599107e5-dbd5-43a9-8c5a-d3d825216569/SBJ00689.gripss.somatic.vcf.gz,readonly \
    --mount=type=bind,source=/fsx/cwl-local/intermediate-outputs/7qsbay8d/SBJ00689.gripss.somatic.vcf.gz.tbi,target=/var/lib/cwl/stg599107e5-dbd5-43a9-8c5a-d3d825216569/SBJ00689.gripss.somatic.vcf.gz.tbi,readonly \
    --mount=type=bind,source=/fsx/reference-data/hartwig-nextcloud/hg38_alt/refgenomes/hg38/hg38.fa,target=/sYPfbz/hg38.fa,readonly \
    --mount=type=bind,source=/fsx/reference-data/hartwig-nextcloud/hg38_alt/refgenomes/hg38/hg38.fa.fai,target=/sYPfbz/hg38.fa.fai,readonly \
    --mount=type=bind,source=/fsx/reference-data/hartwig-nextcloud/hg38_alt/refgenomes/hg38/hg38.dict,target=/sYPfbz/hg38.dict,readonly \
    --workdir=/sYPfbz \
    --read-only=true \
    --user=1000:1000 \
    --rm \
    --env=TMPDIR=/tmp \
    --env=HOME=/sYPfbz \
    --cidfile=/fsx/cwl-local/temp/41r74ocq/20210319065223-181719.cid \
    quay.io/biocontainers/hmftools-purple:2.53--0 \
    PURPLE \
    -Xms2000m \
    -Xmx14000m \
    -amber \
    /var/lib/cwl/stg4e6a5189-b107-4774-bd43-1f7955b104dd/SBJ00689_amber \
    -cobalt \
    /var/lib/cwl/stgd6540df9-cdb4-4a2e-8daf-8d4dfc53b299/SBJ00689_cobalt \
    -gc_profile \
    /var/lib/cwl/stg906175d3-a2fc-4a0f-b01a-714ea8dced4d/GC_profile.1000bp.cnp \
    -output_dir \
    SBJ00689_purple \
    -ref_genome \
    /sYPfbz/hg38.fa \
    -reference \
    SBJ00689_MDX210033_L2100108 \
    -somatic_vcf \
    /var/lib/cwl/stg6957f9e2-04dc-4da3-b1bf-bcc91ee4f2ca/SBJ00689__SBJ00689_MDX210034_L2100109-somatic.vcf.gz \
    -structural_vcf \
    /var/lib/cwl/stg73837edf-69fc-46cf-9580-9a72fef9909f/SBJ00689.gripss.somatic.filtered.vcf.gz \
    -sv_recovery_vcf \
    /var/lib/cwl/stg599107e5-dbd5-43a9-8c5a-d3d825216569/SBJ00689.gripss.somatic.vcf.gz \
    -threads \
    2 \
    -tumor \
    SBJ00689_MDX210034_L2100109
```

## Output
```
19:52:36 - PURPLE version: 2.53
19:52:36 - Reference Sample: SBJ00689_MDX210033_L2100108, Tumor Sample: SBJ00689_MDX210034_L2100109
19:52:36 - Output Directory: SBJ00689_purple
19:52:36 - Using ref genome: COORDS_38
19:52:36 - Reading amber QC from /var/lib/cwl/stg4e6a5189-b107-4774-bd43-1f7955b104dd/SBJ00689_amber/SBJ00689_MDX210034_L2100109.amber.qc
19:52:36 - Reading amber bafs from /var/lib/cwl/stg4e6a5189-b107-4774-bd43-1f7955b104dd/SBJ00689_amber/SBJ00689_MDX210034_L2100109.amber.baf.tsv
19:52:37 - Reading amber pcfs from /var/lib/cwl/stg4e6a5189-b107-4774-bd43-1f7955b104dd/SBJ00689_amber/SBJ00689_MDX210034_L2100109.amber.baf.pcf
19:52:37 - Average amber tumor depth is 105 reads implying an ambiguous BAF of 0.543
19:52:37 - Reading cobalt ratios from /var/lib/cwl/stgd6540df9-cdb4-4a2e-8daf-8d4dfc53b299/SBJ00689_cobalt/SBJ00689_MDX210034_L2100109.cobalt.ratio.tsv
19:52:40 - Reading cobalt reference segments from /var/lib/cwl/stgd6540df9-cdb4-4a2e-8daf-8d4dfc53b299/SBJ00689_cobalt/SBJ00689_MDX210033_L2100108.cobalt.ratio.pcf
19:52:40 - Reading cobalt tumor segments from /var/lib/cwl/stgd6540df9-cdb4-4a2e-8daf-8d4dfc53b299/SBJ00689_cobalt/SBJ00689_MDX210034_L2100109.cobalt.ratio.pcf
19:52:42 - No germline vcf supplied
19:52:42 - Sample gender is female
19:52:42 - Loading structural variants from /var/lib/cwl/stg73837edf-69fc-46cf-9580-9a72fef9909f/SBJ00689.gripss.somatic.filtered.vcf.gz
19:52:42 - Loading somatic variants from /var/lib/cwl/stg6957f9e2-04dc-4da3-b1bf-bcc91ee4f2ca/SBJ00689__SBJ00689_MDX210034_L2100109-somatic.vcf.gz
19:52:42 - Applying segmentation
19:52:42 - Merging reference and tumor ratio break points
19:52:42 - Reading GC Profiles from /var/lib/cwl/stg906175d3-a2fc-4a0f-b01a-714ea8dced4d/GC_profile.1000bp.cnp
19:52:47 - Fitting purity
Exception in thread "main" java.lang.IllegalArgumentException: No enum constant com.hartwig.hmftools.common.genome.chromosome.HumanChromosome._M
        at java.base/java.lang.Enum.valueOf(Enum.java:240)
        at com.hartwig.hmftools.common.genome.chromosome.HumanChromosome.valueOf(HumanChromosome.java:9)
        at com.hartwig.hmftools.common.genome.chromosome.HumanChromosome.fromString(HumanChromosome.java:66)
        at com.hartwig.hmftools.common.genome.region.GenomeRegionSelectorListImpl.compare(GenomeRegionSelectorListImpl.java:73)
        at com.hartwig.hmftools.common.genome.position.GenomePositionSelectorIteratorImpl.select(GenomePositionSelectorIteratorImpl.java:54)
        at com.hartwig.hmftools.common.purple.purity.FittedPurityFactory.<init>(FittedPurityFactory.java:77)
        at com.hartwig.hmftools.purple.PurityPloidyEstimateApplication.fitPurity(PurityPloidyEstimateApplication.java:344)
        at com.hartwig.hmftools.purple.PurityPloidyEstimateApplication.<init>(PurityPloidyEstimateApplication.java:159)
        at com.hartwig.hmftools.purple.PurityPloidyEstimateApplication.main(PurityPloidyEstimateApplication.java:101)
```

**Comment by alexiswl** [comment]
When running with the same inputs with purple 2.51 (docker container quay.io/biocontainers/hmftools-purple:2.51--1 I don't get this error and the command completes successfully)

**Comment by tea-kostic** [comment]
Hi @alexiswl ,

We are running your [CWL version](https://github.com/umccr/gridss-purple-linx/blob/cwl-workflow/cwl/workflows/gridss-purple-linx/1.3.2/gridss-purple-linx.1.3.2.cwl) of the gridss/purple/linx pipeline. 
The workflow is running smoothly without the somatic VCF input, however when we try to run it with the somatic VCF file from Strelka that was preprocessed using the steps explained [here](https://github.com/hartwigmedical/hmftools/tree/master/purple#preparing-strelka-output-for-purple), we get the following error:

`Exception in thread "main" java.lang.NullPointerException
at com.hartwig.hmftools.common.variant.AllelicDepth.containsAllelicDepth(AllelicDepth.java:20)
at com.hartwig.hmftools.common.variant.SomaticVariantFactory.createVariant(SomaticVariantFactory.java:126)
at com.hartwig.hmftools.common.variant.SomaticVariantFactory.createVariant(SomaticVariantFactory.java:118)
at com.hartwig.hmftools.purple.PurityPloidyEstimateApplication.lambda$somaticVariants$0(PurityPloidyEstimateApplication.java:391)
at com.hartwig.hmftools.common.variant.enrich.VariantHotspotEnrichment.accept(VariantHotspotEnrichment.java:38)
at com.hartwig.hmftools.purple.PurityPloidyEstimateApplication.somaticVariants(PurityPloidyEstimateApplication.java:399)
at com.hartwig.hmftools.purple.PurityPloidyEstimateApplication.(PurityPloidyEstimateApplication.java:149)
at com.hartwig.hmftools.purple.PurityPloidyEstimateApplication.main(PurityPloidyEstimateApplication.java:103)`

Here is the command:

`PURPLE -Xms2000m -Xmx14000m -reference HCC1143_N -tumor HCC1143_T -output_dir HCC1143_purple -amber HCC1143_amber -circos /usr/local/bin/circos -cobalt HCC1143_cobalt -gc_profile GC_profile.hg38.1000bp.cnp -ref_genome GCA_000001405.15_GRCh38_no_alt_analysis_set.fasta -somatic_vcf strelka.merged.annotated.vcf.gz -structural_vcf HCC1143.gripss.somatic.filtered.vcf.gz -sv_recovery_vcf HCC1143.gripss.somatic.vcf.gz`

This is the somatic VCF file: [strelka.merged.annotated.vcf.gz](https://github.com/hartwigmedical/hmftools/files/6516436/strelka.merged.annotated.vcf.gz), all variants have the AD field populated, so we are not really sure what could be causing this error. Have you experienced this kind of issue or have any idea how to solve it?

Thanks!
Tea

**Comment by alexiswl** [comment]
Hi @tea-kostic,

The Purple command appears to be missing the following parameters:

* `-hotspots KnownHotspots.vcf.gz`
* `-driver_gene_panel DriverGenePanel.tsv`
* `-driver_catalog`

Having a look at the cwl code, that's an issue with the workflow. I would, however, move to the 'latest' workflow [here](https://github.com/umccr/gridss-purple-linx/blob/cwl-workflow/cwl/workflows/gridss-purple-linx/latest/gridss-purple-linx.latest.cwl). I migrated away from the 1.3.2 version since gridss v2.9.4 wasn't working on a couple of samples we had.

**Comment by tea-kostic** [comment]
Hi @alexiswl ,

Are those parameters necessary when using somatic VCF input?

We updated the workflow to the latest version and it is now working.

Thanks for your help!
Tea

**Comment by alexiswl** [comment]
> Are those parameters necessary when using somatic VCF input?

I'd say yes but someone else from Hartwig would be better suited for informing why they're important
