### ISSUE TITLE
GRIPSS : Exception in thread "main" java.lang.IllegalStateException: contig 21 not defined

### ISSUE THREAD

**Issue by BoudSTER** [hartwigmedical/hmftools#204]
Hi,

I tried to run GRIPSS on a vcf file product by a joint call (Tumour Vs normal) of GRIDSS.
But an error occurs that I can't correct. I tried with different couple but the problem persists. These are the couple for which I have run gridss_somatic_filter without any problem.

Thank you for the time you can give me.

BoudSTER

```
gripss \
> -input_vcf /mnt/isilon_data_nfs/CRUNCH/AUGUSTIN/MM/scratch/L2007916D05_L2007917D03_solo.allocated.vcf \
> -output_vcf /mnt/isilon_data_nfs/CRUNCH/AUGUSTIN/MM/scratch/test_gripss.vcf \
> -breakend_pon /mnt/isilon_data_nfs/CRUNCH/AUGUSTIN/REF/pon_directory_Hg19/gridss_pon_single_breakend.bed \
> -breakpoint_pon /mnt/isilon_data_nfs/CRUNCH/AUGUSTIN/REF/pon_directory_Hg19/gridss_pon_breakpoint.bedpe \
> -breakpoint_hotspot /mnt/isilon_data_nfs/CRUNCH/AUGUSTIN/MM/scratch/known_fusions.37.bedpe \
> -ref_genome /mnt/isilon_data_nfs/CRUNCH/AUGUSTIN/REF/ucsc.hg19.fasta \
> -reference P027-L2007917D03T2_S123_L002 \
> -tumor P019-L2007916D05T2_S115_L002
14:20:56 - Config GripssFilterConfig(hardMinTumorQual=100, hardMaxNormalAbsoluteSupport=3, hardMaxNormalRelativeSupport=0.08, softMaxNormalRelativeSupport=0.03, minNormalCoverage=8, minTumorAF=0.005, maxShortStrandBias=0.95, minQualBreakEnd=1000, minQualBreakPoint=400, minQualRescueMobileElementInsertion=1000, maxHomLengthShortInversion=6, maxInexactHomLengthShortDel=5, minLength=32, polyGCRegion=2:33141260-33141700     +       .)
14:20:56 - Using P027-L2007917D03T2_S123_L002 as reference sample
14:20:56 - Using P019-L2007916D05T2_S115_L002 as tumor sample
14:20:56 - Reading hotspot file: /mnt/isilon_data_nfs/CRUNCH/AUGUSTIN/MM/scratch/known_fusions.37.bedpe
14:20:56 - Finished in 0 seconds
Exception in thread "main" java.lang.IllegalStateException: contig 21 not defined
        at com.hartwig.hmftools.gripss.ContigComparator.compare(ContigComparator.kt:43)
        at com.hartwig.hmftools.bedpe.Breakpoint$Companion.fromBedpe(Location.kt:64)
        at com.hartwig.hmftools.bedpe.Breakpoint$Companion.fromBedpeFile(Location.kt:56)
        at com.hartwig.hmftools.gripss.GripssApplication.run(GripssApplication.kt:90)
        at com.hartwig.hmftools.gripss.GripssApplicationKt.main(GripssApplication.kt:40)
```

**Comment by charlesshale** [comment]
I think that error is occurring because the VCF has HG19 chromosome prefixes (ie 'chr'), whereas those reference BED files (ie for PON and hotspot locations) are expecting no prefix. A work-around would be to add the prefix to your reference files, or switch to GRCh37.

thanks,

Charles
