### ISSUE TITLE
SAGE exception

### ISSUE THREAD

**Issue by jaesvi** [hartwigmedical/hmftools#209]
Hi,
I am trying to run SAGE on a cancer cohort and for a few samples I am getting an Exception that I have not been able to interpret. 
My command is: 

```
SAGE -Xms4G -Xmx32G  -threads 8 -tumor PD22036a -tumor_bam PD22036a.realgned.recal.md.bam \
-reference PD22036b -reference_bam PD22036b.realgned.recal.md.bam -out PD22036a_PD22036b.sage.vcf.gz \
-ref_genome hs37d5.fa  -assembly hg19 -hotspots HMFTools-Resources/Sage/37/KnownHotspots.somatic.37.vcf.gz \
-panel_bed HMFTools-Resources/Sage/37/ActionableCodingPanel.somatic.37.bed.gz \
-high_confidence_bed HMFTools-Resources/GIAB-High-Conf/NA12878_GIAB_highconf_IllFB-IllGATKHC-CG-Ion-Solid_ALLCHROM_v3.2.2_highconf.bed.gz 
```

After which I get the following error:
```
11:32:58 - 1 - SAGE version: 2.8
11:32:58 - 1 - Using non default value 8 for parameter threads
11:32:59 - 1 - Reading bed file: HMFTools-Resources/Sage/37/ActionableCodingPanel.somatic.37.bed.gz
11:32:59 - 1 - Reading hotspot vcf: HMFTools-Resources/Sage/37/KnownHotspots.somatic.37.vcf.gz
11:32:59 - 1 - Reading bed file: HMFTools-Resources/GIAB-High-Conf/NA12878_GIAB_highconf_IllFB-IllGATKHC-CG-Ion-Solid_ALLCHROM_v3.2.2_highconf.bed.gz
11:33:05 - 1 - Writing to file: PD22036a_PD22036b.sage.vcf.gz
11:33:05 - 1 - Beginning quality recalibration
11:36:29 - 20 - Writing base quality recalibration file: PD22036b.sage.bqr.tsv
11:36:30 - 20 - Executing R script via command: Rscript /tmp/script3032641353564204296.R PD22036b.sage.bqr.tsv
11:40:30 - 15 - Writing base quality recalibration file: PD22036a.sage.bqr.tsv
11:40:30 - 15 - Executing R script via command: Rscript /tmp/script15582807275261140432.R PD22036a.sage.bqr.tsv
11:40:58 - 1 - Processing chromosome 1
11:40:58 - 1 - Error at chromosome: 1, position: 94803
11:40:59 - 21 - Error at chromosome: 1, position: 241262
11:41:00 - 15 - Error at chromosome: 1, position: 1207388
11:41:00 - 18 - Error at chromosome: 1, position: 1011861
11:41:00 - 16 - Error at chromosome: 1, position: 564679
11:41:00 - 19 - Error at chromosome: 1, position: 929659
11:41:00 - 21 - Error at chromosome: 1, position: 1122196
11:41:00 - 17 - Error at chromosome: 1, position: 108545
....
11:44:16 - 15 - Error at chromosome: 1, position: 249206969
11:44:16 - 21 - Error at chromosome: 1, position: 248739432
11:44:16 - 20 - Error at chromosome: 1, position: 248605323
11:44:16 - 14 - Error at chromosome: 1, position: 248405791
11:44:16 - 16 - Error at chromosome: 1, position: 249105909
Exception in thread "main" java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Inappropriate call if not paired read
    at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
    at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1999)
    at com.hartwig.hmftools.sage.pipeline.ChromosomePipeline.process(ChromosomePipeline.java:82)
    at com.hartwig.hmftools.sage.SageApplication.run(SageApplication.java:129)
    at com.hartwig.hmftools.sage.SageApplication.main(SageApplication.java:72)
Caused by: java.lang.IllegalStateException: Inappropriate call if not paired read
    at htsjdk.samtools.SAMRecord.requireReadPaired(SAMRecord.java:892)
    at htsjdk.samtools.SAMRecord.getProperPairFlag(SAMRecord.java:900)
    at com.hartwig.hmftools.sage.read.ReadContextCounter.calculateQualityScore(ReadContextCounter.java:337)
    at com.hartwig.hmftools.sage.read.ReadContextCounter.accept(ReadContextCounter.java:235)
    at com.hartwig.hmftools.sage.evidence.ReadContextEvidence.lambda$null$0(ReadContextEvidence.java:69)
    at com.hartwig.hmftools.sage.select.PositionSelector.select(PositionSelector.java:53)
    at com.hartwig.hmftools.sage.select.SamRecordSelector.select(SamRecordSelector.java:23)
    at com.hartwig.hmftools.sage.evidence.ReadContextEvidence.lambda$get$1(ReadContextEvidence.java:69)
    at com.hartwig.hmftools.sage.sam.SamSlicer.slice(SamSlicer.java:54)
    at com.hartwig.hmftools.sage.evidence.ReadContextEvidence.get(ReadContextEvidence.java:66)
    at com.hartwig.hmftools.sage.pipeline.EvidenceStage.lambda$null$0(EvidenceStage.java:39)
    at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:680)
    at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:658)
    at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2094)
    at com.hartwig.hmftools.sage.pipeline.EvidenceStage.lambda$evidence$2(EvidenceStage.java:39)
    at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1106)
    at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2235)
    at com.hartwig.hmftools.sage.pipeline.EvidenceStage.evidence(EvidenceStage.java:29)
    at com.hartwig.hmftools.sage.pipeline.SomaticPipeline.variants(SomaticPipeline.java:57)
    at com.hartwig.hmftools.sage.pipeline.ChromosomePipeline.process(ChromosomePipeline.java:77)
    ... 2 more
```

Any hints to try to fix it?

Many thanks,
Jose

**Comment by p-priestley** [comment]
Hi Jose,  

I have not seen this error before.  The exception seems to be occurring in the htsjdk due to PURPLE trying to read the ProperPair flag (ie. the 0x2 bit in the bitwise FLAG).   I assume you definitely have paired end data?   

If you are able to make a small shareable bam which produces the error then we be happy to look at it.

Peter

**Comment by jaesvi** [comment]
Hi Peter,
The data _should_ be paired-end and I do get reads with the 0x1 and 0x2 bit flags. I can share a little bundle with tumor and normal of one of the samples (1 Mb from chr21). 
[test.tar.gz](https://github.com/hartwigmedical/hmftools/files/7153713/test.tar.gz)
Many thanks,
Jose

**Comment by jaesvi** [comment]
Hi Peter,

Did you get a chance to look at these BAMs? Sorry to bother.
Thanks,
Jose

**Comment by charlesshale** [comment]
Hi Jose,

I can reproduce the exception you hit. There are reads in the BAM which do not have the read-paired flag set, eg:

HSQ-700848:338:D168LACXX:7:1312:19373:79918 1/2 101b aligned to 21:16777250-16777350. (flags = 81)

The SAMRecord called by Sage is not checking that the read-pair flag is set before checking that the read is part of a proper pair. 

Here is the SAMRecord code showing the failing condition:

    public boolean getReadPairedFlag() {
        return (this.mFlags & SAMFlag.READ_PAIRED.flag) != 0;
    }

    private void requireReadPaired() {
        if (!this.getReadPairedFlag()) {
            throw new IllegalStateException("Inappropriate call if not paired read");
        }
    }

    public boolean getProperPairFlag() {
        this.requireReadPaired();
        return this.getProperPairFlagUnchecked();
    }


I'm going to change Sage to first check the read-paired flag explicitly so it treats these reads as improper and continues on without crashing. Will create a Sage 3.1 in the next week or so.

In the meantime perhaps there are ways to filter out these reads or change the way the BAM was produced? Our pipeline has not encountered a BAM with reads in this state before.

thanks,

Charles

**Comment by jaesvi** [comment]
This seems to be the case indeed. Thanks for your time, this should indeed not happen in the BAM file, but it's one of the perks of re-using data, you get to crash tools in unexpected ways :)
