### ISSUE TITLE
SAGE: Exception "Duplicate allele added to VariantContext: A"

### ISSUE THREAD

**Issue by vladsaveliev** [hartwigmedical/hmftools#22]
Hi!

I'm running SAGE as follows, and getting an error:

```
java -Xmx64G -Xms4G \
     -cp sage-1.0-jar-with-dependencies.jar com.hartwig.hmftools.sage.SageHotspotApplication \
     -tumor CCR180075_WH18T002P017 -tumor_bam CCR180075_WH18T002P017-ready.bam \
     -reference CCR180074_WH18B001P017 -reference_bamCCR180074_WH18B001P017-ready.bam \
     -known_hotspots Hotspot.tsv \
     -coding_regions coding_regions.canonical.sort.merged.bed \
     -ref_genome GRCh37.fa \
     -out saged.vcf.gz
17:33:37 - Loading coding regions from coding_regions.canonical.sort.merged.bed
17:33:38 - Loading known hotspots from Hotspot.tsv
17:33:38 - Looking for potential inframe indel locations
17:33:45 - Looking for evidence of hotspots in tumor bam small_test/CCR180075_WH18T002P017-ready.bam
17:33:45 - Looking for evidence of hotspots in reference bam small_test/CCR180074_WH18B001P017-ready.bam
17:33:46 - Writing output to small_test/saged.vcf.gz
17:33:46 - Complete
Exception in thread "main" java.lang.IllegalArgumentException: Duplicate allele added to VariantContext: T
        at htsjdk.variant.variantcontext.VariantContext.makeAlleles(VariantContext.java:1487)
        at htsjdk.variant.variantcontext.VariantContext.<init>(VariantContext.java:380)
        at htsjdk.variant.variantcontext.VariantContextBuilder.make(VariantContextBuilder.java:494)
        at htsjdk.variant.variantcontext.VariantContextBuilder.make(VariantContextBuilder.java:488)
        at com.hartwig.hmftools.common.hotspot.HotspotEvidenceVCF.create(HotspotEvidenceVCF.java:153)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.Collections$2.tryAdvance(Collections.java:4717)
        at java.util.Collections$2.forEachRemaining(Collections.java:4725)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at com.hartwig.hmftools.common.hotspot.HotspotEvidenceVCF.create(HotspotEvidenceVCF.java:107)
        at com.hartwig.hmftools.common.hotspot.HotspotEvidenceVCF.write(HotspotEvidenceVCF.java:78)
        at com.hartwig.hmftools.sage.SageHotspotApplication.run(SageHotspotApplication.java:127)
        at com.hartwig.hmftools.sage.SageHotspotApplication.main(SageHotspotApplication.java:52)
```

Attaching a zip archive [sage_test.zip](https://github.com/hartwigmedical/hmftools/files/2798711/sage_test.zip) with:
- `CCR180075_WH18T002P017-ready.bam` and `CCR180074_WH18B001P017-ready.bam` - the toy input BAM files I'm using;
- `coding_regions.canonical.sort.merged.bed` - the coding regions BED file I'm using (generated from Ensemble GTF, using coding CDS of canonical transcripts, then bedtools-merged), 
- `Hotspot.tsv` - the hotspots file which I downloaded from the HMF website.

I also tried on a full whole genome BAMs as well - got a similar error.

I built Sage jar with maven from a clone of this repository.

Wondering if you could take a look by any change? Suspecting I might be using a wrong hotspots file, or in a wrong format.

Vlad

**Comment by jonbaber** [comment]
Hi Vlad, 

Thanks very much for the clear description and reproducible test case. This bug is caused by an unexpected entry in the hotspot file where alt = ref. 

I will fix this, but in the meantime you can work around this issue by using the latest hotspot file KnownHotspots.tsv available at https://resources.hartwigmedicalfoundation.nl/ under Pipeline Resources. I have checked and it works for your example data. 

If it is still available, could you please let me know which page you got the Hotspot.tsv file you are using from? I will then remove it.

Regards, Jonathan

**Comment by vladsaveliev** [comment]
Jonathan,

I've just tried with the latest `KnownHotspots.tsv`, and my run is working now! Thanks so much for finding the issue.

I don't think the older file is still available. I downloaded it a few months ago from the same page (if I remember correctly), and I guess since then it was updated. Should have checked for a new one before running SAGE :)

Thanks,
Vlad
