### ISSUE TITLE
SAGE: Cannot add position: x before min position: y

### ISSUE THREAD

**Issue by ckrushton** [hartwigmedical/hmftools#220]
I've been running SAGE on an external dataset which was aligned using BWA and GATK's IndelRealigner, and on a subset of samples I am running into an error similar to this:
```
Exception in thread "main" java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Cannot add position: 90374805 before min position: 90374866
        at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
        at com.hartwig.hmftools.sage.pipeline.ChromosomePipeline.process(ChromosomePipeline.java:82)
        at com.hartwig.hmftools.sage.SageApplication.run(SageApplication.java:131)
        at com.hartwig.hmftools.sage.SageApplication.main(SageApplication.java:72)
Caused by: java.lang.IllegalArgumentException: Cannot add position: 90374805 before min position: 90374866
        at com.hartwig.hmftools.sage.count.EvictingArray.computeIfAbsent(EvictingArray.java:30)
        at com.hartwig.hmftools.sage.context.RefContextFactory.refContext(RefContextFactory.java:46)
        at com.hartwig.hmftools.sage.context.RefContextConsumer.processAlignment(RefContextConsumer.java:184)
        at com.hartwig.hmftools.sage.context.RefContextConsumer.access$000(RefContextConsumer.java:28)
        at com.hartwig.hmftools.sage.context.RefContextConsumer$1.handleAlignment(RefContextConsumer.java:60)
        at com.hartwig.hmftools.sage.sam.CigarTraversal.traverseCigar(CigarTraversal.java:53)
        at com.hartwig.hmftools.sage.context.RefContextConsumer.accept(RefContextConsumer.java:78)
        at com.hartwig.hmftools.sage.evidence.CandidateEvidence.lambda$get$1(CandidateEvidence.java:62)
        at com.hartwig.hmftools.sage.sam.SamSlicer.slice(SamSlicer.java:54)
        at com.hartwig.hmftools.sage.evidence.CandidateEvidence.get(CandidateEvidence.java:85)
        at com.hartwig.hmftools.sage.evidence.CandidateEvidence.get(CandidateEvidence.java:70)
        at com.hartwig.hmftools.sage.pipeline.CandidateStage.lambda$null$0(CandidateStage.java:59)
        at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
        at java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:614)
        at java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:1983)
        at com.hartwig.hmftools.sage.pipeline.CandidateStage.lambda$candidates$2(CandidateStage.java:59)
        at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952)
        at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926)
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1595)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```
(Note that the exact chromosome/position differs between samples). Inspecting these samples in IGV, it appears these regions all contain reads with extremely large deletions, and the first position (x, 90374805) corresponds to the start position of this read. I'm guessing there is an internal window for examining a read which this large deletion is violating?
[IGV screenshot](https://imgur.com/a/Rzyx4cA)

**Comment by p-priestley** [comment]
We have not seen this error before, but I think you may be on the right track with the internal window diagnosis.   I have not seen BWA align with such a large deletion before.

Would you mind sharing a mini-bam including 1kb each side so we can test?   If you are not comfortable to share here, you could instead send it to  p.priestley@hartwigmedicalfoundation.nl

**Comment by ckrushton** [comment]
I think those reads are the end product of GATK's IndelRealigner, as I've never seen BWA align reads in such a way either, I sent you an e-mail containing a BAM with the reads in that region.

**Comment by charlesshale** [comment]
I've updated Sage to no longer crash when it processes read out-of-order (which some of these were). I tried re-sorting the realigned BAM and it didn't seem to help.

Beta 3.0 release here:

https://github.com/hartwigmedical/hmftools/releases/tag/sage-v3.0_beta

**Comment by Kdreval** [comment]
@charlesshale Thank you for addressing this issue, I am looking forward to using this feature in my analyses! Any timeline to have this released? It is not on conda yet and I am wondering whether there are plans to release version 3.0 soon?

**Comment by p-priestley** [comment]
We are testing currently and hope to release within a week.

Note that SAGE 3.0 has quite some other improvements also - including a new phasing model that allows phasing out to 150 bases and partial phasing of variants, better deduplication of variants and several improvements to filtering.

**Comment by Kdreval** [comment]
Thanks @p-priestley  for the update! Looking forward to testing it soon!

**Comment by Kdreval** [comment]
@p-priestley , any update on this? Thanks!

**Comment by charlesshale** [comment]
Pretty much ready to go - the official release will probably be next week, but the beta has all details now and the read-me has been updated:

https://github.com/hartwigmedical/hmftools/releases/tag/sage-v3.0_beta
