### ISSUE TITLE
Could not run Linx

### ISSUE THREAD

**Issue by YingYa** [hartwigmedical/hmftools#226]
Hi I could not run linx.jar on CentOS7 with java8:

/share/app/java/jdk1.8.0_261/bin/java -jar linx_v1.16.jar
15:11:01 - [INFO ] - LINX version: 1.16
Exception in thread "main" java.lang.NullPointerException
        at sun.nio.fs.UnixPath.normalizeAndCheck(UnixPath.java:77)
        at sun.nio.fs.UnixPath.<init>(UnixPath.java:71)
        at sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:281)
        at java.nio.file.Paths.get(Paths.java:84)
        at com.hartwig.hmftools.common.utils.FileWriterUtils.checkCreateOutputDir(FileWriterUtils.java:32)
        at com.hartwig.hmftools.linx.LinxApplication.main(LinxApplication.java:76)

**Comment by toddajohnson** [comment]
In my experience, that is what Linx does if you do not provide it with the needed command line arguments described at https://github.com/hartwigmedical/hmftools/tree/master/linx under "Example Usage".

FWIW, it would be nice if it would return the "help" that is often provided by other programs when run without arguments, but that is where the README comes in.

**Comment by YingYa** [comment]
Thanks @toddajohnson , 

Yes, I intended to get help information from linx. I will try to run linx with necessary arguments.
