### ISSUE TITLE
New GRIPSS version does not generate recovery VCF

### ISSUE THREAD

**Issue by jamesdalg** [hartwigmedical/hmftools#231]
https://github.com/hartwigmedical/hmftools/issues/132
The new version of GRIPSS only provides one VCF file. Is this assumed to be the high confidence file, while I use the gripss output for the recovery SV?

module load java/17.0.1
java -jar  /data/CCRBioinfo/dalgleishjl/sv_mapping/gridss/gripss/gripss-1.11.jar \
   -tumor PAUTWB_T \
   -reference PAUTWB_N \
   -ref_genome /data/CCRBioinfo/dalgleishjl/sv_mapping/hg38_ref/hg38.fa \
   -breakend_pon /data/CCRBioinfo/dalgleishjl/sv_mapping/gridss/ponhg38/gridss_pon_single_breakend.38.bed \
   -breakpoint_pon /data/CCRBioinfo/dalgleishjl/sv_mapping/gridss/ponhg38/gridss_pon_breakpoint.38.bedpe \
   -breakpoint_hotspot /data/CCRBioinfo/dalgleishjl/sv_mapping/gridss/external_resources/HMFTools-Resources/Known-Fusions/38/known_fusions.38.bedpe \
   -input_vcf /data/CCRBioinfo/dalgleishjl/sv_mapping/gridss_purple_linx/PAUTWB_T_N_gridss_paired/gridss_PAUTWB_T_N_paired_output.vcf.gz \
   -output_vcf /data/CCRBioinfo/dalgleishjl/sv_mapping/gridss_purple_linx/PAUTWB_T_N_gridss_paired/PAUTWB_T_N_paired_gripss.vcf.gz

It only generates this last file, from what I can tell, not the two VCF files required for purple. Perhaps this is just a minor documentation issue or something that I have missed.

**Comment by jamesdalg** [comment]
I tried running purple with the GRIPSS VCF and the GRIDSS VCF as recovery, but it doesn't seem to work:

`bash-4.2$ java -jar /data/CCRBioinfo/dalgleishjl/sv_mapping/gridss_purple_linx/hmftools/purple/purple_v3.1.jar    -reference PAUTWB_N    -tumor PAUTWB_T    -output_dir /data/CCRBioinfo/dalgleishjl/sv_mapping/PAUTWB_purple/    -amber /data/CCRBioinfo/dalgleishjl/sv_mapping/PAUTWB_amber  -cobalt /data/CCRBioinfo/dalgleishjl/sv_mapping/PAUTWB_cobalt  -gc_profile /data/CCRBioinfo/dalgleishjl/sv_mapping/gridss_purple_linx/hmftools/cobalt/GC_profile.1000bp.38.cnp    -ref_genome /data/CCRBioinfo/dalgleishjl/sv_mapping/hg38_ref/hg38.fa -structural_vcf /data/CCRBioinfo/dalgleishjl/sv_mapping/gridss_purple_linx/PAUTWB_T_N_gridss_paired/PAUTWB_T_N_paired_gripss.vcf.gz -sv_recovery_vcf /data/CCRBioinfo/dalgleishjl/sv_mapping/gridss_purple_linx/PAUTWB_T_N_gridss_paired/gridss_PAUTWB_T_N_paired_output.vcf.gz
09:43:02 - [INFO ] - PURPLE version: 3.1
09:43:02 - [INFO ] - Reference Sample: PAUTWB_N, Tumor Sample: PAUTWB_T
09:43:02 - [INFO ] - Output Directory: /data/CCRBioinfo/dalgleishjl/sv_mapping/PAUTWB_purple/
09:43:02 - [INFO ] - Using ref genome: V38
09:43:04 - [INFO ] - Reading GC Profiles from /data/CCRBioinfo/dalgleishjl/sv_mapping/gridss_purple_linx/hmftools/cobalt/GC_profile.1000bp.38.cnp
09:43:09 - [INFO ] - Processing sample(ref=PAUTWB_N tumor=PAUTWB_T)
09:43:09 - [INFO ] - Reading amber QC from /data/CCRBioinfo/dalgleishjl/sv_mapping/PAUTWB_amber/PAUTWB_T.amber.qc
09:43:09 - [INFO ] - Reading amber bafs from /data/CCRBioinfo/dalgleishjl/sv_mapping/PAUTWB_amber/PAUTWB_T.amber.baf.tsv
09:43:10 - [INFO ] - Reading amber pcfs from /data/CCRBioinfo/dalgleishjl/sv_mapping/PAUTWB_amber/PAUTWB_T.amber.baf.pcf
09:43:10 - [INFO ] - Average amber tumor depth is 138 reads implying an ambiguous BAF of 0.537
09:43:10 - [INFO ] - Reading cobalt ratios from /data/CCRBioinfo/dalgleishjl/sv_mapping/PAUTWB_cobalt/PAUTWB_T.cobalt.ratio.tsv
09:43:15 - [INFO ] - Reading cobalt reference segments from /data/CCRBioinfo/dalgleishjl/sv_mapping/PAUTWB_cobalt/PAUTWB_N.cobalt.ratio.pcf
09:43:15 - [INFO ] - Reading cobalt tumor segments from /data/CCRBioinfo/dalgleishjl/sv_mapping/PAUTWB_cobalt/PAUTWB_T.cobalt.ratio.pcf
09:43:17 - [INFO ] - Loading structural variants from /data/CCRBioinfo/dalgleishjl/sv_mapping/gridss_purple_linx/PAUTWB_T_N_gridss_paired/PAUTWB_T_N_paired_gripss.vcf.gz
09:43:20 - [INFO ] - Somatic variants support disabled.
09:43:20 - [INFO ] - Sample gender is male
09:43:20 - [INFO ] - Applying segmentation
09:43:20 - [INFO ] - Merging reference and tumor ratio break points
09:43:27 - [INFO ] - Fitting purity
09:44:06 - [INFO ] - Sample maxDiploidProportion(0.454) diploidCandidates(93) purityRange(0.470 - 0.700) hasTumor(true)
09:44:06 - [INFO ] - Calculating copy number
09:44:07 - [INFO ] - Loading recovery candidates from /data/CCRBioinfo/dalgleishjl/sv_mapping/gridss_purple_linx/PAUTWB_T_N_gridss_paired/gridss_PAUTWB_T_N_paired_output.vcf.gz
09:44:09 - [INFO ] - Reapplying segmentation with 3 recovered structural variants
09:44:09 - [INFO ] - Merging reference and tumor ratio break points
09:44:13 - [INFO ] - Recalculating copy number
09:44:15 - [INFO ] - Calculating chromosome copy number arm
09:44:15 - [INFO ] - Generating QC Stats
09:44:15 - [INFO ] - Modelling somatic peaks
09:44:15 - [ERROR] - failed processing sample(PAUTWB_T): htsjdk.tribble.TribbleException$MalformedFeatureFile: Unable to parse header with error: java.io.IOException: Is a directory, for input source: file:///spin1/home/linux/dalgleishjl/
htsjdk.tribble.TribbleException$MalformedFeatureFile: Unable to parse header with error: java.io.IOException: Is a directory, for input source: file:///spin1/home/linux/dalgleishjl/
        at htsjdk.tribble.TribbleIndexedFeatureReader.readHeader(TribbleIndexedFeatureReader.java:263)
        at htsjdk.tribble.TribbleIndexedFeatureReader.<init>(TribbleIndexedFeatureReader.java:102)
        at htsjdk.tribble.TribbleIndexedFeatureReader.<init>(TribbleIndexedFeatureReader.java:127)
        at htsjdk.tribble.AbstractFeatureReader.getFeatureReader(AbstractFeatureReader.java:121)
        at htsjdk.tribble.AbstractFeatureReader.getFeatureReader(AbstractFeatureReader.java:81)
        at htsjdk.variant.vcf.VCFFileReader.<init>(VCFFileReader.java:145)
        at htsjdk.variant.vcf.VCFFileReader.<init>(VCFFileReader.java:95)
        at com.hartwig.hmftools.purple.somatic.SomaticPeakStream.somaticPeakModel(SomaticPeakStream.java:96)
        at com.hartwig.hmftools.purple.PurpleApplication.processSample(PurpleApplication.java:288)
        at com.hartwig.hmftools.purple.PurpleApplication.run(PurpleApplication.java:150)
        at com.hartwig.hmftools.purple.PurpleApplication.main(PurpleApplication.java:503)
Caused by: htsjdk.samtools.util.RuntimeIOException: java.io.IOException: Is a directory
        at htsjdk.tribble.readers.SynchronousLineReader.readLine(SynchronousLineReader.java:53)
        at htsjdk.tribble.readers.LineIteratorImpl.advance(LineIteratorImpl.java:24)
        at htsjdk.tribble.readers.LineIteratorImpl.advance(LineIteratorImpl.java:11)
        at htsjdk.samtools.util.AbstractIterator.hasNext(AbstractIterator.java:44)
        at htsjdk.variant.vcf.VCFCodec.readActualHeader(VCFCodec.java:89)
        at htsjdk.tribble.AsciiFeatureCodec.readHeader(AsciiFeatureCodec.java:79)
        at htsjdk.tribble.AsciiFeatureCodec.readHeader(AsciiFeatureCodec.java:37)
        at htsjdk.tribble.TribbleIndexedFeatureReader.readHeader(TribbleIndexedFeatureReader.java:261)
        ... 10 more
Caused by: java.io.IOException: Is a directory
        at java.base/sun.nio.ch.FileDispatcherImpl.read0(Native Method)
        at java.base/sun.nio.ch.FileDispatcherImpl.read(FileDispatcherImpl.java:48)
        at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:330)
        at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:296)
        at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:273)
        at java.base/sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:229)
        at htsjdk.samtools.seekablestream.SeekablePathStream.read(SeekablePathStream.java:86)
        at java.base/java.io.InputStream.read(InputStream.java:218)
        at htsjdk.tribble.readers.PositionalBufferedStream.fill(PositionalBufferedStream.java:132)
        at htsjdk.tribble.readers.PositionalBufferedStream.read(PositionalBufferedStream.java:84)
        at java.base/sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:270)
        at java.base/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:313)
        at java.base/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:188)
        at java.base/java.io.InputStreamReader.read(InputStreamReader.java:177)
        at htsjdk.tribble.readers.LongLineBufferedReader.fill(LongLineBufferedReader.java:140)
        at htsjdk.tribble.readers.LongLineBufferedReader.readLine(LongLineBufferedReader.java:300)
        at htsjdk.tribble.readers.LongLineBufferedReader.readLine(LongLineBufferedReader.java:356)
        at htsjdk.tribble.readers.SynchronousLineReader.readLine(SynchronousLineReader.java:51)
        ... 17 more
09:44:15 - [INFO ] - Complete
`

**Comment by jamesdalg** [comment]
Reading through the java code, I think I've pinpointed the line where this is breaking:

`
       final List<PeakModel> somaticPeaks = somaticPeakStream.somaticPeakModel(
                purityAdjuster, copyNumbers, enrichedFittedRegions, sampleDataFiles.SomaticVcfFile);
`

One of these arguments is the somaticVcfFile. Given these lines in the errors, I assume it has to do with reading the somatic VCF:
`        at htsjdk.variant.vcf.VCFFileReader.<init>(VCFFileReader.java:145)
        at htsjdk.variant.vcf.VCFFileReader.<init>(VCFFileReader.java:95)
`

**Comment by charlesshale** [comment]
Once Gripss has been run the first time to apply the hard and soft filters, it then needs to be called again to produce the filtered SV file, as is described in the READ-ME:

java -cp gripss.jar com.hartwig.hmftools.gripss.GripssHardFilterApplicationKt \
   -input_vcf /path/to/SAMPLE_T.gripss.vcf.gz \
   -output_vcf /path/to/SAMPLE_T.gripss.filtered.vcf.gz 

So the first run will produce a file showing all non-hard-filtered SVs and their soft-filter values eg SAMPLE_T.gripss.vcf.gz.

The second run will then produce a filtered VCF with only PASS and PON SVs.

It is these 2 VCFs which are then fed into Purple. The second, filtered VCF should be passed to Purple as 'structural_vcf'. The first unfiltered VCF is the 'recovery' SV VCF, ie config 'sv_recovery_vcf'.
