### ISSUE TITLE
Linx erros

### ISSUE THREAD

**Issue by msubirana** [hartwigmedical/hmftools#249]
I'm running Linx as:

`java -jar $EBROOTLINX/linx_v1.17_beta.jar -sample $sample_name -ref_genome_version 38 -sv_vcf $sv_vcf -purple_dir $output_dir_purple -output_dir $output_dir_linx -fragile_site_file $fragile_site_file -line_element_file $line_element_file -check_fusions -known_fusion_file $known_fusion_file -check_drivers -driver_gene_panel $DriverGenePanel -log_debug `

And I got the following error:

`10:49:42 - [INFO ] - LINX version: 1.17
Exception in thread "main" org.apache.commons.cli.UnrecognizedOptionException: Unrecognized option: -ensembl_data_dir
	at org.apache.commons.cli.DefaultParser.handleUnknownToken(DefaultParser.java:347)
	at org.apache.commons.cli.DefaultParser.handleConcatenatedOptions(DefaultParser.java:689)
	at org.apache.commons.cli.DefaultParser.handleShortAndLongOption(DefaultParser.java:520)
	at org.apache.commons.cli.DefaultParser.handleToken(DefaultParser.java:243)
	at org.apache.commons.cli.DefaultParser.parse(DefaultParser.java:120)
	at org.apache.commons.cli.DefaultParser.parse(DefaultParser.java:76)
	at org.apache.commons.cli.DefaultParser.parse(DefaultParser.java:60)
	at com.hartwig.hmftools.linx.LinxApplication.createCommandLine(LinxApplication.java:363)
	at com.hartwig.hmftools.linx.LinxApplication.main(LinxApplication.java:57)`

If I revome the -ensembl_data_dir option I got:

`10:50:20 - [INFO ] - LINX version: 1.17
Exception in thread "main" java.lang.IllegalArgumentException: No enum constant com.hartwig.hmftools.common.drivercatalog.panel.DriverGeneGermlineReporting.FALSE
	at java.lang.Enum.valueOf(Enum.java:238)
	at com.hartwig.hmftools.common.drivercatalog.panel.DriverGeneGermlineReporting.valueOf(DriverGeneGermlineReporting.java:3)
	at com.hartwig.hmftools.common.drivercatalog.panel.DriverGeneFile.fromString(DriverGeneFile.java:92)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.hartwig.hmftools.common.drivercatalog.panel.DriverGeneFile.read(DriverGeneFile.java:36)
	at com.hartwig.hmftools.common.drivercatalog.panel.DriverGenePanelConfig.driverGenes(DriverGenePanelConfig.java:38)
	at com.hartwig.hmftools.linx.LinxConfig.loadDriverGenes(LinxConfig.java:183)
	at com.hartwig.hmftools.linx.LinxConfig.<init>(LinxConfig.java:162)
	at com.hartwig.hmftools.linx.LinxApplication.main(LinxApplication.java:74)`

**Comment by charlesshale** [comment]
Could you try the official release of Linx v1.17:

https://github.com/hartwigmedical/hmftools/releases/tag/linx-v1.17

The beta may have still used the previous config tag of "gene_transcript_dir" for the Ensembl data cache.

thanks.

**Comment by msubirana** [comment]
I tried with the new version and the changes that you suggested and I got:

`12:54:29 - [INFO ] - LINX version: 1.17
Exception in thread "main" java.lang.IllegalArgumentException: No enum constant com.hartwig.hmftools.common.drivercatalog.panel.DriverGeneGermlineReporting.FALSE
	at java.base/java.lang.Enum.valueOf(Enum.java:273)
	at com.hartwig.hmftools.common.drivercatalog.panel.DriverGeneGermlineReporting.valueOf(DriverGeneGermlineReporting.java:3)
	at com.hartwig.hmftools.common.drivercatalog.panel.DriverGeneFile.fromLines(DriverGeneFile.java:89)
	at com.hartwig.hmftools.common.drivercatalog.panel.DriverGeneFile.read(DriverGeneFile.java:36)
	at com.hartwig.hmftools.common.drivercatalog.panel.DriverGenePanelConfig.driverGenes(DriverGenePanelConfig.java:38)
	at com.hartwig.hmftools.linx.LinxConfig.loadDriverGenes(LinxConfig.java:206)
	at com.hartwig.hmftools.linx.LinxConfig.<init>(LinxConfig.java:177)
	at com.hartwig.hmftools.linx.LinxApplication.main(LinxApplication.java:57)
`

**Comment by msubirana** [comment]
Okey now I working! It was about the DriverPanel file!

One more question, the sv_vcf input, which file from gridss should be used? The raw, filtered, somatic?

**Comment by msubirana** [comment]
Now is working but there are some errors:

`15:24:38 - [INFO ] - LINX version: 1.17
15:24:38 - [INFO ] - running SV analysis for NET1_TI
15:24:38 - [INFO ] - loaded known fusion data: KNOWN_PAIR(405), EXON_DEL_DUP(13), IG_PROMISCUOUS(1), PROMISCUOUS_5(31), PROMISCUOUS_3(33), IG_KNOWN_PAIR(20)
15:24:40 - [INFO ] - loaded 20 known fragile sites from file: fragile_sites_hmf.38.csv
15:24:40 - [INFO ] - loaded 124 known line elements from file: line_elements.38.csv
15:24:41 - [INFO ] - loaded 24813 SV data records from VCF file: gridss/NET1_somatic.vcf.gz
15:24:41 - [WARN ] - sample(NET1_TI) has 26763 unmatched CN-SV segments
15:24:41 - [ERROR] - failed to load driver catalog or purity context: java.nio.file.NoSuchFileException: purple/NET1_TI.driver.catalog.somatic.tsv
15:24:41 - [INFO ] - sample(NET1_TI) procesed 1 SVs
15:24:41 - [INFO ] - SV analysis complete for NET1_TI
`

I check and I don't have driver file from purple, any suggestion?

**Comment by charlesshale** [comment]
You can leave out the drivers file if you also remove the 'check_drivers' config option.

So Purple did not produce a NET1_TI.driver.catalog.somatic.tsv? Was this run with the latest, v3.2?
