### ISSUE TITLE
AMBER 3.6 java.lang.NullPointerException

### ISSUE THREAD

**Issue by scwatts** [hartwigmedical/hmftools#253]
Hi, I'm trying to run AMBER 3.6 on downsampled test data but an exception is raised shortly after launch. The downsampled test data and command used works with AMBER 3.5. Below is the AMBER 3.6 command that triggers the exception along with the traceback that is generated:

Command
```bash
java \
  -Xmx4G \
  -cp bin/amber-3.6.jar \
  com.hartwig.hmftools.amber.AmberApplication \
    -tumor T_SRR7890936_50p \
    -tumor_bam data/T_SRR7890936_50pc-ready.bam \
    -reference N_SRR789088 \
    -reference_bam data/N_SRR7890889-ready.bam \
    -output_dir amber-3.6/ \
    -threads 1 \
    -loci data/GermlineHetPon.38.vcf.gz
```

Traceback
```text
05:25:57 - AMBER version: 3.6
05:25:57 - Loading vcf file data/GermlineHetPon.38.vcf.gz
Exception in thread "main" java.lang.NullPointerException
	at com.hartwig.hmftools.amber.AmberApplication.readerFactory(AmberApplication.java:299)
	at com.hartwig.hmftools.amber.AmberApplication.runNormalMode(AmberApplication.java:104)
	at com.hartwig.hmftools.amber.AmberApplication.run(AmberApplication.java:97)
	at com.hartwig.hmftools.amber.AmberApplication.main(AmberApplication.java:336)
```

I've also worked up a minimal reproducible example below. Requires the use of Docker.
<details><summary>MRE (click to expand)</summary>

Script (save as `reproduce_exception.sh` in cwd)
```bash
#!/usr/bin/env bash
set -x

# Install reqiured software
mamba install -y \
  -c bioconda \
  -c conda-forge \
  -c defaults \
  bioconductor-copynumber \
  openjdk \
  samtools \
  wget

# Set directory names and base URLs
data_dir=data
bin_dir=bin
base_url_git=https://github.com/umccr/umccrise_test_data/raw/master/data/bcbio_test_project/final
base_url_hmf=https://nextcloud.hartwigmedicalfoundation.nl/s/LTiKTd8XxBqwaiC

# Create directories for downloads
mkdir -p ${data_dir} ${bin_dir}

# Download downsampled test data
wget -P ${data_dir} ${base_url_git}/N_SRR7890889/N_SRR7890889-ready.bam{,.bai}
wget -P ${data_dir} ${base_url_git}/T_SRR7890936_50pc/T_SRR7890936_50pc-ready.bam{,.bai}
wget -O ${data_dir}/GermlineHetPon.38.vcf.gz "${base_url_hmf}/download?path=%2FHMFTools-Resources%2FAmber%2F38&files=GermlineHetPon.38.vcf.gz"

# Download AMBER JARs
wget -O ${bin_dir}/amber-3.5.jar https://github.com/hartwigmedical/hmftools/releases/download/amber-v3.5/amber-3.5.jar
wget -O ${bin_dir}/amber-3.6.jar https://github.com/hartwigmedical/hmftools/releases/download/amber-v3.6/amber.jar

# Get tumor and normal sample names
function get_rg_sm() {
  samtools view -H "${1}" | sed -n '/^@RG/{s/^.\+SM:\([^ \t]\+\).\+$/\1/p}'
}
normal_name=$(get_rg_sm data/N_SRR7890889-ready.bam)
tumor_name=$(get_rg_sm data/T_SRR7890936_50pc-ready.bam)

# Run AMBER 3.5 (succeeds)
java \
  -Xmx4G \
  -cp ${bin_dir}/amber-3.5.jar \
  com.hartwig.hmftools.amber.AmberApplication \
    -tumor ${tumor_name} \
    -tumor_bam data/T_SRR7890936_50pc-ready.bam \
    -reference ${normal_name} \
    -reference_bam data/N_SRR7890889-ready.bam \
    -output_dir amber-3.5/ \
    -threads 1 \
    -loci data/GermlineHetPon.38.vcf.gz

# Run AMBER 3.6 (fails)
java \
  -Xmx4G \
  -cp ${bin_dir}/amber-3.6.jar \
  com.hartwig.hmftools.amber.AmberApplication \
    -tumor ${tumor_name} \
    -tumor_bam data/T_SRR7890936_50pc-ready.bam \
    -reference ${normal_name} \
    -reference_bam data/N_SRR7890889-ready.bam \
    -output_dir amber-3.6/ \
    -threads 1 \
    -loci data/GermlineHetPon.38.vcf.gz
```

Execute from cwd with the following:
```bash
docker run -ti -v $(pwd -P):/mount/ condaforge/mambaforge:4.11.0-2 /mount/reproduce_exception.sh
```
</details>

**Comment by hongwingl** [comment]
Thanks for reporting this. I have made a bug fix release:

https://github.com/hartwigmedical/hmftools/releases/tag/amber-v3.7

**Comment by scwatts** [comment]
Thank you for the quick response. Using AMBER 3.7 appears to work but I'm getting an unusual error message right at the end of the run:
```bash
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```

<details><summary>Command and full log (click to expand)</summary>

Command
```bash
java \
  -Xmx4G \
  -cp /data/bin/amber-3.7.jar \
  com.hartwig.hmftools.amber.AmberApplication \
    -tumor T_SRR7890936_50p \
    -tumor_bam /data/data/T_SRR7890936_50pc-ready.bam \
    -reference N_SRR789088 \
    -reference_bam /data/data/N_SRR7890889-ready.bam \
    -output_dir amber-3.7/ \
    -threads 1 \
    -loci /data/data/GermlineHetPon.38.vcf.gz
```
> Process reports an exit-code of `0` via `echo $?`

Log
```text
07:14:06 - AMBER version: 3.7
07:14:06 - Loading vcf file /data/data/GermlineHetPon.38.vcf.gz
07:14:08 - Processing 1337724 potential sites in reference bam /data/data/N_SRR7890889-ready.bam
07:14:14 -   [##########          ] 50% complete
07:14:14 -   [####################] 100% complete
07:14:21 -   [####################] 100% complete
07:14:29 -   [####################] 100% complete
07:14:33 -   [####################] 100% complete
07:14:33 -   [####################] 100% complete
07:14:44 -   [####################] 100% complete
07:14:45 -   [####################] 100% complete
07:14:49 -   [####################] 100% complete
07:14:51 -   [####################] 100% complete
07:14:54 -   [####################] 100% complete
07:14:58 -   [####################] 100% complete
07:15:05 -   [####################] 100% complete
07:15:06 -   [####################] 100% complete
07:15:11 -   [####################] 100% complete
07:15:12 - Median normal depth is 4 reads: filtering reads outside of 2 and 6
07:15:12 - Processing 164 heterozygous sites in tumor bam /data/data/T_SRR7890936_50pc-ready.bam
07:15:12 -   [##                  ] 14% complete
07:15:12 -   [#####               ] 27% complete
07:15:12 -   [########            ] 41% complete
07:15:12 -   [###########         ] 55% complete
07:15:12 -   [#############       ] 68% complete
07:15:12 -   [################    ] 82% complete
07:15:12 -   [################### ] 95% complete
07:15:12 -   [####################] 100% complete
07:15:12 - Processing 519 homozygous sites in tumor bam /data/data/T_SRR7890936_50pc-ready.bam for contamination
07:15:13 -   [##                  ] 13% complete
07:15:13 -   [#####               ] 26% complete
07:15:13 -   [#######             ] 39% complete
07:15:13 -   [##########          ] 52% complete
07:15:13 -   [#############       ] 65% complete
07:15:13 -   [###############     ] 78% complete
07:15:13 -   [##################  ] 91% complete
07:15:13 -   [####################] 100% complete
07:15:13 - Median normal depth is 4 reads: filtering reads outside of 2 and 6
07:15:13 - Median tumor depth at potential contamination sites is 0 reads
07:15:13 - No evidence of contamination.
07:15:13 - Writing 164 BAF records to amber-3.6//T_SRR7890936_50p.amber.baf.vcf.gz
07:15:14 - Writing 315 contamination records to amber-3.6//T_SRR7890936_50p.amber.contamination.vcf.gz
07:15:14 - Writing 1101 germline snp records to amber-3.6//N_SRR789088.amber.snp.vcf.gz
07:15:14 - Applying pcf segmentation
07:15:14 - Executing R script via command: Rscript /tmp/script10892752855820169351.R amber-3.6//T_SRR7890936_50p.amber.baf.tsv amber-3.6//T_SRR7890936_50p.amber.baf.pcf
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```

**Comment by scwatts** [comment]
Could I also suggest adding `-ref_genome_version` to the optional argument table in the AMBER [documentation](https://github.com/hartwigmedical/hmftools/tree/master/amber#optional-arguments)?

**Comment by p-priestley** [comment]
added to the documentation

**Comment by scwatts** [comment]
Ah, looking at the CLI help text I hadn't realised `-ref_genome_version` was only necessary when providing a reference for CRAMs. Thank you nonetheless!
