### ISSUE TITLE
lilac error: "Exception in thread "main" org.apache.commons.cli.UnrecognizedOptionException: Unrecognized option: -somatic_vcf"

### ISSUE THREAD

**Issue by jamesdalg** [hartwigmedical/hmftools#257]
I think this seems pretty simple. Did the name of the command line option for the VCF file change with the new version of lilac?

```
(base) bash-4.2$ mkdir -p /data/CCRBioinfo/dalgleishjl/sv_mapping/PASFCV_lilac/; module load gridss samtools R java/17.0.1 circos; java -jar /data/CCRBioinfo/dalgleishjl/sv_mapping/gridss_purple_linx/hmftools/lilac/lilac.jar -sample PASFCV_T  -ref_genome /data/CCRBioinfo/dalgleishjl/sv_mapping/hg38_ref/hg38.fa -reference_bam /data/CCRBioinfo/dalgleishjl/sv_mapping/gridss_pipeline/bam_hg38/PASFCV_N.bam -tumor_bam /data/CCRBioinfo/dalgleishjl/sv_mapping/gridss_pipeline/bam_hg38/PASFCV_T.bam -somatic_vcf /data/CCRBioinfo/dalgleishjl/sv_mapping/PASFCV_purple/PASFCV_T.purple.somatic.vcf.gz -gene_copy_number /data/CCRBioinfo/dalgleishjl/sv_mapping/PASFCV_purple/PASFCV.purple.cnv.gene.tsv -output_dir  /data/CCRBioinfo/dalgleishjl/sv_mapping/PASFCV_lilac/ -threads 32
[+] Loading gridss  2.12.2  on cn1060
[+] Loading singularity  3.8.5-1  on cn1060
[+] Loading samtools 1.14  ...
[+] Loading gcc  9.2.0  ...
[+] Loading GSL 2.6 for GCC 9.2.0 ...
[-] Unloading gcc  9.2.0  ...
[+] Loading gcc  9.2.0  ...
[+] Loading openmpi 4.0.5  for GCC 9.2.0
[+] Loading ImageMagick  7.0.8  on cn1060
[+] Loading HDF5  1.10.4
[-] Unloading gcc  9.2.0  ...
[+] Loading gcc  9.2.0  ...
[+] Loading NetCDF 4.7.4_gcc9.2.0
[+] Loading pandoc  2.16.2  on cn1060
[+] Loading pcre2 10.21  ...
[+] Loading R 4.1.0
[-] Unloading java 1.8.0_11  ...
[+] Loading java 17.0.1  ...
[+] Loading circos  0.69-9

The following have been reloaded with a version change:
  1) java/1.8.0_11 => java/17.0.1

Exception in thread "main" org.apache.commons.cli.UnrecognizedOptionException: Unrecognized option: -somatic_vcf
        at org.apache.commons.cli.DefaultParser.handleUnknownToken(DefaultParser.java:347)
        at org.apache.commons.cli.DefaultParser.handleConcatenatedOptions(DefaultParser.java:689)
        at org.apache.commons.cli.DefaultParser.handleShortAndLongOption(DefaultParser.java:520)
        at org.apache.commons.cli.DefaultParser.handleToken(DefaultParser.java:243)
        at org.apache.commons.cli.DefaultParser.parse(DefaultParser.java:120)
        at org.apache.commons.cli.DefaultParser.parse(DefaultParser.java:76)
        at org.apache.commons.cli.DefaultParser.parse(DefaultParser.java:60)
        at com.hartwig.hmftools.lilac.LilacApplication.createCommandLine(LilacApplication.java:763)
        at com.hartwig.hmftools.lilac.LilacApplication.main(LilacApplication.java:737)

```

**Comment by charlesshale** [comment]
The table of config options in the read-me is correct, but the example command unhelpfully had the old config name. 

The two input files should be:
- gene_copy_number_file
- somatic_variants_file

Read-me updated.

thanks.

**Comment by jamesdalg** [comment]
Thanks for pointing that out. The error has been cleared now.
