### ISSUE TITLE
lilac: "outputDir" is null, even though it exists in the file system.

### ISSUE THREAD

**Issue by jamesdalg** [hartwigmedical/hmftools#258]
Sorry to post more than one issue, but I ran into another problem I haven't seen before and I can't find anything like this in the issues pages:
The output directory exists, but it believes it to be null for some reason.
```
(base) bash-4.2$ mkdir -p /data/CCRBioinfo/dalgleishjl/sv_mapping/PASFCV_lilac/; module load gridss samtools R java/17.0.1 circos; java -jar /data/CCRBioinfo/dalgleishjl/sv_mapping/gridss_purple_linx/hmftools/lilac/lilac.jar -sample PASFCV_T  -ref_genome /data/CCRBioinfo/dalgleishjl/sv_mapping/hg38_ref/hg38.fa -reference_bam /data/CCRBioinfo/dalgleishjl/sv_mapping/gridss_pipeline/bam_hg38/PASFCV_N.bam -tumor_bam /data/CCRBioinfo/dalgleishjl/sv_mapping/gridss_pipeline/bam_hg38/PASFCV_T.bam -somatic_variants_file /data/CCRBioinfo/dalgleishjl/sv_mapping/PASFCV_purple/PASFCV_T.purple.somatic.vcf.gz -gene_copy_number_file /data/CCRBioinfo/dalgleishjl/sv_mapping/PASFCV_purple/PASFCV.purple.cnv.gene.tsv -output_dir  /data/CCRBioinfo/dalgleishjl/sv_mapping/PASFCV_lilac
[-] Unloading gridss  2.12.2 on cn1060
[+] Loading gridss  2.12.2  on cn1060
[-] Unloading singularity  3.8.5-1  on cn1060
[+] Loading singularity  3.8.5-1  on cn1060
[-] Unloading samtools 1.14  ...
[+] Loading samtools 1.14  ...
[-] Unloading gcc  9.2.0  ...
[-] Unloading GSL 2.6 for GCC 9.2.0 ...
[-] Unloading openmpi 4.0.5  for GCC 9.2.0
[-] Unloading ImageMagick  7.0.8  on cn1060
[-] Unloading HDF5  1.10.4
[-] Unloading NetCDF 4.7.4_gcc9.2.0
[-] Unloading pandoc  2.16.2  on cn1060
[-] Unloading pcre2 10.21  ...
[-] Unloading R 4.1.0
[+] Loading gcc  9.2.0  ...
[+] Loading GSL 2.6 for GCC 9.2.0 ...
[-] Unloading gcc  9.2.0  ...
[+] Loading gcc  9.2.0  ...
[+] Loading openmpi 4.0.5  for GCC 9.2.0
[+] Loading ImageMagick  7.0.8  on cn1060
[+] Loading HDF5  1.10.4
[-] Unloading gcc  9.2.0  ...
[+] Loading gcc  9.2.0  ...
[+] Loading NetCDF 4.7.4_gcc9.2.0
[+] Loading pandoc  2.16.2  on cn1060
[+] Loading pcre2 10.21  ...
[+] Loading R 4.1.0
[-] Unloading java 17.0.1  ...
[+] Loading java 17.0.1  ...
[-] Unloading circos  0.69-9
[+] Loading circos  0.69-9
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "String.endsWith(String)" because "outputDir" is null
        at com.hartwig.hmftools.common.utils.FileWriterUtils.checkAddDirSeparator(FileWriterUtils.java:59)
        at com.hartwig.hmftools.lilac.LilacConfig.<init>(LilacConfig.java:157)
        at com.hartwig.hmftools.lilac.LilacApplication.main(LilacApplication.java:741)
(base) bash-4.2$ ls -l /data/CCRBioinfo/dalgleishjl/sv_mapping/PASFCV_lilac
total 0
```

I have also tried it with a slash at the end of the filename. What else can I try?

```
(base) bash-4.2$ mkdir -p /data/CCRBioinfo/dalgleishjl/sv_mapping/PASFCV_lilac/; module load gridss samtools R java/17.0.1 circos; java -jar /data/CCRBioinfo/dalgleishjl/sv_mapping/gridss_purple_linx/hmftools/lilac/lilac.jar -sample PASFCV_T  -ref_genome /data/CCRBioinfo/dalgleishjl/sv_mapping/hg38_ref/hg38.fa -reference_bam /data/CCRBioinfo/dalgleishjl/sv_mapping/gridss_pipeline/bam_hg38/PASFCV_N.bam -tumor_bam /data/CCRBioinfo/dalgleishjl/sv_mapping/gridss_pipeline/bam_hg38/PASFCV_T.bam -somatic_vcf /data/CCRBioinfo/dalgleishjl/sv_mapping/PASFCV_purple/PASFCV_T.purple.somatic.vcf.gz -gene_copy_number /data/CCRBioinfo/dalgleishjl/sv_mapping/PASFCV_purple/PASFCV.purple.cnv.gene.tsv -output_dir  /data/CCRBioinfo/dalgleishjl/sv_mapping/PASFCV_lilac/ -threads 32
[-] Unloading gridss  2.12.2 on cn1060
[+] Loading gridss  2.12.2  on cn1060
[-] Unloading singularity  3.8.5-1  on cn1060
[+] Loading singularity  3.8.5-1  on cn1060
[-] Unloading samtools 1.14  ...
[+] Loading samtools 1.14  ...
[-] Unloading gcc  9.2.0  ...
[-] Unloading GSL 2.6 for GCC 9.2.0 ...
[-] Unloading openmpi 4.0.5  for GCC 9.2.0
[-] Unloading ImageMagick  7.0.8  on cn1060
[-] Unloading HDF5  1.10.4
[-] Unloading NetCDF 4.7.4_gcc9.2.0
[-] Unloading pandoc  2.16.2  on cn1060
[-] Unloading pcre2 10.21  ...
[-] Unloading R 4.1.0
[+] Loading gcc  9.2.0  ...
[+] Loading GSL 2.6 for GCC 9.2.0 ...
[-] Unloading gcc  9.2.0  ...
[+] Loading gcc  9.2.0  ...
[+] Loading openmpi 4.0.5  for GCC 9.2.0
[+] Loading ImageMagick  7.0.8  on cn1060
[+] Loading HDF5  1.10.4
[-] Unloading gcc  9.2.0  ...
[+] Loading gcc  9.2.0  ...
[+] Loading NetCDF 4.7.4_gcc9.2.0
[+] Loading pandoc  2.16.2  on cn1060
[+] Loading pcre2 10.21  ...
[+] Loading R 4.1.0
[-] Unloading java 17.0.1  ...
[+] Loading java 17.0.1  ...
[-] Unloading circos  0.69-9
[+] Loading circos  0.69-9
Exception in thread "main" org.apache.commons.cli.UnrecognizedOptionException: Unrecognized option: -somatic_vcf
        at org.apache.commons.cli.DefaultParser.handleUnknownToken(DefaultParser.java:347)
        at org.apache.commons.cli.DefaultParser.handleConcatenatedOptions(DefaultParser.java:689)
        at org.apache.commons.cli.DefaultParser.handleShortAndLongOption(DefaultParser.java:520)
        at org.apache.commons.cli.DefaultParser.handleToken(DefaultParser.java:243)
        at org.apache.commons.cli.DefaultParser.parse(DefaultParser.java:120)
        at org.apache.commons.cli.DefaultParser.parse(DefaultParser.java:76)
        at org.apache.commons.cli.DefaultParser.parse(DefaultParser.java:60)
        at com.hartwig.hmftools.lilac.LilacApplication.createCommandLine(LilacApplication.java:763)
        at com.hartwig.hmftools.lilac.LilacApplication.main(LilacApplication.java:737)

```

**Comment by jamesdalg** [comment]
It looks like there is a space before and after, from what I can see.

**Comment by jamesdalg** [comment]
Figured it out by looking through LilacConfig.java.  It's not the output dir it wants, it's the resource dir. Once I added that, it ran.
