### ISSUE TITLE
Teal issue with WGSMetrics

### ISSUE THREAD

**Issue by jamesdalg** [hartwigmedical/hmftools#262]
I'm having an issue running teal (see command and output below). If anyone knows of something to try, let me know. I'll keep working on it.  Thanks again for all your advice.

```
        module load java/17.0.1; java -Xmx30G -cp /data/CCRBioinfo/dalgleishjl/sv_mapping/gridss_purple_linx/hmftools/teal/teal-1.0_beta.jar com.hartwig.hmftools.teal.TealApplication        -reference NAAHDA_N -reference_bam /data/CCRBioinfo/dalgleishjl/sv_mapping/gridss_pipeline/bam_hg38/NAAHDA_N.bam        -tumor NAAHDA_T -tumor_bam /data/CCRBioinfo/dalgleishjl/sv_mapping/gridss_pipeline/bam_hg38/NAAHDA_T.bam        -purple /data/CCRBioinfo/dalgleishjl/sv_mapping/NAAHDA_purple        -cobalt /data/CCRBioinfo/dalgleishjl/sv_mapping/NAAHDA_cobalt        -reference_wgs_metrics /data/CCRBioinfo/dalgleishjl/sv_mapping/gridss_pipeline/bam_hg38/NAAHDA_T.bam        -tumor_wgs_metrics  /data/CCRBioinfo/dalgleishjl/sv_mapping/gridss_pipeline/bam_hg38/NAAHDA_T.bam        -output_dir /data/CCRBioinfo/dalgleishjl/sv_mapping/NAAHDA_teal/        -threads 32

[+] Loading java 17.0.1  ...
Exception in thread "main" java.nio.charset.MalformedInputException: Input length = 1
        at java.base/java.nio.charset.CoderResult.throwException(CoderResult.java:274)
        at java.base/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
        at java.base/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:188)
        at java.base/java.io.InputStreamReader.read(InputStreamReader.java:177)
        at java.base/java.io.BufferedReader.fill(BufferedReader.java:162)
        at java.base/java.io.BufferedReader.readLine(BufferedReader.java:329)
        at java.base/java.io.BufferedReader.readLine(BufferedReader.java:396)
        at java.base/java.nio.file.Files.readAllLines(Files.java:3415)
        at java.base/java.nio.file.Files.readAllLines(Files.java:3453)
        at com.hartwig.hmftools.common.metrics.WGSMetricsLines.fromFile(WGSMetricsLines.java:24)
        at com.hartwig.hmftools.common.metrics.WGSMetricsFile.read(WGSMetricsFile.java:33)
        at com.hartwig.hmftools.teal.TealApplication$PipelineMode.readPipelineFiles(TealApplication.kt:231)
        at com.hartwig.hmftools.teal.TealApplication$PipelineMode.run(TealApplication.kt:190)
        at com.hartwig.hmftools.teal.TealApplication$Companion.main(TealApplication.kt:286)
        at com.hartwig.hmftools.teal.TealApplication.main(TealApplication.kt)

```
It seems to have an issue with the WGS Metrics reading section of the code. I'll look more into it, but here is my picard output from WGSMetrics.

```
## htsjdk.samtools.metrics.StringHeader
# CollectWgsMetrics INPUT=/data/CCRBioinfo/dalgleishjl/sv_mapping/gridss_pipeline/bam_hg38/NAAHDA_N.bam OUTPUT=/data/CCRBioinfo/dalgleishjl/sv_mapping/NAAHDA_wgsmetrics/NAAHDA_N_wgs_metrics.txt USE_FAST_ALGORITHM=true REFERENCE_SEQUENCE=/data/CCRBioinfo/dalgleishjl/sv_mapping/hg38_ref/hg38.fa    MINIMUM_MAPPING_QUALITY=20 MINIMUM_BASE_QUALITY=20 COVERAGE_CAP=250 LOCUS_ACCUMULATION_CAP=100000 STOP_AFTER=-1 INCLUDE_BQ_HISTOGRAM=false COUNT_UNPAIRED=false SAMPLE_SIZE=10000 ALLELE_FRACTION=[0.001, 0.005, 0.01, 0.02, 0.05, 0.1, 0.2, 0.3, 0.5] READ_LENGTH=150 VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=2 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json USE_JDK_DEFLATER=false USE_JDK_INFLATER=false
## htsjdk.samtools.metrics.StringHeader
# Started on: Thu Feb 24 17:25:33 EST 2022

## METRICS CLASS	picard.analysis.WgsMetrics
GENOME_TERRITORY	MEAN_COVERAGE	SD_COVERAGE	MEDIAN_COVERAGE	MAD_COVERAGE	PCT_EXC_ADAPTER	PCT_EXC_MAPQ	PCT_EXC_DUPE	PCT_EXC_UNPAIRED	PCT_EXC_BASEQ	PCT_EXC_OVERLAP	PCT_EXC_CAPPED	PCT_EXC_TOTAL	PCT_1X	PCT_5X	PCT_10X	PCT_15X	PCT_20X	PCT_25X	PCT_30X	PCT_40X	PCT_50X	PCT_60X	PCT_70X	PCT_80X	PCT_90X	PCT_100X	FOLD_80_BASE_PENALTY	FOLD_90_BASE_PENALTY	FOLD_95_BASE_PENALTY	HET_SNP_SENSITIVITY	HET_SNP_Q
2942530525	75.641321	20.612179	79	7	0.000123	0.070059	0.026802	0.000295	0.020138	0.128028	0.004259	0.249705	0.966005	0.961524	0.958819	0.956736	0.954876	0.953071	0.951177	0.946427	0.939581	0.916461	0.790654	0.466882	0.150461	0.026979	1.096251	1.220021	2.363791	0.964053	14

## HISTOGRAM	java.lang.Integer
coverage	high_quality_coverage_count
0	100031457
1	5417694
2	3201295
3	2472198
4	2095238
5	1853353
6	1685222
7	1565265
8	1469965
9	1383489
10	1314045
11	1262311
12	1219688
13	1183297
14	1151761
15	1130617
16	1112156
17	1090976
18	1076379
19	1062968
20	1059553
21	1060403
22	1057372
23	1063785
24	1068785
25	1077847
26	1092005
27	1113171
28	1130350
29	1161874
30	1195610
31	1234950
32	1276188
33	1323808
34	1371465
35	1416907
36	1467543
37	1516503
38	1564474
39	1608370
40	1655690
41	1703189
42	1755220
43	1810237
44	1878103
45	1968250
46	2079226
47	2225651
48	2412639
49	2657081
50	2969441
51	3368036
52	3874117
53	4524722
54	5347126
55	6385383
56	7665341
57	9245045
58	11172586
59	13477326
60	16236353
61	19474699
62	23223245
63	27521246
64	32361230
65	37754210
66	43617514
67	49938991
68	56596774
69	63468044
70	70456990
71	77363324
72	84027641
73	90277492
74	95960209
75	100912721
76	104939633
77	108005221
78	109981059
79	110783871
80	110428113
81	108946719
82	106362249
83	102809371
84	98321749
85	93150925
86	87345825
87	81122973
88	74620273
89	67970565
90	61352746
91	54871350
92	48601224
93	42677323
94	37153057
95	32050713
96	27428423
97	23277556
98	19581541
99	16354885
100	13552583
101	11151852
102	9109693
103	7392499
104	5961148
105	4778990
106	3814712
107	3027852
108	2397080
109	1895044
110	1496810
111	1184653
112	937826
113	747904
114	598797
115	485884
116	399009
117	332256
118	280114
119	241842
120	212085
121	190036
122	172611
123	159238
124	148031
125	139410
126	131330
127	125743
128	120230
129	115207
130	110797
131	106289
132	102391
133	99332
134	96097
135	93813
136	91260
137	88869
138	87386
139	85551
140	84756
141	83887
142	82299
143	81072
144	81034
145	80704
146	80228
147	80155
148	80718
149	80289
150	80263
151	80543
152	79877
153	80238
154	80624
155	79803
156	79682
157	78336
158	77449
159	76604
160	76605
161	74718
162	74074
163	72977
164	71552
165	70435
166	68647
167	67061
168	65711
169	63604
170	61608
171	59575
172	57834
173	55670
174	54261
175	52122
176	50603
177	48995
178	46672
179	45334
180	43949
181	43081
182	41362
183	40355
184	39641
185	38492
186	37616
187	36984
188	35824
189	35132
190	34499
191	33995
192	33321
193	33044
194	32745
195	32267
196	31672
197	31190
198	30807
199	30443
200	29829
201	29459
202	29136
203	29005
204	28712
205	28916
206	28491
207	28183
208	27777
209	27668
210	27641
211	27478
212	27609
213	27405
214	27296
215	27534
216	27482
217	27373
218	27618
219	27308
220	27478
221	27467
222	27354
223	27663
224	27307
225	27137
226	27075
227	27260
228	26942
229	26724
230	27134
231	26846
232	26595
233	26659
234	26279
235	26490
236	26269
237	25788
238	25664
239	25445
240	25125
241	24775
242	24802
243	24241
244	24009
245	23546
246	23260
247	22832
248	22626
249	21924
250	2227804


```

**Comment by hongwingl** [comment]
Your WGSMetrics files look fine to me.
The following arguments:
```
-reference_wgs_metrics /data/CCRBioinfo/dalgleishjl/sv_mapping/gridss_pipeline/bam_hg38/NAAHDA_T.bam
-tumor_wgs_metrics  /data/CCRBioinfo/dalgleishjl/sv_mapping/gridss_pipeline/bam_hg38/NAAHDA_T.bam 
```
The input to those arguments should be the WGSMetrics files, not the bam files.

**Comment by jamesdalg** [comment]
Thanks! It's wonderful when the problem is that simple. I thought I had double checked that, but that slipped through. Sorry to bother when it's this simple. Seems to work quite well, from what I find and the blacklistedTelomereRegions.38.bed in the jar is easy to modify.

**Comment by hongwingl** [comment]
That's all good. Thanks for using TEAL. Don't hesitate to ask if you got any more questions 🙂
