### ISSUE TITLE
Linx index error

### ISSUE THREAD

**Issue by jaesvi** [hartwigmedical/hmftools#268]
Hi,
I have encountered a LINX IndexOutBounds exception that I do not know how to debug;
```
 Exception in thread "main" java.lang.IndexOutOfBoundsException: Index 52 out of bounds for length 52
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:372)
	at java.base/java.util.ArrayList.get(ArrayList.java:459)
	at com.hartwig.hmftools.linx.analysis.DoubleMinuteData.setPairCharacteristics(DoubleMinuteData.java:252)
	at com.hartwig.hmftools.linx.analysis.DoubleMinuteData.setChainCharacteristics(DoubleMinuteData.java:202)
	at com.hartwig.hmftools.linx.analysis.DoubleMinuteData.annotate(DoubleMinuteData.java:145)
	at com.hartwig.hmftools.linx.analysis.DoubleMinuteFinder.analyseCluster(DoubleMinuteFinder.java:234)
	at com.hartwig.hmftools.linx.analysis.DoubleMinuteFinder.analyseCluster(DoubleMinuteFinder.java:112)
	at com.hartwig.hmftools.linx.analysis.ClusterAnalyser.findLimitedChains(ClusterAnalyser.java:310)
	at com.hartwig.hmftools.linx.analysis.ClusterAnalyser.clusterAndAnalyse(ClusterAnalyser.java:181)
	at com.hartwig.hmftools.linx.analysis.SampleAnalyser.analyse(SampleAnalyser.java:341)
	at com.hartwig.hmftools.linx.LinxApplication.main(LinxApplication.java:246)
```
Do you have any hint as of where this might come from? Purple did run succesfully for this sample. I can provide reference files if you tell me which ones would be useful.
Thanks.

**Comment by charlesshale** [comment]
I've not seen that before and it looks like the breakend index of one of the SVs is is invalid relative to the other SVs in its cluster. I can run it through debug if you can provide the command you ran, the SV VCF and the purple input files. 

Email me directly c.shale@hartwigmedicalfoundation.nl

thanks.

**Comment by charlesshale** [comment]
A duplicate breakend was being considered as a double-minute, but had insufficient info to be annotated as such.

Fixed in v.19 beta:
https://github.com/hartwigmedical/hmftools/releases/tag/linx-v1.19_beta

**Comment by jaesvi** [comment]
Worked perfectly, thanks.
