### ISSUE TITLE
write_pass_only and read_pass_only error in pave

### ISSUE THREAD

**Issue by jamesdalg** [hartwigmedical/hmftools#271]
I'm having trouble with the read_pass_only and write_pass_only options in pave. Is there something I'm doing wrong or is this a bug?

I've tried both version 1.0 and version 1.1 of pave, but the result is the same.

```
(base) [dalgleishjl@cn0630 snakemake-gridss]$ module load java/17.0.2; java -jar /data/CCRBioinfo/dalgleishjl/sv_mapping/gridss_purple_linx/hmftools/pave/pave_v1.0.jar           -sample PAMHYN           -vcf_file /data/CCRBioinfo/dalgleishjl/sv_mapping/sage/PAMHYN_sage/PAMHYN.sage.pon_filtered.vcf.gz           -ensembl_data_dir  /data/CCRBioinfo/dalgleishjl/sv_mapping/gridss/external_resources/HMFTools-Resources/Ensembl-Data-Cache/38/           -ref_genome /data/CCRBioinfo/dalgleishjl/sv_mapping/hg38_ref/hg38.fa            -ref_genome_version 38            -output_dir /data/CCRBioinfo/dalgleishjl/sv_mapping/pave/PAMHYN_pave/           -output_vcf_file /data/CCRBioinfo/dalgleishjl/sv_mapping/pave/PAMHYN_pave/PAMHYN.pave.vcf.gz  -write_pass_only -read_pass_only
[-] Unloading java 17.0.2  ...
[+] Loading java 17.0.2  ...
Exception in thread "main" org.apache.commons.cli.UnrecognizedOptionException: Unrecognized option: -write_pass_only
        at org.apache.commons.cli.DefaultParser.handleUnknownToken(DefaultParser.java:347)
        at org.apache.commons.cli.DefaultParser.handleConcatenatedOptions(DefaultParser.java:689)
        at org.apache.commons.cli.DefaultParser.handleShortAndLongOption(DefaultParser.java:520)
        at org.apache.commons.cli.DefaultParser.handleToken(DefaultParser.java:243)
        at org.apache.commons.cli.DefaultParser.parse(DefaultParser.java:120)
        at org.apache.commons.cli.DefaultParser.parse(DefaultParser.java:76)
        at org.apache.commons.cli.DefaultParser.parse(DefaultParser.java:60)
        at com.hartwig.hmftools.pave.PaveApplication.createCommandLine(PaveApplication.java:544)
        at com.hartwig.hmftools.pave.PaveApplication.main(PaveApplication.java:532)
(base) [dalgleishjl@cn0630 snakemake-gridss]$ module load java/17.0.2; java -jar /data/CCRBioinfo/dalgleishjl/sv_mapping/gridss_purple_linx/hmftools/pave/pave_v1.1.jar           -sample PAMHYN           -vcf_file /data/CCRBioinfo/dalgleishjl/sv_mapping/sage/PAMHYN_sage/PAMHYN.sage.pon_filtered.vcf.gz           -ensembl_data_dir  /data/CCRBioinfo/dalgleishjl/sv_mapping/gridss/external_resources/HMFTools-Resources/Ensembl-Data-Cache/38/           -ref_genome /data/CCRBioinfo/dalgleishjl/sv_mapping/hg38_ref/hg38.fa            -ref_genome_version 38            -output_dir /data/CCRBioinfo/dalgleishjl/sv_mapping/pave/PAMHYN_pave/           -output_vcf_file /data/CCRBioinfo/dalgleishjl/sv_mapping/pave/PAMHYN_pave/PAMHYN.pave.vcf.gz  -write_pass_only -read_pass_only
[-] Unloading java 17.0.2  ...
[+] Loading java 17.0.2  ...
Exception in thread "main" org.apache.commons.cli.UnrecognizedOptionException: Unrecognized option: -write_pass_only
        at org.apache.commons.cli.DefaultParser.handleUnknownToken(DefaultParser.java:347)
        at org.apache.commons.cli.DefaultParser.handleConcatenatedOptions(DefaultParser.java:689)
        at org.apache.commons.cli.DefaultParser.handleShortAndLongOption(DefaultParser.java:520)
        at org.apache.commons.cli.DefaultParser.handleToken(DefaultParser.java:243)
        at org.apache.commons.cli.DefaultParser.parse(DefaultParser.java:120)
        at org.apache.commons.cli.DefaultParser.parse(DefaultParser.java:76)
        at org.apache.commons.cli.DefaultParser.parse(DefaultParser.java:60)
        at com.hartwig.hmftools.pave.PaveApplication.createCommandLine(PaveApplication.java:544)
        at com.hartwig.hmftools.pave.PaveApplication.main(PaveApplication.java:532)

```

**Comment by charlesshale** [comment]
These new config options are available with v1.2 for which I've just made a beta release:

https://github.com/hartwigmedical/hmftools/releases/tag/pave-v1.2_beta

Official release due in about a week.
