### ISSUE TITLE
Missing Contig Causes Unhandled Exception in Amber

### ISSUE THREAD

**Issue by DarioS** [hartwigmedical/hmftools#28]
For my data set, I have mapped the reads to a particular version of GRCh38 made available by NCBI and [recommended by Heng Li](http://lh3.github.io/2017/11/13/which-human-reference-genome-to-use), the creator of BWA. I am using the file named GermlineHetPon.hg38.bed.gz downloaded from the resources website which contains some contigs which the reference genome does not and this causes an error

```
14:18:09 - Loading bed file GermlineHetPon.hg38.bed.gz
14:18:11 - Processing 1391244 potential sites in reference bam LS33.bam
14:52:27 - Complete
Exception in thread "main" java.lang.IllegalArgumentException: No enum constant com.hartwig.hmftools.common.chromosome.HumanChromosome._HG142_HG150_NOVEL_TEST
        at java.lang.Enum.valueOf(Enum.java:238)
        at com.hartwig.hmftools.common.chromosome.HumanChromosome.valueOf(HumanChromosome.java:9)
        at com.hartwig.hmftools.common.chromosome.HumanChromosome.fromString(HumanChromosome.java:66)
        at com.hartwig.hmftools.amber.AmberApplication.lambda$normalDepth$0(AmberApplication.java:149)
        at java.util.ArrayList.forEach(ArrayList.java:1255)
        at com.hartwig.hmftools.amber.AmberApplication.normalDepth(AmberApplication.java:149)
        at com.hartwig.hmftools.amber.AmberApplication.run(AmberApplication.java:102)
        at com.hartwig.hmftools.amber.AmberApplication.main(AmberApplication.java:61)
```

Is there advice for modifying the BED file to avoid the error? Perhaps a similar tweak would be needed for GC_profile.hg38.1000bp.cnp.gz when running COBALT afterwards.

**Comment by jonbaber** [comment]
I have uploaded a new version of the file without the offending contigs. 

I will also add a fix to AMBER to handle it more gracefully.

**Comment by jonbaber** [comment]
I have added a fix to AMBER which will be included in the next release.
