### ISSUE TITLE
GRIPSS truncated file causing error in GRIPSS. Exception in thread "main" htsjdk.tribble.TribbleException$MalformedFeatureFile: Unable to parse header with error: Premature end of file: 

### ISSUE THREAD

**Issue by jamesdalg** [hartwigmedical/hmftools#285]
`         module load gridss samtools R java/17.0.2 bcftools; java -jar  /data/CCRBioinfo/dalgleishjl/sv_mapping/gridss/gripss/gripss_v2.1.jar  -sample PALHRL_T -reference PALHRL_N  -ref_genome /data/CCRBioinfo/dalgleishjl/sv_mapping/hg38_ref/hg38.fa  -pon_sv_file /data/CCRBioinfo/dalgleishjl/sv_mapping/gridss/ponhg38/gridss_pon_breakpoint.38.bedpe -pon_sgl_file /data/CCRBioinfo/dalgleishjl/sv_mapping/gridss/ponhg38/gridss_pon_single_breakend.38.bed -known_hotspot_file /data/CCRBioinfo/dalgleishjl/sv_mapping/gridss/external_resources/HMFTools-Resources/Known-Fusions/38/known_fusions.38.bedpe   -vcf /data/CCRBioinfo/dalgleishjl/sv_mapping/gridss_purple_linx/PALHRL_T_N_gridss_paired/gridss_PALHRL_T_N_paired_output_hg38.vcf.gz  -output_dir /data/CCRBioinfo/dalgleishjl/sv_mapping/gridss_purple_linx/PALHRL_T_N_gridss_paired/ > gripss_log.txt
[-] Unloading gridss  2.13.2 on cn0882
[+] Loading gridss  2.13.2  on cn0882
[-] Unloading singularity  3.8.5-1  on cn0882
[+] Loading singularity  3.8.5-1  on cn0882
[-] Unloading samtools 1.15  ...
[+] Loading samtools 1.15  ...
[-] Unloading gcc  9.2.0  ...
[-] Unloading GSL 2.6 for GCC 9.2.0 ...
[-] Unloading openmpi 4.0.5  for GCC 9.2.0
[-] Unloading ImageMagick  7.0.8  on cn0882
[-] Unloading HDF5  1.10.4
[-] Unloading NetCDF 4.7.4_gcc9.2.0
[-] Unloading pandoc  2.17.1.1  on cn0882
[-] Unloading pcre2 10.21  ...
[-] Unloading R 4.1.3
[+] Loading gcc  9.2.0  ...
[+] Loading GSL 2.6 for GCC 9.2.0 ...
[-] Unloading gcc  9.2.0  ...
[+] Loading gcc  9.2.0  ...
[+] Loading openmpi 4.0.5  for GCC 9.2.0
[+] Loading ImageMagick  7.0.8  on cn0882
[+] Loading HDF5  1.10.4
[-] Unloading gcc  9.2.0  ...
[+] Loading gcc  9.2.0  ...
[+] Loading NetCDF 4.7.4_gcc9.2.0
[+] Loading pandoc  2.17.1.1  on cn0882
[+] Loading pcre2 10.21  ...
[+] Loading R 4.1.3
[-] Unloading java 17.0.2  ...
[+] Loading java 17.0.2  ...
[-] Unloading samtools 1.13  ...
[+] Loading samtools 1.13  ...
Exception in thread "main" htsjdk.tribble.TribbleException$MalformedFeatureFile: Unable to parse header with error: Premature end of file: /data/CCRBioinfo/dalgleishjl/sv_mapping/gridss_purple_linx/PALHRL_T_N_gridss_paired/gridss_PALHRL_T_N_paired_output_hg38.vcf.gz, for input source: /data/CCRBioinfo/dalgleishjl/sv_mapping/gridss_purple_linx/PALHRL_T_N_gridss_paired/gridss_PALHRL_T_N_paired_output_hg38.vcf.gz
        at htsjdk.tribble.TabixFeatureReader.readHeader(TabixFeatureReader.java:97)
        at htsjdk.tribble.TabixFeatureReader.<init>(TabixFeatureReader.java:82)
        at htsjdk.tribble.AbstractFeatureReader.getFeatureReader(AbstractFeatureReader.java:117)
        at htsjdk.tribble.AbstractFeatureReader.getFeatureReader(AbstractFeatureReader.java:81)
        at com.hartwig.hmftools.gripss.GripssApplication.processVcf(GripssApplication.java:113)
        at com.hartwig.hmftools.gripss.GripssApplication.run(GripssApplication.java:108)
        at com.hartwig.hmftools.gripss.GripssApplication.main(GripssApplication.java:336)
Caused by: htsjdk.samtools.FileTruncatedException: Premature end of file:
[gripss_log.txt](https://github.com/hartwigmedical/hmftools/files/8605946/gripss_log.txt)
 /data/CCRBioinfo/dalgleishjl/sv_mapping/gridss_purple_linx/PALHRL_T_N_gridss_paired/gridss_PALHRL_T_N_paired_output_hg38.vcf.gz
        at htsjdk.samtools.util.BlockCompressedInputStream.processNextBlock(BlockCompressedInputStream.java:530)
        at htsjdk.samtools.util.BlockCompressedInputStream.nextBlock(BlockCompressedInputStream.java:468)
        at htsjdk.samtools.util.BlockCompressedInputStream.readBlock(BlockCompressedInputStream.java:458)
        at htsjdk.samtools.util.BlockCompressedInputStream.available(BlockCompressedInputStream.java:196)
        at htsjdk.samtools.util.BlockCompressedInputStream.read(BlockCompressedInputStream.java:331)
        at htsjdk.samtools.util.BlockCompressedInputStream.read(BlockCompressedInputStream.java:257)
        at htsjdk.tribble.readers.PositionalBufferedStream.fill(PositionalBufferedStream.java:132)
        at htsjdk.tribble.readers.PositionalBufferedStream.read(PositionalBufferedStream.java:84)
        at java.base/sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:270)
        at java.base/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:313)
        at java.base/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:188)
        at java.base/java.io.InputStreamReader.read(InputStreamReader.java:177)
        at htsjdk.tribble.readers.LongLineBufferedReader.fill(LongLineBufferedReader.java:140)
        at htsjdk.tribble.readers.LongLineBufferedReader.readLine(LongLineBufferedReader.java:300)
        at htsjdk.tribble.readers.LongLineBufferedReader.readLine(LongLineBufferedReader.java:356)
        at htsjdk.tribble.readers.SynchronousLineReader.readLine(SynchronousLineReader.java:51)
        at htsjdk.tribble.readers.LineIteratorImpl.advance(LineIteratorImpl.java:24)
        at htsjdk.tribble.readers.LineIteratorImpl.advance(LineIteratorImpl.java:11)
        at htsjdk.samtools.util.AbstractIterator.hasNext(AbstractIterator.java:44)
        at htsjdk.variant.vcf.VCFCodec.readActualHeader(VCFCodec.java:89)
        at htsjdk.tribble.AsciiFeatureCodec.readHeader(AsciiFeatureCodec.java:79)
        at htsjdk.tribble.AsciiFeatureCode
[gridss.full.20220502_151012.cn2414.67676.log](https://github.com/hartwigmedical/hmftools/files/8605970/gridss.full.20220502_151012.cn2414.67676.log)
[gridss.timing.20220502_151012.cn2414.67676.log](https://github.com/hartwigmedical/hmftools/files/8605971/gridss.timing.20220502_151012.cn2414.67676.log)
c.readHeader(AsciiFeatureCodec.java:37)
        at htsjdk.tribble.TabixFeatureReader.readHeader(TabixFeatureReader.java:95)
`
I've had this happen several times on several samples recently. Maybe it's an easy/small thing, but I'm not understanding why GRIDSS is producing truncated files. I've included the GRIDSS log, but it seems like everything ran fine and yet the VCF is still truncated. Not sure why this is or why it keeps happening.

**Comment by jamesdalg** [comment]
[gridss.full.20220502_151012.cn2414.67676.log](https://github.com/hartwigmedical/hmftools/files/8605977/gridss.full.20220502_151012.cn2414.67676.log)
[gridss.timing.20220502_151012.cn2414.67676.log](https://github.com/hartwigmedical/hmftools/files/8605978/gridss.timing.20220502_151012.cn2414.67676.log)

**Comment by p-priestley** [comment]
Hi James - I am not sure to what extent the VCF is truncated but this appears to be a GRIDSS issue and not something we can fix in GRIPSS so best to log the error here: https://github.com/PapenfussLab/gridss/issues

I am not sure how actively these issues are being maintained though but you may get some advice there.

**Comment by jamesdalg** [comment]
Sounds great. Thanks!
