### ISSUE TITLE
How to pull out all the option for GRIPSS?

### ISSUE THREAD

**Issue by zhujack** [hartwigmedical/hmftools#286]
Hi,

I try to pull out all the options for GRIPSS from the command line? I always get the following error:

       `$ java -jar /data//hmftools/gripss_2.1.jar -h

        Exception in thread "main" org.apache.commons.cli.UnrecognizedOptionException: Unrecognized option: -h
	at org.apache.commons.cli.DefaultParser.handleUnknownToken(DefaultParser.java:347)
	at org.apache.commons.cli.DefaultParser.handleShortAndLongOption(DefaultParser.java:484)
	at org.apache.commons.cli.DefaultParser.handleToken(DefaultParser.java:243)
	at org.apache.commons.cli.DefaultParser.parse(DefaultParser.java:120)
	at org.apache.commons.cli.DefaultParser.parse(DefaultParser.java:76)
	at org.apache.commons.cli.DefaultParser.parse(DefaultParser.java:60)
	at com.hartwig.hmftools.gripss.GripssApplication.createCommandLine(GripssApplication.java:345)
	at com.hartwig.hmftools.gripss.GripssApplication.main(GripssApplication.java:331)`

Also it looks like minNormalCoverage option does not exist for GRIPSS:
        
        `java -jar /data/source/hmftools/gripss_2.1.jar -minNormalCoverage 5 ...

         Exception in thread "main" org.apache.commons.cli.UnrecognizedOptionException: 
         Unrecognized option: -minNormalCoverage`

Any suggestions will be greatly appreciated.

Jack

**Comment by charlesshale** [comment]
I will add '-h' support for the next version.

I have added the missing config options to the READ-ME. MinNormalCoverage can be set with 'min_normal_coverage'.
