### ISSUE TITLE
Teal: java.lang.NumberFormatException: For input string

### ISSUE THREAD

**Issue by YingYa** [hartwigmedical/hmftools#287]
The teal could not input double data that generated by cobalt (version=1.13) when running with Pipeline mode. 
Exception in thread "main" java.lang.NumberFormatException: For input string: "335.72"
        at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.base/java.lang.Integer.parseInt(Integer.java:652)
        at java.base/java.lang.Integer.parseInt(Integer.java:770)
        at com.hartwig.hmftools.common.genome.gc.GCMedianReadCountFile.fromLines(GCMedianReadCountFile.java:42)
        at com.hartwig.hmftools.common.genome.gc.GCMedianReadCountFile.read(GCMedianReadCountFile.java:29)
        at com.hartwig.hmftools.teal.TealApplication$PipelineMode.readPipelineFiles(TealApplication.kt:212)
        at com.hartwig.hmftools.teal.TealApplication$PipelineMode.run(TealApplication.kt:190)
        at com.hartwig.hmftools.teal.TealApplication$Companion.main(TealApplication.kt:286)
        at com.hartwig.hmftools.teal.TealApplication.main(TealApplication.kt)

**Comment by hongwingl** [comment]
Thanks for reporting this. I will make a fix for it.
