### ISSUE TITLE
Unable to parse flagstat file correctly

### ISSUE THREAD

**Issue by YingYa** [hartwigmedical/hmftools#288]
Health-Checker could not process raw output of samtools (1.15) flagstat:

14:06:24 - [INFO ] - Running Health-Checker v3.4
14:06:24 - [INFO ] - Running in somatic mode
Exception in thread "main" java.io.IOException: Unable to parse flagstat file correctly
        at com.hartwig.hmftools.common.flagstat.FlagstatFile.read(FlagstatFile.java:41)
        at com.hartwig.hmftools.healthchecker.runners.TumorFlagstatChecker.<init>(TumorFlagstatChecker.java:16)
        at com.hartwig.hmftools.healthchecker.HealthChecksApplication.run(HealthChecksApplication.java:138)
        at com.hartwig.hmftools.healthchecker.HealthChecksApplication.main(HealthChecksApplication.java:95)

While the filtered (grep -vE "primary mapped|read1|read2|primary|with mate mapped to a different chr") output of samtools (1.15) flagstat chould be run successfully.

**Comment by p-priestley** [comment]
This tool is for internal use only, so we don't support, sorry.
