### ISSUE TITLE
lilac:  java.lang.StringIndexOutOfBoundsException: String index out of range

### ISSUE THREAD

**Issue by YingYa** [hartwigmedical/hmftools#289]
Hi,

4 of my lilac runnnings failed with 'java.lang.StringIndexOutOfBoundsException: String index out of range':

Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: 4
        at java.base/java.lang.StringLatin1.charAt(StringLatin1.java:47)
        at java.base/java.lang.String.charAt(String.java:693)
        at com.hartwig.hmftools.lilac.qc.Haplotype.sequence(Haplotype.java:97)
        at com.hartwig.hmftools.lilac.qc.HaplotypeQC.findSupportingFragmentCounts(HaplotypeQC.java:190)
        at com.hartwig.hmftools.lilac.qc.HaplotypeQC.create(HaplotypeQC.java:99)
        at com.hartwig.hmftools.lilac.LilacApplication.run(LilacApplication.java:498)
        at com.hartwig.hmftools.lilac.LilacApplication.main(LilacApplication.java:745)

Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: 4
        at java.base/java.lang.StringLatin1.charAt(StringLatin1.java:47)
        at java.base/java.lang.String.charAt(String.java:693)
        at com.hartwig.hmftools.lilac.qc.Haplotype.sequence(Haplotype.java:97)
        at com.hartwig.hmftools.lilac.qc.HaplotypeQC.findSupportingFragmentCounts(HaplotypeQC.java:190)
        at com.hartwig.hmftools.lilac.qc.HaplotypeQC.create(HaplotypeQC.java:99)
        at com.hartwig.hmftools.lilac.LilacApplication.run(LilacApplication.java:498)
        at com.hartwig.hmftools.lilac.LilacApplication.main(LilacApplication.java:745)

Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: 16
        at java.base/java.lang.StringLatin1.charAt(StringLatin1.java:47)
        at java.base/java.lang.String.charAt(String.java:693)
        at com.hartwig.hmftools.lilac.qc.Haplotype.sequence(Haplotype.java:97)
        at com.hartwig.hmftools.lilac.qc.HaplotypeQC.findSupportingFragmentCounts(HaplotypeQC.java:190)
        at com.hartwig.hmftools.lilac.qc.HaplotypeQC.create(HaplotypeQC.java:99)
        at com.hartwig.hmftools.lilac.LilacApplication.run(LilacApplication.java:498)
        at com.hartwig.hmftools.lilac.LilacApplication.main(LilacApplication.java:745)

Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: 5
        at java.base/java.lang.StringLatin1.charAt(StringLatin1.java:47)
        at java.base/java.lang.String.charAt(String.java:693)
        at com.hartwig.hmftools.lilac.qc.Haplotype.sequence(Haplotype.java:97)
        at com.hartwig.hmftools.lilac.qc.HaplotypeQC.findSupportingFragmentCounts(HaplotypeQC.java:190)
        at com.hartwig.hmftools.lilac.qc.HaplotypeQC.create(HaplotypeQC.java:99)
        at com.hartwig.hmftools.lilac.LilacApplication.run(LilacApplication.java:498)
        at com.hartwig.hmftools.lilac.LilacApplication.main(LilacApplication.java:745)

**Comment by charlesshale** [comment]
I can't see what conditions are triggering this exception.

Are you able to provide a BAM and then config you're using to run Lilac? if so, can you email me at c.shale@hartwigmedicalfoundation.nl

Otherwise I could add some extra logging to show the haplotype that is being checked at this point in the code.

thanks.

**Comment by YingYa** [comment]
Two bam files are about 250 GB, a little big to share. Maybe more extra logging would be more easy way to check the issue?

**Comment by p-priestley** [comment]
Only the HLA region is necessary.   You can slice your bams using these regions (assuming hg38 no alt):

chr6	29940260	29946884
chr6	31352872	31358188
chr6	31267749	31273130

Normally this should be  a < 5mb file

**Comment by charlesshale** [comment]
I've made a beta release with extra logging - let me know what that shows, thanks

https://github.com/hartwigmedical/hmftools/releases/tag/lilac-v1.3_rc1

**Comment by YingYa** [comment]
the extra logging with [lilac-v1.3_rc1](https://github.com/hartwigmedical/hmftools/releases/tag/lilac-v1.3_rc1)

09:57:20 - [INFO ] -   found 1 HLA somatic variants
09:57:20 - [INFO ] - calculating somatic variant allele coverage
09:57:20 - [INFO ] -   gene(HLA-B) pos(chr6:31355585) variant(TG>T NONSENSE_OR_FRAMESHIFT) -> [B*07:02[11,11,0,0], B*08:01[11,11,0,0]]}
09:57:21 - [ERROR] - invalid haplotype(loci(1 - 14) frags(supporting=0 phased=3) haplotype=AVMAPTLLLLLA) created from evidence(ATLA) and amino-acid indices: 1;7;8;14
09:57:21 - [ERROR] - invalid haplotype(loci(1 - 14) frags(supporting=0 phased=4) haplotype=LVMAPTVLLLLG) created from evidence(LTVG) and amino-acid indices: 1;7;8;14
09:57:21 - [ERROR] - invalid haplotype(loci(96 - 100) frags(supporting=0 phased=3) haplotype=ADVG) created from evidence(AVG) and amino-acid indices: 96;99;100
09:57:21 - [ERROR] - invalid haplotype(loci(103 - 113) frags(supporting=0 phased=6) haplotype=TLGYYNQSED) created from evidence(TD) and amino-acid indices: 103;113
09:57:21 - [ERROR] - invalid haplotype(loci(1 - 14) frags(supporting=0 phased=3) haplotype=AVMAPTLLLLLA) created from evidence(ATLA) and amino-acid indices: 1;7;8;14
09:57:21 - [ERROR] - invalid haplotype(loci(1 - 14) frags(supporting=0 phased=4) haplotype=LVMAPTVLLLLG) created from evidence(LTVG) and amino-acid indices: 1;7;8;14
09:57:21 - [ERROR] - invalid haplotype(loci(96 - 100) frags(supporting=0 phased=3) haplotype=ADVG) created from evidence(AVG) and amino-acid indices: 96;99;100
09:57:21 - [ERROR] - invalid haplotype(loci(103 - 113) frags(supporting=0 phased=6) haplotype=TLGYYNQSED) created from evidence(TD) and amino-acid indices: 103;113
09:57:21 - [ERROR] - invalid haplotype(loci(1 - 14) frags(supporting=0 phased=3) haplotype=AVMAPTLLLLLA) created from evidence(ATLA) and amino-acid indices: 1;7;8;14
09:57:21 - [ERROR] - invalid haplotype(loci(1 - 14) frags(supporting=0 phased=4) haplotype=LVMAPTVLLLLG) created from evidence(LTVG) and amino-acid indices: 1;7;8;14
09:57:21 - [ERROR] - invalid haplotype(loci(96 - 100) frags(supporting=0 phased=3) haplotype=ADVG) created from evidence(AVG) and amino-acid indices: 96;99;100
09:57:21 - [ERROR] - invalid haplotype(loci(103 - 113) frags(supporting=0 phased=6) haplotype=TLGYYNQSED) created from evidence(TD) and amino-acid indices: 103;113
09:57:21 - [ERROR] - haplotype(loci(96 - 100) frags(supporting=0 phased=3) haplotype=ADVG) invalid sequence request at locus(100)
09:57:21 - [INFO ] -   UNMATCHED_HAPLTOYPE loci(14 - 15) frags(supporting=3 phased=4) haplotype=AG
09:57:21 - [INFO ] -   UNMATCHED_HAPLTOYPE loci(92 - 96) frags(supporting=3 phased=3) haplotype=AQSQA
09:57:21 - [INFO ] -   UNMATCHED_HAPLTOYPE loci(100 - 103) frags(supporting=5 phased=6) haplotype=SLRT
09:57:21 - [INFO ] -   UNMATCHED_HAPLTOYPE loci(276 - 296) frags(supporting=4 phased=4) haplotype=QEQRYTCHMQHEGLHEPLTLS
09:57:21 - [INFO ] -   UNMATCHED_HAPLTOYPE loci(305 - 332) frags(supporting=6 phased=5) haplotype=IPIVGIIAGLVLLGAVTTGAVVAAVMWR

**Comment by charlesshale** [comment]
The missing amino acids are due to the sequences have less than the required min evidence at that locus. I've removed that requirement, so it will just use the amino acid with the most support in the unmatched haplotype.

Use the latest JAR here:
https://github.com/hartwigmedical/hmftools/releases/tag/lilac-v1.3_rc1
