### ISSUE TITLE
variant-annotator: ensembl_db option is hardcoded

### ISSUE THREAD

**Issue by mvweae** [hartwigmedical/hmftools#3]
variant-annotator-1.0-jar-with-dependencies.jar

when trying to set the option `-ensembl_db` to a version other than 89_37, get the following error:

Example: 
```
java -jar hmftools/variant-annotator/variant-annotator-1.0-jar-with-dependencies.jar 
	-ensembl_db "mysql://localhost:3306/homo_sapiens_core_75_37?user=blah" 

Exception in thread "main" org.jooq.exception.DataAccessException: SQL [select `homo_sapiens_core_89_37`.`coord_system`.`coord_system_id` from `homo_sapiens_core_89_37`.`coord_system` where `homo_sapiens_core_89_37`.`coord_system`.`version` = ? order by `homo_sapiens_core_89_37`.`coord_system`.`rank` asc limit ?]; SELECT command denied to user 'ensuser'@'localhost' for table 'coord_system'
	at org.jooq_3.9.5.MYSQL.debug(Unknown Source)
	at org.jooq.impl.Tools.translate(Tools.java:1994)
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:676)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:363)
	at org.jooq.impl.AbstractResultQuery.fetchLazy(AbstractResultQuery.java:368)
	at org.jooq.impl.AbstractResultQuery.fetchLazy(AbstractResultQuery.java:355)
	at org.jooq.impl.AbstractResultQuery.fetchOne(AbstractResultQuery.java:520)
	at org.jooq.impl.SelectImpl.fetchOne(SelectImpl.java:2871)
	at com.hartwig.hmftools.svannotation.MySQLAnnotator.findCoordSystemId(MySQLAnnotator.java:56)
	at com.hartwig.hmftools.svannotation.MySQLAnnotator.<init>(MySQLAnnotator.java:47)
	at com.hartwig.hmftools.svannotation.MySQLAnnotator.make(MySQLAnnotator.java:40)
	at com.hartwig.hmftools.svannotation.LoadStructuralVariants.main(LoadStructuralVariants.java:89)
Caused by: java.sql.SQLSyntaxErrorException: SELECT command denied to user 'user'@'localhost' for table 'coord_system'
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:536)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:513)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:115)
	at com.mysql.cj.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:1983)
	at com.mysql.cj.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1826)
	at com.mysql.cj.jdbc.PreparedStatement.execute(PreparedStatement.java:1153)
	at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:195)
	at org.jooq.impl.AbstractResultQuery.execute(AbstractResultQuery.java:270)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:349)
	... 8 more
```

**Comment by kduyvesteyn** [comment]
Yes, we have a strict dependency on version 89.37 but leave it configurable where to put this database. I have made it clearer in the readme that this dependency is there and where you can find the version we use (which is publicly available). Hope you can switch to this version. 

Adding support for multiple versions in the annotation is not something we intend to do.
