### ISSUE TITLE
SAGE_3.0_rc2 throws java.lang.NullPointerException

### ISSUE THREAD

**Issue by toddajohnson** [hartwigmedical/hmftools#300]
Just to let you know, since as far a I know, sage_v3.0_rc2.jar may only be compiled for running on HMF's pipeline/infrastructure or not fit for consumption at all, but I ran it with needed CLI changes on some of my bams, and it was throwing exceptions like:

18:09:01.281 [INFO ] base quality recalibration cache generated
18:09:02.011 [INFO ] chromosome(chr1) executing 2490 regions
Exception in thread "Thread-28" java.lang.NullPointerException
	at com.hartwig.hmftools.sage.evidence.ReadContextCounter.processRead(ReadContextCounter.java:340)
	at com.hartwig.hmftools.sage.evidence.ReadContextEvidence.processReadRecord(ReadContextEvidence.java:163)
	at com.hartwig.hmftools.common.samtools.BamSlicer.slice(BamSlicer.java:63)
	at com.hartwig.hmftools.sage.common.SamSlicer.slice(SamSlicer.java:28)
	at com.hartwig.hmftools.sage.evidence.ReadContextEvidence.collectEvidence(ReadContextEvidence.java:87)
	at com.hartwig.hmftools.sage.pipeline.EvidenceStage.findEvidence(EvidenceStage.java:59)
	at com.hartwig.hmftools.sage.pipeline.RegionTask.run(RegionTask.java:112)
	at com.hartwig.hmftools.sage.pipeline.RegionThread.run(RegionThread.java:95)
Exception in thread "Thread-33" java.lang.NullPointerException
Exception in thread "Thread-34" java.lang.NullPointerException
Exception in thread "Thread-32" java.lang.NullPointerException

I switched to sage_v3.0.1.jar and so far I have not seen any problems in the log files.

**Comment by charlesshale** [comment]
Just fixed that and made a new RC #3 for Sage 3.0, attached here:

https://github.com/hartwigmedical/hmftools/releases/tag/sage-v3.0
