### ISSUE TITLE
LiLaC error: Unrecognized option: -gene_copy_number_file

### ISSUE THREAD

**Issue by Biojenifer** [hartwigmedical/hmftools#316]
Hi!

Do you know which is the new name of this argument for lilac_v1.3_rc2.jar: -gene_copy_number_file?

I get the following error:

`Exception in thread "main" org.apache.commons.cli.UnrecognizedOptionException: Unrecognized option: -gene_copy_number_file
        at org.apache.commons.cli.DefaultParser.handleUnknownToken(DefaultParser.java:347)
        at org.apache.commons.cli.DefaultParser.handleConcatenatedOptions(DefaultParser.java:689)
        at org.apache.commons.cli.DefaultParser.handleShortAndLongOption(DefaultParser.java:520)
        at org.apache.commons.cli.DefaultParser.handleToken(DefaultParser.java:243)
        at org.apache.commons.cli.DefaultParser.parse(DefaultParser.java:120)
        at org.apache.commons.cli.DefaultParser.parse(DefaultParser.java:76)
        at org.apache.commons.cli.DefaultParser.parse(DefaultParser.java:60)
        at com.hartwig.hmftools.lilac.LilacApplication.createCommandLine(LilacApplication.java:763)
        at com.hartwig.hmftools.lilac.LilacApplication.main(LilacApplication.java:737)`
        
        
I am using this version because I'm trying to resolve the same error explained in [this post](https://github.com/hartwigmedical/hmftools/issues/289) 

Thanks!

**Comment by charlesshale** [comment]
I've just updated the READ-ME - the config name is 'gene_copy_number'.
