### ISSUE TITLE
Lilac gene copy number

### ISSUE THREAD

**Issue by jaesvi** [hartwigmedical/hmftools#318]
Hi,
When running Lilac with gene copy number file, I get a NullPointerException at or after the _building frag-alleles from aminoAcids_ steps, whereas with the same inputs but excluding the gene copy number it runs without problem. Below my command and the exception, and attached the specific gene copy number file (changed the extension from tsv to txt for uploading to github). 
```
java -jar lilac_v1.2.jar \
-sample test \
-ref_genome GRCh38_no_alt_analysis_set.fna.gz \
-ref_genome_version V38 \
-resource_dir hmftools/HMFTools-Resources/Lilac \
-reference_bam test.sliced.merged.bam \
-output_dir lilac-tumour-sliced/ \
-tumor_bam test.sliced.tumour.merged.bam \
-somatic_vcf test.purple.somatic.vcf.gz \
-gene_copy_number test.purple.cnv.gene.tsv

16:43:04 - [INFO ] - loaded 230 allele frequencies from file(hmftools/HMFTools-Resources/Lilac/lilac_allele_frequencies.csv)
16:43:04 - [INFO ] - Lilac version(1.2), key parameters:
16:43:04 - [INFO ] - sample(test) inputs: tumorBam(true) somaticVCF(true) geneCopyNumber(true) rnaBam(false)
...
16:43:33 - [INFO ] - WINNERS_REF: test, 2, A*25:01, A*68:01, B*07:02, B*18:01, C*12:03, C*15:05, 4.826, B*18:177, 145,153,177,140,166,158
16:43:34 - [INFO ] - calculating tumor coverage from frags(1507 highQual=1448)
16:43:34 - [INFO ] - building frag-alleles from aminoAcids(frags=1448 candSeq=6) nucFrags(hetLoci=3 candSeq=283 nucs=1101) knownIndels(0)
Exception in thread "main" java.lang.NullPointerException
	at com.hartwig.hmftools.lilac.variant.CopyNumberAssignment.loadCopyNumberData(CopyNumberAssignment.java:60)
	at com.hartwig.hmftools.lilac.LilacApplication.extractTumorResults(LilacApplication.java:545)
	at com.hartwig.hmftools.lilac.LilacApplication.run(LilacApplication.java:477)
	at com.hartwig.hmftools.lilac.LilacApplication.main(LilacApplication.java:745)
```
[test.purple.cnv.gene.txt](https://github.com/hartwigmedical/hmftools/files/9113307/test.purple.cnv.gene.txt)

Any hint at what is going wrong?  Thanks,
Jose

**Comment by jaesvi** [comment]
Ah, I guess my version of Purple is older and the format of the gene copy number file has changed.
