### ISSUE TITLE
GRIPSS chromosome ranking error (java.lang.NumberFormatException)

### ISSUE THREAD

**Issue by scwatts** [hartwigmedical/hmftools#335]
During breakend realignment, GRIPSS will centre CIs for paired breakends that are not imprecise. This process involves determining whether a start breakend position is inverted and may do so by comparing chromosome rank order using chromosome name ([link](https://github.com/hartwigmedical/hmftools/blob/af29930/hmf-common/src/main/java/com/hartwig/hmftools/common/genome/chromosome/HumanChromosome.java#L128)). However, only main contigs (chr1-22, chrXYM) are handled and ALT contig names (e.g. chr10_GL383545v1_alt) cause a `java.lang.NumberFormatException` error.

Error (and logged messages):

```text
16:00:22.422 [INFO ] loading reference data
16:00:25.072 [INFO ] loaded 3103381 germline SV PON records from file(./data/reference/gridss_pon_breakpoint.38.bedpe.gz)
16:00:26.056 [INFO ] loaded 1520513 germline SGL PON records from file(./data/reference/gridss_pon_single_breakend.38.bed.gz)
16:00:26.060 [INFO ] loaded 458 known hotspot records from file
16:00:48.824 [INFO ] loaded 5417857 repeat-mask entries from file(./data/reference/38.fa.out.gz)
16:00:48.929 [INFO ] sample(sample_normal) processing VCF(./data/sample/sv.gridss.vcf.gz)
16:00:48.934 [INFO ] tumor genetype info(0: sample_normal)
16:00:48.979 [INFO ] read VCF: breakends(2) unmatched(0) complete(1) hardFiltered(0)
16:00:48.979 [INFO ] writing output VCF files to ./output/
16:00:49.121 [INFO ] applying soft-filters and realignment
Exception in thread "main" java.lang.NumberFormatException: For input string: "10_GL383545v1_alt"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.base/java.lang.Integer.parseInt(Integer.java:652)
	at java.base/java.lang.Integer.parseInt(Integer.java:770)
	at com.hartwig.hmftools.common.genome.chromosome.HumanChromosome.chromosomeRank(HumanChromosome.java:146)
	at com.hartwig.hmftools.gripss.BreakendRealigner.centreAlignConfidenceIntervals(BreakendRealigner.java:92)
	at com.hartwig.hmftools.gripss.BreakendRealigner.realign(BreakendRealigner.java:39)
	at com.hartwig.hmftools.gripss.GripssApplication.processVcf(GripssApplication.java:190)
	at com.hartwig.hmftools.gripss.GripssApplication.run(GripssApplication.java:121)
	at com.hartwig.hmftools.gripss.GripssApplication.main(GripssApplication.java:374)
```

Command:

```bash
java \
  -Xmx12g \
  -jar ./software/gripss_v2.3.jar \
    -sample sample_normal \
    -ref_genome_version 38 \
    -ref_genome ./data/reference/hg38.fa \
    -pon_sgl_file ./data/reference/gridss_pon_single_breakend.38.bed.gz \
    -pon_sv_file ./data/reference/gridss_pon_breakpoint.38.bedpe.gz \
    -known_hotspot_file ./data/reference/known_fusions.38.bedpe \
    -vcf ./data/sample/sv.gridss.vcf.gz \
    -repeat_mask_file ./data/reference/38.fa.out.gz \
    -output_dir ./output/
```

<details><summary>Reproducible example (click to show)</summary>

<br />

Attachment: [sv.gridss.vcf.gz](https://github.com/hartwigmedical/hmftools/files/9816917/sv.gridss.vcf.gz)

```bash
# Prepare
# Reference data expected to be under `./data/reference/`
mkdir -p software/ data/sample/
wget -P software/ https://github.com/hartwigmedical/hmftools/releases/download/gripss-v2.3/gripss_v2.3.jar
wget -P data/sample/ https://github.com/hartwigmedical/hmftools/files/9816917/sv.gridss.vcf.gz

# Run GRIPSS (fails)
mkdir -p 1_gripss_alt_error/
java \
  -Xmx12g \
  -jar ./software/gripss_v2.3.jar \
    -sample sample_normal \
    -ref_genome_version 38 \
    -ref_genome ./data/reference/hg38.fa \
    -pon_sgl_file ./data/reference/gridss_pon_single_breakend.38.bed.gz \
    -pon_sv_file ./data/reference/gridss_pon_breakpoint.38.bedpe.gz \
    -known_hotspot_file ./data/reference/known_fusions.38.bedpe \
    -vcf ./data/sample/sv.gridss.vcf.gz \
    -repeat_mask_file ./data/reference/38.fa.out.gz \
    -output_dir ./1_gripss_alt_error/

# Replace ALT contig name with main name for demonstration purposes
bcftools view ./data/sample/sv.gridss.vcf.gz | \
  sed '/^#/ ! { s/chr10_GL383545v1_alt/chr10/g }' | \
  bcftools view --no-version -o ./data/sample/sv.gridss.noalt.vcf.gz

# Run GRIPSS (succeeds)
mkdir -p 2_gripss_noalt/
java \
  -Xmx12g \
  -jar ./software/gripss_v2.3.jar \
    -sample sample_normal \
    -ref_genome_version 38 \
    -ref_genome ./data/reference/hg38.fa \
    -pon_sgl_file ./data/reference/gridss_pon_single_breakend.38.bed.gz \
    -pon_sv_file ./data/reference/gridss_pon_breakpoint.38.bedpe.gz \
    -known_hotspot_file ./data/reference/known_fusions.38.bedpe \
    -vcf ./data/sample/sv.gridss.noalt.vcf.gz \
    -repeat_mask_file ./data/reference/38.fa.out.gz \
    -output_dir ./2_gripss_noalt/
```

</details>

**Comment by charlesshale** [comment]
Fixed in v2.3.1:

https://github.com/hartwigmedical/hmftools/releases/tag/gripss-v2.3.1
