### ISSUE TITLE
Error with sv_prep

### ISSUE THREAD

**Issue by insilicool** [hartwigmedical/hmftools#345]
Hi,

I am testing sv_prep for potential addition to our workflow, but unfortunately, it is erroring out when parsing the known_fusion_data.37.csv from the latest resource bundle

Error:
15:40:46.242 [main] [INFO ] SvPrep version: 1.0.1
15:40:46.262 [main] [INFO ] refGenome(V37), bam(alignment/COLO829T/COLO829T.sorted.dup.recal.bam)
15:40:46.263 [main] [INFO ] output(SVariants/COLO829/GRIDSS/sv_prep/)
15:40:46.306 [main] [ERROR] invalid hotspot entry: Type,FiveGene,ThreeGene,CancerTypes,PubMedId,KnownExonTranscript,KnownExonUpRange,KnownExonDownRange,HighImpactPromiscuous,Overrides
15:40:46.359 [main] [INFO ] loaded 6402 blacklist locations from file

Command:

module purge && module load mugqic/java/openjdk-jdk-19 && \
mkdir -p SVariants/COLO829/GRIDSS/sv_prep && \
java -XX:+UseParallelGC -XX:ParallelGCThreads=1 -Dsamjdk.buffer_size=4194304 -Xmx36G \
-jar bin/sv-prep_v1.0.1.jar -threads 6 \
-sample COLO829T \
-bam_file alignment/COLO829T/COLO829T.sorted.dup.recal.bam \
-ref_genome Homo_sapiens.hs37d5.fa \
-ref_genome_version 37 \
-blacklist_bed hmf_pipeline_resources.37_v5.31/sv/sv_prep_blacklist.37.bed \
-known_fusion_bed hmf_pipeline_resources.37_v5.31/sv/known_fusion_data.37.csv \
-output_dir SVariants/COLO829/GRIDSS/sv_prep

Also, I've added -log_debug and -log_level DEBUG to the argument and it outputs the same uninformative error.

Any help would be much appreciated.

Thanks,
 Rob Eveleigh

**Comment by p-priestley** [comment]
I think you parsed the wrong file into the algorithm.   You need to use this file:  known_fusions.37.bedpe  (not the csv file)

**Comment by insilicool** [comment]
Apologizes.  Indeed that was the issue.

Unfortunately, a new issue has arisen when applying the algorithm to the reference using the tumor junctions.

Command:
module purge && module load mugqic/java/openjdk-jdk-19 && \
java -XX:+UseParallelGC -XX:ParallelGCThreads=1 -Dsamjdk.buffer_size=4194304 -Xmx36G \
-jar bin/sv-prep_v1.0.1.jar -threads 6 \
-sample COLO829N \
-bam_file COLO829N.sorted.dup.recal.bam \
-ref_genome Homo_sapiens.hs37d5.fa \
-ref_genome_version 37 \
-blacklist_bed hg37.blacklist.bed \
-known_fusion_bed known_fusions.37.bedpe \
-existing_junction_file SVariants/COLO829/GRIDSS/sv_prep/COLO829T.sv_prep.junctions.csv \
-output_dir SVariants/GRIDSS/COLO829/sv_prep 

Error:
08:21:07.360 [main] [INFO ] SvPrep version: 1.0.1
08:21:07.370 [main] [INFO ] refGenome(V37), bam(alignment/COLO829N/COLO829N.sorted.dup.recal.bam)
08:21:07.371 [main] [INFO ] output(SVariants/GRIDSS/COLO829/sv_prep/)
08:21:07.380 [main] [INFO ] loaded 458 known hotspot records from file
08:21:07.381 [main] [INFO ] loaded 164 blacklist locations from file
08:21:07.387 [main] [ERROR]  failed to create junction writer: java.io.FileNotFoundException: SVariants/GRIDSS/COLO829/sv_prep/COLO829N.sv_prep.junctions.csv (No such file or directory)
Exception in thread "main" htsjdk.samtools.util.RuntimeIOException: Error opening file: file:///lb/project/mugqic/projects/DREAM_techdev/SVariants/GRIDSS/COLO829/sv_prep/COLO829N.sv_prep.bam
	at htsjdk.samtools.SAMFileWriterFactory.makeBAMWriter(SAMFileWriterFactory.java:306)
	at htsjdk.samtools.SAMFileWriterFactory.makeBAMWriter(SAMFileWriterFactory.java:276)
	at htsjdk.samtools.SAMFileWriterFactory.makeBAMWriter(SAMFileWriterFactory.java:252)
	at com.hartwig.hmftools.svprep.BamWriter.initialise(BamWriter.java:44)
	at com.hartwig.hmftools.svprep.BamWriter.<init>(BamWriter.java:30)
	at com.hartwig.hmftools.svprep.ResultsWriter.<init>(ResultsWriter.java:64)
	at com.hartwig.hmftools.svprep.SvPrepApplication.<init>(SvPrepApplication.java:30)
	at com.hartwig.hmftools.svprep.SvPrepApplication.main(SvPrepApplication.java:133)
Caused by: java.nio.file.NoSuchFileException: SVariants/GRIDSS/COLO829/sv_prep/COLO829N.sv_prep.bam
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:218)
	at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:484)
	at java.base/java.nio.file.Files.newOutputStream(Files.java:228)
	at htsjdk.samtools.SAMFileWriterFactory.makeBAMWriter(SAMFileWriterFactory.java:294)
	... 7 more

Best,
 Rob E.

**Comment by charlesshale** [comment]
Hi Rob,

SvPrep doesn't currently create new output directories, so it will need the one you specify to exist:

-output_dir SVariants/GRIDSS/COLO829/sv_prep

Can you try that?

thanks,

Charles
