### ISSUE TITLE
cobalt, R execution failed. Unable to complete segmentation.

### ISSUE THREAD

**Issue by a00101** [hartwigmedical/hmftools#38]
```
# java -Xmx32G -jar cobalt_v1-4.jar \
-reference test_N -reference_bam test_N.bam \
-tumor test_T -tumor_bam test_T.bam \
-output_dir ./ -threads 16 \
-gc_profile GC_profile.hg38.1000bp.cnp

19:53:50 - COBALT version: 1.4
19:53:50 - Thread Count: 16, Window Size: 1000, Min Quality 10
19:53:50 - Reading GC Profile
19:53:52 - Calculating Read Count from test_T.bam
19:53:52 - Generating windows on chromosome chr1
19:53:52 - Generating windows on chromosome chr2
19:53:52 - Generating windows on chromosome chr3
19:53:52 - Generating windows on chromosome chr4
19:53:52 - Generating windows on chromosome chr5
19:53:52 - Generating windows on chromosome chr6
19:53:52 - Generating windows on chromosome chr7
19:53:52 - Generating windows on chromosome chr8
19:53:52 - Generating windows on chromosome chr9
19:53:52 - Generating windows on chromosome chr10
19:53:52 - Generating windows on chromosome chr11
19:53:52 - Generating windows on chromosome chr12
19:53:52 - Generating windows on chromosome chr13
19:53:52 - Generating windows on chromosome chr14
19:53:52 - Calculating Read Count from test_N.bam
19:53:52 - Generating windows on chromosome chr15
19:53:52 - Generating windows on chromosome chr16
20:22:31 - Generating windows on chromosome chr17
20:24:30 - Generating windows on chromosome chr18
20:25:54 - Generating windows on chromosome chr19
20:33:06 - Generating windows on chromosome chr20
20:38:11 - Generating windows on chromosome chr21
20:40:14 - Generating windows on chromosome chr22
20:42:00 - Generating windows on chromosome chrX
20:42:40 - Generating windows on chromosome chrY
20:45:14 - Generating windows on chromosome chrM
20:45:26 - Generating windows on chromosome chr1
20:45:57 - Generating windows on chromosome chr2
20:50:21 - Generating windows on chromosome chr3
20:52:01 - Generating windows on chromosome chr4
20:52:41 - Generating windows on chromosome chr5
20:53:44 - Generating windows on chromosome chr6
20:54:41 - Generating windows on chromosome chr7
20:58:10 - Generating windows on chromosome chr8
21:00:14 - Generating windows on chromosome chr9
21:00:38 - Generating windows on chromosome chr10
21:04:19 - Generating windows on chromosome chr11
21:14:00 - Generating windows on chromosome chr12
21:17:54 - Generating windows on chromosome chr13
21:29:30 - Generating windows on chromosome chr14
21:30:19 - Generating windows on chromosome chr15
21:41:38 - Generating windows on chromosome chr16
21:44:15 - Generating windows on chromosome chr17
21:51:52 - Generating windows on chromosome chr18
21:52:24 - Generating windows on chromosome chr19
21:53:22 - Generating windows on chromosome chr20
21:54:26 - Generating windows on chromosome chr21
21:57:31 - Generating windows on chromosome chr22
21:57:52 - Generating windows on chromosome chrX
22:01:17 - Generating windows on chromosome chrY
22:03:45 - Generating windows on chromosome chrM
22:17:22 - Read Count Complete
22:17:22 - Excluding unsupported chr9 chromosome from read counts
22:17:22 - Excluding unsupported chr7 chromosome from read counts
22:17:22 - Excluding unsupported chr8 chromosome from read counts
22:17:22 - Excluding unsupported chr5 chromosome from read counts
22:17:22 - Excluding unsupported chr6 chromosome from read counts
22:17:22 - Excluding unsupported chr3 chromosome from read counts
22:17:22 - Excluding unsupported chr21 chromosome from read counts
22:17:22 - Excluding unsupported chr4 chromosome from read counts
22:17:22 - Excluding unsupported chr22 chromosome from read counts
22:17:22 - Excluding unsupported chr1 chromosome from read counts
22:17:22 - Excluding unsupported chr2 chromosome from read counts
22:17:22 - Excluding unsupported chr20 chromosome from read counts
22:17:22 - Excluding unsupported chrY chromosome from read counts
22:17:22 - Excluding unsupported chrX chromosome from read counts
22:17:22 - Excluding unsupported chr10 chromosome from read counts
22:17:22 - Excluding unsupported chr11 chromosome from read counts
22:17:22 - Excluding unsupported chr12 chromosome from read counts
22:17:22 - Excluding unsupported chr13 chromosome from read counts
22:17:22 - Excluding unsupported chrM chromosome from read counts
22:17:22 - Excluding unsupported chr18 chromosome from read counts
22:17:22 - Excluding unsupported chr19 chromosome from read counts
22:17:22 - Excluding unsupported chr14 chromosome from read counts
22:17:22 - Excluding unsupported chr15 chromosome from read counts
22:17:22 - Excluding unsupported chr16 chromosome from read counts
22:17:22 - Excluding unsupported chr17 chromosome from read counts
22:17:22 - Applying ratio gc normalization
22:17:22 - Applying ratio diploid normalization
22:17:22 - Persisting gc read count medians to ./
22:17:22 - Persisting cobalt ratios to test_T.cobalt
22:17:22 - Executing R script via command: Rscript /tmp/script6680161850079528767.R test_T.cobalt TumorGCRatio test_T.cobalt.ratio.pcf
22:17:22 - Executing R script via command: Rscript /tmp/script3259465341395476612.R test_T.cobalt ReferenceGCDiploidRatio test_N.cobalt.ratio.pcf
Exception in thread "main" java.util.concurrent.ExecutionException: java.io.IOException: R execution failed. Unable to complete segmentation.
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at com.hartwig.hmftools.cobalt.RatioSegmentation.applySegmentation(RatioSegmentation.java:37)
        at com.hartwig.hmftools.cobalt.CountBamLinesApplication.<init>(CountBamLinesApplication.java:128)
        at com.hartwig.hmftools.cobalt.CountBamLinesApplication.main(CountBamLinesApplication.java:52)
Caused by: java.io.IOException: R execution failed. Unable to complete segmentation.
        at com.hartwig.hmftools.cobalt.RatioSegmentation.ratioSegmentation(RatioSegmentation.java:48)
        at com.hartwig.hmftools.cobalt.RatioSegmentation.lambda$applySegmentation$0(RatioSegmentation.java:33)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

```

cobalt is working currently. I guess something is going wrong.
is it alright?

**Comment by jonbaber** [comment]
It looks like cobalt has completed successfully but after that we run a R script to generate the segmentation which seems to have failed. 

Have you installed the [R dependencies](https://github.com/hartwigmedical/hmftools/tree/master/count-bam-lines#r-dependencies)?

You can manually diagnose the issue by downloading the [script](https://github.com/hartwigmedical/hmftools/blob/master/count-bam-lines/src/main/resources/r/ratioSegmentation.R) and running it manually with the command:

```
Rscript ratioSegmentation.R test_T.cobalt TumorGCRatio test_T.cobalt.ratio.pcf
Rscript ratioSegmentation.R test_T.cobalt ReferenceGCDiploidRatio test_N.cobalt.ratio.pcf
```

If this fails to provide further information you may need to run it line by line in R.

**Comment by a00101** [comment]
it works well using latest version (cobalt 1.6) 
thanks.

**Comment by TnakaNY** [comment]
Hi,
I had a same error in v1.9. 
My PC is windows10, R4.0.

I did your recommendation (May15, 2019). It looks there is some errors in R script. 
When I used v1.8, it ran with no error. 
--------------------------------
D:\GRIDSStest\test5\cobalt>Rscript test.R test_T.cobalt TumorGCRatio CPCT12345678T.cobalt.ratio.pcf
Loading required package: BiocGenerics
Loading required package: parallel

Attaching package: 'BiocGenerics'

The following objects are masked from 'package:parallel':

    clusterApply, clusterApplyLB, clusterCall, clusterEvalQ,
    clusterExport, clusterMap, parApply, parCapply, parLapply,
    parLapplyLB, parRapply, parSapply, parSapplyLB

The following objects are masked from 'package:stats':

    IQR, mad, sd, var, xtabs

The following objects are masked from 'package:base':

    anyDuplicated, append, as.data.frame, basename, cbind, colnames,
    dirname, do.call, duplicated, eval, evalq, Filter, Find, get, grep,
    grepl, intersect, is.unsorted, lapply, Map, mapply, match, mget,
    order, paste, pmax, pmax.int, pmin, pmin.int, Position, rank,
    rbind, Reduce, rownames, sapply, setdiff, sort, table, tapply,
    union, unique, unsplit, which, which.max, which.min

Error in file(file, "rt") : cannot open the connection
Calls: read.table -> file
In addition: Warning message:
In file(file, "rt") :
  cannot open file 'test_T.cobalt': No such file or directory
Execution halted
-------------------------------------------------------------------

Best.

**Comment by jonbaber** [comment]
Please use fully qualified file names including their path. 

Also, it is unlikely that the files are called test_T.cobalt & CPCT12345678T.cobalt.ratio.pcf as they should take the form SAMPLE.cobalt and SAMPLE.cobalt.ratio.pcf so their should either be:

test_T.cobalt and test_T.cobalt.ratio.pcf

or they will be:

CPCT12345678T.cobalt and CPCT12345678T.cobalt.ratio.pcf.
