### ISSUE TITLE
SAGE problem: VCF header has duplicate sample names

### ISSUE THREAD

**Issue by rod1Gene** [hartwigmedical/hmftools#399]
For SAGE, when I run this

java -Xms4G -Xmx32G -cp $HOME/bin/jars/sage_v3.2.5.jar com.hartwig.hmftools.sage.SageApplication \
    -tumor 679252_and_GN013939 \
    -tumor_bam 679252_and_GN013939_0801-T_chr6_sorted.bam \
    -ref_genome /home/rod1/GCA_000001405.15_GRCh38_no_alt_analysis_set_chr6.fna \
    -ref_genome_version 38 \
    -out 679252_and_GN013939.sage.rna.vcf.gz \
    -hotspots /home/rod1/variants/KnownHotspots.somatic.38.vcf.gz \
    -panel_bed /home/rod1/variants/ActionableCodingPanel.38.bed.gz \
    -high_confidence_bed /home/rod1/variants/HG001_GRCh38_GIAB_highconf_CG-IllFB-IllGATKHC-Ion-10X-SOLID_CHROM1-X_v.3.3.2_highconf_nosomaticdel_noCENorHET7.bed.gz \
    -ensembl_data_dir /home/rod1/common/ensembl_data \
    -reference 679252_and_GN013939 \
    -reference_bam 679252_and_GN013939_0801-N_chr6_sorted.bam

I get this output

[INFO ] Sage version: 3.2.5
[INFO ] read 5961 panel entries from bed file: /home/rod1/variants/ActionableCodingPanel.38.bed.gz
read 9456 hotspots from vcf: /home/rod1/variants/KnownHotspots.somatic.38.vcf.gz
read 438100 high-confidence entries from bed file: /home/rod1/variants/HG001_GRCh38_GIAB_highconf_CG-IllFB-IllGATKHC-Ion-10X-SOLID_CHROM1-X_v.3.3.2_highconf_nosomaticdel_noCENorHET7.bed
Exception in thread "main" htsjdk.tribble.TribbleException$InvalidHeader: Your input file has a malformed header: BUG: VCF header has duplicate sample names
	at htsjdk.variant.vcf.VCFHeader.<init>(VCFHeader.java:163)
	at com.hartwig.hmftools.sage.vcf.VariantVCF.header(VariantVCF.java:148)
	at com.hartwig.hmftools.sage.vcf.VariantVCF.header(VariantVCF.java:143)
	at com.hartwig.hmftools.sage.vcf.VariantVCF.<init>(VariantVCF.java:101)
	at com.hartwig.hmftools.sage.vcf.VcfWriter.<init>(VcfWriter.java:22)
	at com.hartwig.hmftools.sage.SageApplication.<init>(SageApplication.java:66)
	at com.hartwig.hmftools.sage.SageApplication.main(SageApplication.java:148)

Any idea what I did wrong? It looks like it read the only vcf file okay.

**Comment by charlesshale** [comment]
The tumor and reference names need to be different.
