### ISSUE TITLE
SAGE exception: ... because "this.mRefContext" is null

### ISSUE THREAD

**Issue by rod1Gene** [hartwigmedical/hmftools#401]
Sorry for all the questions, but here's another:

I'm trying SAGE on _exonic_ sequences. Since I'm using this ultimately for LILAC, I realigned the reads from chr6 alts to chr6 and used just chr6 as my reference.

When I run this

java -Xms4G -Xmx32G -cp $HOME/bin/jars/sage_v3.2.5.jar com.hartwig.hmftools.sage.SageApplication
-tumor 679252_and_GN013939_t
-tumor_bam 679252_and_GN013939_0801-T_chr6_sorted.bam
-ref_genome /home/rod1/GCA_000001405.15_GRCh38_no_alt_analysis_set_chr6.fna
-ref_genome_version 38
-out 679252_and_GN013939.sage.rna.vcf.gz
-hotspots /home/rod1/variants/KnownHotspots.somatic.38.vcf.gz
-panel_bed /home/rod1/variants/ActionableCodingPanel.38.bed.gz
-high_confidence_bed /home/rod1/variants/HG001_GRCh38_GIAB_highconf_CG-IllFB-IllGATKHC-Ion-10X-SOLID_CHROM1-X_v.3.3.2_highconf_nosomaticdel_noCENorHET7.bed.gz
-ensembl_data_dir /home/rod1/common/ensembl_data
-reference 679252_and_GN013939_n
-reference_bam 679252_and_GN013939_0801-N_chr6_sorted.bam

I get these two lines many times in the output
[WARN ] registerDepthLimit: ignoring read with position(141201) before prior position(203333)
[WARN ] registerDepth: ignoring read with position(141201) before prior position(203333)

and then this

[ERROR] thread execution error: java.lang.NullPointerException: Cannot invoke "com.hartwig.hmftools.sage.candidate.RefContext.processAltRead(String, String, int, int, com.hartwig.hmftools.sage.common.ReadContext)" because "this.mRefContext" is null
java.lang.NullPointerException: Cannot invoke "com.hartwig.hmftools.sage.candidate.RefContext.processAltRead(String, String, int, int, com.hartwig.hmftools.sage.common.ReadContext)" because "this.mRefContext" is null
	at com.hartwig.hmftools.sage.candidate.AltRead.updateRefContext(AltRead.java:73)
	at com.hartwig.hmftools.sage.candidate.RefContextConsumer.processRead(RefContextConsumer.java:190)
	at com.hartwig.hmftools.sage.evidence.CandidateEvidence.lambda$readBam$1(CandidateEvidence.java:52)
	at com.hartwig.hmftools.common.samtools.BamSlicer.slice(BamSlicer.java:70)
	at com.hartwig.hmftools.sage.common.SamSlicer.slice(SamSlicer.java:28)
	at com.hartwig.hmftools.sage.evidence.CandidateEvidence.readBam(CandidateEvidence.java:72)
	at com.hartwig.hmftools.sage.evidence.CandidateEvidence.readBam(CandidateEvidence.java:60)
	at com.hartwig.hmftools.sage.pipeline.CandidateStage.findCandidates(CandidateStage.java:59)
	at com.hartwig.hmftools.sage.pipeline.RegionTask.run(RegionTask.java:92)
	at com.hartwig.hmftools.sage.pipeline.RegionThread.run(RegionThread.java:95)

When I add '-specific_regions chr6', it just outputs the version number.

**Comment by charlesshale** [comment]
Hi Rod,

See comments in the other ticket about using the non-alt ref genome with out pipeline and tools.

thanks.
