### ISSUE TITLE
Amber error; IndexOutofBoundsException

### ISSUE THREAD

**Issue by a00101** [hartwigmedical/hmftools#42]
I got an error with Amber

```
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(ArrayList.java:657)
        at java.util.ArrayList.get(ArrayList.java:433)
        at com.hartwig.hmftools.common.amber.TumorContaminationModel.medianDepth(TumorContaminationModel.java:98)
        at com.hartwig.hmftools.common.amber.TumorContaminationModel.contamination(TumorContaminationModel.java:23)
        at com.hartwig.hmftools.amber.AmberPersistence.persisQC(AmberPersistence.java:53)
        at com.hartwig.hmftools.amber.AmberApplication.run(AmberApplication.java:120)
        at com.hartwig.hmftools.amber.AmberApplication.main(AmberApplication.java:64)

```

version=2.3
build.date=2019-04-05 00:49
CMD = 
java -Xmx32G -jar amber-2.3.jar 
-reference NSLA_464_N -reference_bam NSLA_464_N_FINAL.bam 
-tumor NSLA_464_T -tumor_bam NSLA_464_T_FINAL.bam 
-output_dir /data/Amber_result 
-threads 16 -ref_genome Hg38.fa 
-bed bundle/GermlineHetPon.hg38.bed

Thanks in advance.

**Comment by jonbaber** [comment]
Can you please try with the latest version of [amber](https://github.com/hartwigmedical/hmftools/releases/tag/amber-v2-5)

**Comment by a00101** [comment]
If so, do I have to re-run all samples with newly versions?

**Comment by jonbaber** [comment]
The newest version of AMBER changes the output filename. You will need to run PURPLE 2.3 or later to recognise the new files names. 

You do not need to run AMBER again for all your old samples, PURPLE 2.3 and onwards supports both the old and the new names.

**Comment by a00101** [comment]
Is Amber download address under construction? I can't download at all.
Please check this out if you would.

Thanks.

**Comment by a00101** [comment]
https://github.com/hartwigmedical/hmftools/releases/download/amber-v2-5/amber-2.5.jar

**Comment by jonbaber** [comment]
That link works for me

**Comment by p-priestley** [comment]
Closing issue due to no further feedback

**Comment by mroosmalen** [comment]
I got the same IndexOutOfBoundsException with AMBER version: 3.1 when I'm using the hg38 reference genome. When I use the hg19 reference genome it works fine.

Can you help me, solving this problem?

**Comment by jonbaber** [comment]
Hi Mark, 

Happy to take a look for you. Could you please provide a stack trace (similar to the one above) just to make sure it is the exact same problem.

Thanks, Jon

**Comment by mroosmalen** [comment]
Hi Jon

Thank you for your time. Here is more information. The command that I try to run is:

```
java -Xmx10G \
-Dreference_fasta=/hpc/pmc_vanboxtel/data/homo_sapiens.GRCh38.GATK.illumina//Homo_sapiens_assembly38.fasta \
-Dsamjdk.use_async_io_read_samtools=true \
-Dsamjdk.use_async_io_write_samtools=true \
-Dsamjdk.use_async_io_write_tribble=true \
-Dsamjdk.buffer_size=4194304 \
-jar /hpc/local/CentOS7/pmc_vanboxtel/bin/amber-3.1/amber-3.1.jar \
-threads 8 \
-tumor PMC21636_T \
-reference PMC21636_N \
-tumor_bam /hpc/pmc_vanboxtel/projects/Markus_GRIDSSpipeline/PMC21636_hg38/IAP/PMC21636AMLBULK/mapping/PMC21636AMLBULK_dedup.bam \
-reference_bam /hpc/pmc_vanboxtel/projects/Markus_GRIDSSpipeline/PMC21636_hg38/IAP/PMC21636MSCBULK/mapping/PMC21636MSCBULK_dedup.bam \
-loci /hpc/local/CentOS7/pmc_vanboxtel/bin/gridss-purple-linx_v1.0.0//dbs/germline_het_pon/GermlineHetPon.hg38.vcf.gz \
-ref_genome /hpc/pmc_vanboxtel/data/homo_sapiens.GRCh38.GATK.illumina//Homo_sapiens_assembly38.fasta \
-output_dir .//amber \
2>&1 | tee .//logs/20200117_075357.n0067.compute.hpc.19982.amber.log
 ```

And this is the output that I get:

```
07:53:58 - AMBER version: 3.1
07:53:58 - Using non default value 8 for parameter threads
07:53:58 - Loading vcf file /hpc/local/CentOS7/pmc_vanboxtel/bin/gridss-purple-linx_v1.0.0//dbs/germline_het_pon/GermlineHetPon.hg38.vcf.gz
07:54:01 - Processing 1337724 potential sites in reference bam /hpc/pmc_vanboxtel/projects/Markus_GRIDSSpipeline/PMC21636_hg38/IAP/PMC21636MSCBULK/mapping/PMC21636MSCBULK_dedup.bam
07:54:12 -   [####################] 100% complete
07:54:12 -   [####################] 100% complete
07:54:17 -   [####################] 100% complete
07:54:20 -   [####################] 100% complete
07:54:22 -   [####################] 100% complete
07:54:23 -   [####################] 100% complete
07:54:24 -   [####################] 100% complete
07:54:24 -   [####################] 100% complete
07:54:25 -   [####################] 100% complete
07:54:32 -   [####################] 100% complete
07:54:38 -   [####################] 100% complete
07:54:39 -   [####################] 100% complete
07:54:40 -   [####################] 100% complete
07:54:41 -   [####################] 100% complete
07:54:45 -   [####################] 100% complete
07:54:53 -   [####################] 100% complete
07:54:58 -   [####################] 100% complete
07:55:00 -   [####################] 100% complete
07:55:04 -   [####################] 100% complete
07:55:07 -   [####################] 100% complete
07:55:08 -   [####################] 100% complete
07:55:11 -   [####################] 100% complete
07:55:12 -   [####################] 100% complete
07:55:12 - Complete
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at com.hartwig.hmftools.common.amber.BaseDepthFilter.medianDepth(BaseDepthFilter.java:38)
	at com.hartwig.hmftools.common.amber.BaseDepthFilter.<init>(BaseDepthFilter.java:23)
	at com.hartwig.hmftools.amber.AmberApplication.runNormalMode(AmberApplication.java:128)
	at com.hartwig.hmftools.amber.AmberApplication.run(AmberApplication.java:119)
	at com.hartwig.hmftools.amber.AmberApplication.main(AmberApplication.java:69)
```

**Comment by jonbaber** [comment]
Thanks. I'll fix it up for you on Monday.

Cheers, Jon

**Comment by jonbaber** [comment]
Can you please try again with the new version: 

https://github.com/hartwigmedical/hmftools/releases/tag/amber-v3.2

Thanks, Jon

**Comment by mroosmalen** [comment]
It works!!

Thanks for the quick fix

**Comment by jonbaber** [comment]
Glad I could help :)
