### ISSUE TITLE
ORANGE (v2.5.0) failed to load LINX (v1.23.6) plots  

### ISSUE THREAD

**Issue by YingYa** [hartwigmedical/hmftools#427]
I am running ORANGE (v2.5.0) to summarize the key outputs from all algorithms in the Hartwig suite. 

But some samples were failed to load linx plots:

Exception in thread "main" java.lang.IllegalStateException: Could not find structural variant that underlies breakend: LinxBreakend{id=85, svId=40, gene=PBRM1, transcriptId=ENST00000296302, canonical=true, geneOrientation=Downstream, disruptive=true, reportedDisruption=true, undisruptedCopyNumber=1.156, regionType=INTRONIC, codingType=CODING, nextSpliceExonRank=16, type=DEL, chromosome=chr3, orientation=1, strand=-1, chrBand=p21.1, exonUp=15, exonDown=16, junctionCopyNumber=0.8836}
        at com.hartwig.hmftools.orange.report.datamodel.BreakendEntryFactory.determineClusterId(BreakendEntryFactory.java:70)
        at com.hartwig.hmftools.orange.report.datamodel.BreakendEntryFactory.create(BreakendEntryFactory.java:33)
        at com.hartwig.hmftools.orange.report.chapters.SomaticFindingsChapter.addBreakends(SomaticFindingsChapter.java:199)
        at com.hartwig.hmftools.orange.report.chapters.SomaticFindingsChapter.render(SomaticFindingsChapter.java:79)
        at com.hartwig.hmftools.orange.report.ReportWriter.writePdfChapters(ReportWriter.java:95)
        at com.hartwig.hmftools.orange.report.ReportWriter.writePdf(ReportWriter.java:64)
        at com.hartwig.hmftools.orange.report.ReportWriter.write(ReportWriter.java:51)
        at com.hartwig.hmftools.orange.OrangeApplication.run(OrangeApplication.java:55)
        at com.hartwig.hmftools.orange.OrangeApplication.main(OrangeApplication.java:39)

**Comment by charlesshale** [comment]
I would suggest running all tools matching a current pipeline version, eg v5.32, to ensure correct and consistent tool outputs.
