### ISSUE TITLE
[ERROR] COBALT error: Column chromosome does not exist in table readRatios summary

### ISSUE THREAD

**Issue by AlexanderKotyurgin** [hartwigmedical/hmftools#437]
I am running COBALT 1.15.1 in paired mode and get this error:

```
06:56:32.522 [main] [INFO ] - COBALT version: 1.15.1, build timestamp: 2023-07-10T21:58:00Z
06:56:32.524 [main] [INFO ] - Reading GC Profile from /input/GC_profile.1000bp.38.cnp
06:56:32.636 [main] [INFO ] - Calculating Read Count from /input/TUMOR.bam
06:56:32.639 [main] [INFO ] - Calculating Read Count from /input/NORMAL.bam
06:56:32.638 [worker-1] [INFO ] - Generating windows on chromosome chr2
06:56:32.638 [worker-0] [INFO ] - Generating windows on chromosome chr1
06:56:32.638 [worker-2] [INFO ] - Generating windows on chromosome chr3
06:56:32.639 [worker-3] [INFO ] - Generating windows on chromosome chr4
06:57:13.189 [worker-3] [INFO ] - Generating windows on chromosome chr5
06:57:33.579 [worker-1] [INFO ] - Generating windows on chromosome chr6
06:57:53.137 [worker-2] [INFO ] - Generating windows on chromosome chr7
06:57:53.264 [worker-0] [INFO ] - Generating windows on chromosome chr8
06:58:11.050 [worker-3] [INFO ] - Generating windows on chromosome chr9
06:59:05.223 [worker-0] [INFO ] - Generating windows on chromosome chr10
06:59:05.712 [worker-2] [INFO ] - Generating windows on chromosome chr11
06:59:31.966 [worker-1] [INFO ] - Generating windows on chromosome chr12
06:59:38.762 [worker-3] [INFO ] - Generating windows on chromosome chr13
06:59:46.971 [worker-2] [INFO ] - Generating windows on chromosome chr14
06:59:47.537 [worker-0] [INFO ] - Generating windows on chromosome chr15
07:00:06.888 [worker-3] [INFO ] - Generating windows on chromosome chr16
07:00:17.103 [worker-2] [INFO ] - Generating windows on chromosome chr17
07:00:29.570 [worker-1] [INFO ] - Generating windows on chromosome chr18
07:00:36.064 [worker-1] [INFO ] - Generating windows on chromosome chr19
07:00:43.850 [worker-3] [INFO ] - Generating windows on chromosome chr20
07:00:57.327 [worker-3] [INFO ] - Generating windows on chromosome chr21
07:01:00.472 [worker-1] [INFO ] - Generating windows on chromosome chr22
07:01:14.604 [worker-3] [INFO ] - Generating windows on chromosome chrX
07:01:22.605 [worker-1] [INFO ] - Generating windows on chromosome chrY
07:01:24.072 [worker-1] [INFO ] - Generating windows on chromosome chr1
07:01:38.367 [worker-2] [INFO ] - Generating windows on chromosome chr2
07:01:39.554 [worker-0] [INFO ] - Generating windows on chromosome chr3
07:02:14.348 [worker-1] [INFO ] - Generating windows on chromosome chr4
07:02:22.501 [worker-3] [INFO ] - Generating windows on chromosome chr5
07:02:22.847 [worker-2] [INFO ] - Generating windows on chromosome chr6
07:02:40.681 [worker-1] [INFO ] - Generating windows on chromosome chr7
07:02:42.320 [worker-0] [INFO ] - Generating windows on chromosome chr8
07:03:11.661 [worker-3] [INFO ] - Generating windows on chromosome chr9
07:03:40.103 [worker-1] [INFO ] - Generating windows on chromosome chr10
07:03:44.610 [worker-0] [INFO ] - Generating windows on chromosome chr11
07:03:58.499 [worker-2] [INFO ] - Generating windows on chromosome chr12
07:04:11.356 [worker-1] [INFO ] - Generating windows on chromosome chr13
07:04:17.636 [worker-3] [INFO ] - Generating windows on chromosome chr14
07:04:22.821 [worker-0] [INFO ] - Generating windows on chromosome chr15
07:04:42.572 [worker-3] [INFO ] - Generating windows on chromosome chr16
07:04:44.329 [worker-1] [INFO ] - Generating windows on chromosome chr17
07:04:46.135 [worker-2] [INFO ] - Generating windows on chromosome chr18
07:04:51.198 [worker-2] [INFO ] - Generating windows on chromosome chr19
07:05:07.032 [worker-2] [INFO ] - Generating windows on chromosome chr20
07:05:08.733 [worker-3] [INFO ] - Generating windows on chromosome chr21
07:05:16.814 [worker-2] [INFO ] - Generating windows on chromosome chr22
07:05:19.968 [worker-3] [INFO ] - Generating windows on chromosome chrX
07:05:34.241 [worker-2] [INFO ] - Generating windows on chromosome chrY
07:06:16.462 [main] [INFO ] - Read Count Complete
07:06:24.517 [main] [INFO ] - calculating sample ratios for TUMOR
07:06:25.304 [main] [INFO ] - merging in gc profile
07:06:48.030 [main] [INFO ] - Applying ratio gc normalization
07:06:56.498 [main] [INFO ] - median read count: 5.797057370299204, sparse consolidation count: 90
07:06:56.717 [main] [INFO ] - chromosome: chr9, lov buckets count: 1108
07:06:56.867 [main] [INFO ] - chromosome: chr7, lov buckets count: 1514
07:06:57.005 [main] [INFO ] - chromosome: chr8, lov buckets count: 1461
07:06:57.155 [main] [INFO ] - chromosome: chr5, lov buckets count: 1799
07:06:57.307 [main] [INFO ] - chromosome: chr6, lov buckets count: 1734
07:06:57.465 [main] [INFO ] - chromosome: chr3, lov buckets count: 2021
07:06:57.538 [main] [INFO ] - chromosome: chr21, lov buckets count: 336
07:06:57.610 [main] [INFO ] - chromosome: chr22, lov buckets count: 321
07:06:57.763 [main] [INFO ] - chromosome: chr4, lov buckets count: 1912
07:06:57.937 [main] [INFO ] - chromosome: chr1, lov buckets count: 2241
07:06:58.119 [main] [INFO ] - chromosome: chr2, lov buckets count: 2410
07:06:58.208 [main] [INFO ] - chromosome: chr20, lov buckets count: 615
07:06:58.274 [main] [INFO ] - chromosome: chrY, lov buckets count: 112
07:06:58.405 [main] [INFO ] - chromosome: chrX, lov buckets count: 1455
07:06:58.528 [main] [INFO ] - chromosome: chr10, lov buckets count: 1324
07:06:58.654 [main] [INFO ] - chromosome: chr11, lov buckets count: 1303
07:06:58.782 [main] [INFO ] - chromosome: chr12, lov buckets count: 1344
07:06:58.906 [main] [INFO ] - chromosome: chr13, lov buckets count: 994
07:06:59.006 [main] [INFO ] - chromosome: chr18, lov buckets count: 774
07:06:59.091 [main] [INFO ] - chromosome: chr19, lov buckets count: 523
07:06:59.197 [main] [INFO ] - chromosome: chr14, lov buckets count: 897
07:06:59.296 [main] [INFO ] - chromosome: chr15, lov buckets count: 787
07:06:59.396 [main] [INFO ] - chromosome: chr16, lov buckets count: 736
07:06:59.491 [main] [INFO ] - chromosome: chr17, lov buckets count: 754
07:06:59.492 [main] [INFO ] - using low coverage ratio
07:06:59.492 [main] [INFO ] - using 28475 sparse consolidated buckets, from 2560371 input ratios
07:07:09.675 [main] [INFO ] - Persisting TUMOR gc read count to /output/cobalt
07:07:09.689 [main] [INFO ] - calculating sample ratios for NORMAL
07:07:10.249 [main] [INFO ] - merging in gc profile
07:07:32.772 [main] [INFO ] - Applying ratio gc normalization
07:07:39.615 [main] [INFO ] - using low coverage ratio
07:07:39.615 [main] [INFO ] - using 28475 sparse consolidated buckets, from 2560376 input ratios
07:07:48.189 [main] [INFO ] - Persisting NORMAL gc read count to /output/cobalt
07:07:48.194 [main] [ERROR] - [Thread[main,5,main]]: uncaught exception: java.lang.IllegalStateException: Column chromosome does not exist in table readRatios summary
java.lang.IllegalStateException: Column chromosome does not exist in table readRatios summary
        at tech.tablesaw.table.Relation.column(Relation.java:142)
        at tech.tablesaw.table.Relation.stringColumn(Relation.java:607)
        at com.hartwig.hmftools.cobalt.CobaltUtils.toCommonChromosomeMap(CobaltUtils.java:29)
        at com.hartwig.hmftools.cobalt.ratio.RatioSupplier$GermlineRatios.<init>(RatioSupplier.java:149)
        at com.hartwig.hmftools.cobalt.ratio.RatioSupplier.tumorNormalPair(RatioSupplier.java:241)
        at com.hartwig.hmftools.cobalt.CobaltApplication.run(CobaltApplication.java:146)
        at com.hartwig.hmftools.cobalt.CobaltApplication.main(CobaltApplication.java:86)
```
Tumor-only mode is working fine, while germline mode get the same error. I'm pretty sure that problem is not in bam files, because I get error even when I supply germline mode with tumor file or swap files in paired mode, but don't get it when I analyze reference bam file in tumor-mode only. 
UPD: changed logs to more readable version

**Comment by hongwingl** [comment]
Hi,

Thanks for the detailed bug report. I have made a new cobalt release to fix this.

https://github.com/hartwigmedical/hmftools/releases/tag/cobalt-v1.15.2
