### ISSUE TITLE
purple v2.31

### ISSUE THREAD

**Issue by galder-max** [hartwigmedical/hmftools#44]
When providing -ref_genome FASTA file:

Exception in thread "main" java.lang.NullPointerException
        at com.hartwig.hmftools.common.chromosome.ChromosomeLengthFactory.create(ChromosomeLengthFactory.java:45)
        at com.hartwig.hmftools.purple.config.RefGenomeData.createRefGenomeConfig(RefGenomeData.java:71)
        at com.hartwig.hmftools.purple.config.ConfigSupplier.<init>(ConfigSupplier.java:128)
        at com.hartwig.hmftools.purple.PurityPloidyEstimateApplication.<init>(PurityPloidyEstimateApplication.java:114)
        at com.hartwig.hmftools.purple.PurityPloidyEstimateApplication.main(PurityPloidyEstimateApplication.java:96)

The same call runs fine with v2.30 without -ref_genome

**Comment by jonbaber** [comment]
I have managed to reproduce this bug. 

In the same directory as the fasta file there needs to be an associated dict file. 

You can create a dict file using samtools with the command `samtools dict ref_genome.fasta`

I will update the documentation to reflect this.

**Comment by galder-max** [comment]
Thanks a lot for the prompt response!

**Comment by jonbaber** [comment]
You're welcome :)
