### ISSUE TITLE
Exception in thread "main" java.lang.IllegalArgumentException: No enum constant com.hartwig.hmftools.common.amber.BaseDepthData.Base.GA

### ISSUE THREAD

**Issue by gagank4911** [hartwigmedical/hmftools#448]
:~/gagan/ECLIPSE_Final$ java -Xmx16G -cp amber-3.9.jar com.hartwig.hmftools.amber.AmberApplication -reference VSI_15_S24 -reference_bam VSI_15_S24_sentieon_match_4.1_deduped.bam -tumor TCS176___S33 -tumor_bam TCS176___S33_sentieon_match_4.1_deduped.bam -output_dir /amber_out -ref_genome_version 38 -threads 8 -loci TCS176___S33_TNscope_NEW.vcf
10:07:20.610 INFO  [main] - AMBER version: 3.9
10:07:20.613 INFO  [main] - Loading vcf file TCS176___S33_TNscope_NEW.vcf
10:07:21.186 INFO  [main] - loaded 5439 baf loci
10:07:21.262 INFO  [main] - Processing 5439 potential sites in reference bam VSI_15_S24_sentieon_match_4.1_deduped.bam
Exception in thread "main" java.lang.IllegalArgumentException: No enum constant com.hartwig.hmftools.common.amber.BaseDepthData.Base.GA
        at java.base/java.lang.Enum.valueOf(Enum.java:240)
        at com.hartwig.hmftools.common.amber.BaseDepthData$Base.valueOf(BaseDepthData.java:11)
        at com.hartwig.hmftools.common.amber.BaseDepthFactory.fromAmberSite(BaseDepthFactory.java:46)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
        at com.google.common.collect.CollectSpliterators$FlatMapSpliterator.lambda$forEachRemaining$1(CollectSpliterators.java:377)
        at java.base/java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1693)
        at com.google.common.collect.CollectSpliterators$FlatMapSpliterator.forEachRemaining(CollectSpliterators.java:373)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
        at com.hartwig.hmftools.amber.AmberGermline.germlineDepth(AmberGermline.java:101)
        at com.hartwig.hmftools.amber.AmberGermline.<init>(AmberGermline.java:65)
        at com.hartwig.hmftools.amber.AmberApplication.runNormalMode(AmberApplication.java:102)
        at com.hartwig.hmftools.amber.AmberApplication.run(AmberApplication.java:79)
        at com.hartwig.hmftools.amber.AmberApplication.main(AmberApplication.java:238)

**Comment by charlesshale** [comment]
The Amber sites VCF must only contain SNVs. In this case it has been passed an MNV (with value 'GA').

**Comment by gagank4911** [comment]
/gagan/ECLIPSE_Final$ java -Xmx16G -cp amber-3.9.jar com.hartwig.hmftools.amber.AmberApplication -reference VSI_15_S24 -reference_bam VSI_15_S24_sentieon_match_4.1_deduped.bam -tumor TCS176___S33 -tumor_bam TCS176___S33_sentieon_match_4.1_deduped.bam -output_dir /amber_out -ref_genome_version 38 -threads 8 -loci TCS176___S33_TNscope_N1_filter.vcf
06:01:14.583 INFO  [main] - AMBER version: 3.9
06:01:14.585 INFO  [main] - Loading vcf file TCS176___S33_TNscope_N1_filter.vcf
06:01:14.922 INFO  [main] - loaded 4083 baf loci
06:01:14.952 INFO  [main] - Processing 4083 potential sites in reference bam VSI_15_S24_sentieon_match_4.1_deduped.bam
06:01:14.972 INFO  [main] - 4083 loci, 2366 genome regions, min gap = 2000
Exception in thread "worker-0" java.lang.IllegalArgumentException: Invalid reference index -1
        at htsjdk.samtools.QueryInterval.<init>(QueryInterval.java:24)
        at htsjdk.samtools.SamReader$PrimitiveSamReaderToSamReaderAdapter.query(SamReader.java:538)
        at htsjdk.samtools.SamReader$PrimitiveSamReaderToSamReaderAdapter.queryOverlapping(SamReader.java:400)
        at com.hartwig.hmftools.amber.AsyncBamLociReader$BamReaderThread.run(AsyncBamLociReader.java:69)
Exception in thread "worker-1" java.lang.IllegalArgumentException: Invalid reference index -1
        at htsjdk.samtools.QueryInterval.<init>(QueryInterval.java:24)
        at htsjdk.samtools.SamReader$PrimitiveSamReaderToSamReaderAdapter.query(SamReader.java:538)
        at htsjdk.samtools.SamReader$PrimitiveSamReaderToSamReaderAdapter.queryOverlapping(SamReader.java:400)
        at com.hartwig.hmftools.amber.AsyncBamLociReader$BamReaderThread.run(AsyncBamLociReader.java:69)
Exception in thread "worker-2" java.lang.IllegalArgumentException: Invalid reference index -1
        at htsjdk.samtools.QueryInterval.<init>(QueryInterval.java:24)
        at htsjdk.samtools.SamReader$PrimitiveSamReaderToSamReaderAdapter.query(SamReader.java:538)
        at htsjdk.samtools.SamReader$PrimitiveSamReaderToSamReaderAdapter.queryOverlapping(SamReader.java:400)
        at com.hartwig.hmftools.amber.AsyncBamLociReader$BamReaderThread.run(AsyncBamLociReader.java:69)
Exception in thread "worker-3" java.lang.IllegalArgumentException: Invalid reference index -1
        at htsjdk.samtools.QueryInterval.<init>(QueryInterval.java:24)
        at htsjdk.samtools.SamReader$PrimitiveSamReaderToSamReaderAdapter.query(SamReader.java:538)
        at htsjdk.samtools.SamReader$PrimitiveSamReaderToSamReaderAdapter.queryOverlapping(SamReader.java:400)
        at com.hartwig.hmftools.amber.AsyncBamLociReader$BamReaderThread.run(AsyncBamLociReader.java:69)
Exception in thread "worker-4" java.lang.IllegalArgumentException: Invalid reference index -1
        at htsjdk.samtools.QueryInterval.<init>(QueryInterval.java:24)
        at htsjdk.samtools.SamReader$PrimitiveSamReaderToSamReaderAdapter.query(SamReader.java:538)
        at htsjdk.samtools.SamReader$PrimitiveSamReaderToSamReaderAdapter.queryOverlapping(SamReader.java:400)
        at com.hartwig.hmftools.amber.AsyncBamLociReader$BamReaderThread.run(AsyncBamLociReader.java:69)
Exception in thread "worker-5" java.lang.IllegalArgumentException: Invalid reference index -1
        at htsjdk.samtools.QueryInterval.<init>(QueryInterval.java:24)
        at htsjdk.samtools.SamReader$PrimitiveSamReaderToSamReaderAdapter.query(SamReader.java:538)
        at htsjdk.samtools.SamReader$PrimitiveSamReaderToSamReaderAdapter.queryOverlapping(SamReader.java:400)
        at com.hartwig.hmftools.amber.AsyncBamLociReader$BamReaderThread.run(AsyncBamLociReader.java:69)
Exception in thread "worker-6" java.lang.IllegalArgumentException: Invalid reference index -1
        at htsjdk.samtools.QueryInterval.<init>(QueryInterval.java:24)
        at htsjdk.samtools.SamReader$PrimitiveSamReaderToSamReaderAdapter.query(SamReader.java:538)
        at htsjdk.samtools.SamReader$PrimitiveSamReaderToSamReaderAdapter.queryOverlapping(SamReader.java:400)
        at com.hartwig.hmftools.amber.AsyncBamLociReader$BamReaderThread.run(AsyncBamLociReader.java:69)
06:01:15.332 INFO  [main] - 8 bam reader threads started
Exception in thread "worker-7" java.lang.IllegalArgumentException: Invalid reference index -1
        at htsjdk.samtools.QueryInterval.<init>(QueryInterval.java:24)
        at htsjdk.samtools.SamReader$PrimitiveSamReaderToSamReaderAdapter.query(SamReader.java:538)
        at htsjdk.samtools.SamReader$PrimitiveSamReaderToSamReaderAdapter.queryOverlapping(SamReader.java:400)
        at com.hartwig.hmftools.amber.AsyncBamLociReader$BamReaderThread.run(AsyncBamLociReader.java:69)
06:01:15.334 INFO  [main] - 8 bam reader threads finished
06:01:15.341 INFO  [main] - Median normal depth is 0 reads: filtering reads outside of 0 and 0
06:01:15.351 INFO  [main] - 0 heterozygous, 0 homozygous in reference bams
06:01:15.383 INFO  [main] - Median normal depth is 0 reads: filtering reads outside of 0 and 0
06:01:15.388 INFO  [main] - Processing 0 germline heterozygous loci in tumor bam TCS176___S33_sentieon_match_4.1_deduped.bam
06:01:15.388 INFO  [main] - Processing 0 germline homozygous loci in tumor bam TCS176___S33_sentieon_match_4.1_deduped.bam for contamination
06:01:15.390 INFO  [main] - 0 loci, 0 genome regions, min gap = 2000
WARNING: BAM index file /home/moubeen.fauzul/gagan/ECLIPSE_Final/TCS176___S33_sentieon_match_4.1_deduped.bam.bai is older than BAM /home/moubeen.fauzul/gagan/ECLIPSE_Final/TCS176___S33_sentieon_match_4.1_deduped.bam
WARNING: BAM index file /home/moubeen.fauzul/gagan/ECLIPSE_Final/TCS176___S33_sentieon_match_4.1_deduped.bam.bai is older than BAM /home/moubeen.fauzul/gagan/ECLIPSE_Final/TCS176___S33_sentieon_match_4.1_deduped.bam
WARNING: BAM index file /home/moubeen.fauzul/gagan/ECLIPSE_Final/TCS176___S33_sentieon_match_4.1_deduped.bam.bai is older than BAM /home/moubeen.fauzul/gagan/ECLIPSE_Final/TCS176___S33_sentieon_match_4.1_deduped.bam
WARNING: BAM index file /home/moubeen.fauzul/gagan/ECLIPSE_Final/TCS176___S33_sentieon_match_4.1_deduped.bam.bai is older than BAM /home/moubeen.fauzul/gagan/ECLIPSE_Final/TCS176___S33_sentieon_match_4.1_deduped.bam
WARNING: BAM index file /home/moubeen.fauzul/gagan/ECLIPSE_Final/TCS176___S33_sentieon_match_4.1_deduped.bam.bai is older than BAM /home/moubeen.fauzul/gagan/ECLIPSE_Final/TCS176___S33_sentieon_match_4.1_deduped.bam
WARNING: BAM index file /home/moubeen.fauzul/gagan/ECLIPSE_Final/TCS176___S33_sentieon_match_4.1_deduped.bam.bai is older than BAM /home/moubeen.fauzul/gagan/ECLIPSE_Final/TCS176___S33_sentieon_match_4.1_deduped.bam
WARNING: BAM index file /home/moubeen.fauzul/gagan/ECLIPSE_Final/TCS176___S33_sentieon_match_4.1_deduped.bam.bai is older than BAM /home/moubeen.fauzul/gagan/ECLIPSE_Final/TCS176___S33_sentieon_match_4.1_deduped.bam
WARNING: BAM index file /home/moubeen.fauzul/gagan/ECLIPSE_Final/TCS176___S33_sentieon_match_4.1_deduped.bam.bai is older than BAM /home/moubeen.fauzul/gagan/ECLIPSE_Final/TCS176___S33_sentieon_match_4.1_deduped.bam
06:01:15.540 INFO  [main] - 8 bam reader threads started
06:01:15.541 INFO  [main] - 8 bam reader threads finished
06:01:15.547 INFO  [main] - Median tumor depth at potential contamination sites is 0 reads
06:01:15.557 INFO  [main] - No evidence of contamination.
Exception in thread "main" java.nio.file.NoSuchFileException: /amber_out/TCS176___S33.amber.qc
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
        at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
        at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:478)
        at java.base/java.nio.file.Files.newOutputStream(Files.java:220)
        at java.base/java.nio.file.Files.write(Files.java:3565)
        at java.base/java.nio.file.Files.write(Files.java:3616)
        at com.hartwig.hmftools.common.amber.qc.AmberQCFile.write(AmberQCFile.java:36)
        at com.hartwig.hmftools.amber.AmberPersistence.persistQC(AmberPersistence.java:57)
        at com.hartwig.hmftools.amber.AmberApplication.runNormalMode(AmberApplication.java:112)
        at com.hartwig.hmftools.amber.AmberApplication.run(AmberApplication.java:79)
        at com.hartwig.hmftools.amber.AmberApplication.main(AmberApplication.java:238)
