### ISSUE TITLE
Error running PURPLE 2.31 with -somatic_vcf 

### ISSUE THREAD

**Issue by vladsaveliev** [hartwigmedical/hmftools#45]
Hi,

Thank you for the new release and the ability to annotate variants with purity and clonality, that's incredibly useful. I've got a problem though however running PURPLE during "Modelling somatic peaks" stage. The command and the output are the following:

```
java -jar purple-2.31.jar \
-amber amber \
-cobalt cobalt \
-output_dir result \
-reference PRJ180599_SFRC01073-S2N \
-tumor SFRC01073__PRJ180598_SFRC01073-S2T \
-threads 28 \
-gc_profile GC_profile.1000bp.cnp \
-structural_vcf manta.vcf \
-somatic_vcf somatic.vcf \
-circos circos \
-ref_genome hg38.fa

16:18:17 - PURPLE version: 2.31
16:18:17 - Reference Sample: PRJ180599_SFRC01073-S2N, Tumor Sample: SFRC01073__PRJ180598_SFRC01073-S2T
16:18:17 - Output Directory: chr21/purple
16:18:17 - Using ref genome: HG38
16:18:18 - Reading cobalt ratios from chr21/cobalt/SFRC01073__PRJ180598_SFRC01073-S2T.cobalt.ratio.tsv
16:18:18 - Reading cobalt reference segments from chr21/cobalt/PRJ180599_SFRC01073-S2N.cobalt.ratio.pcf
16:18:18 - Reading cobalt tumor segments from chr21/cobalt/SFRC01073__PRJ180598_SFRC01073-S2T.cobalt.ratio.pcf
16:18:18 - Reading amber bafs from chr21/amber/SFRC01073__PRJ180598_SFRC01073-S2T.amber.baf.tsv
16:18:18 - Reading amber pcfs from chr21/amber/SFRC01073__PRJ180598_SFRC01073-S2T.amber.baf.pcf
16:18:18 - Average amber tumor depth is 100 reads implying an ambiguous BAF of 0.544
16:18:18 - Sample gender is male
16:18:18 - Loading structural variants from chr21/manta.vcf
16:18:18 - Loading somatic variants from chr21/somatic.vcf
16:18:19 - Applying segmentation
16:18:19 - Merging reference and tumor ratio break points
16:18:19 - Reading GC Profiles from /g/data3/gx8/extras/umccrise_2019_Mar/genomes/hg38/hmf/GC_profile.1000bp.cnp
16:18:22 - Fitting purity
16:18:22 - Calculating copy number
16:18:22 - Generating QC Stats
16:18:22 - Modelling somatic peaks
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 201
        at com.hartwig.hmftools.common.variant.clonality.PeakModelFactory.modelPeakHistogram(PeakModelFactory.java:178)
        at com.hartwig.hmftools.common.variant.clonality.PeakModelFactory.model(PeakModelFactory.java:60)
        at com.hartwig.hmftools.purple.PurityPloidyEstimateApplication.modelSomaticPeaks(PurityPloidyEstimateApplication.java:388)
        at com.hartwig.hmftools.purple.PurityPloidyEstimateApplication.<init>(PurityPloidyEstimateApplication.java:192)
        at com.hartwig.hmftools.purple.PurityPloidyEstimateApplication.main(PurityPloidyEstimateApplication.java:96)
```

It works well without the `-somatic_vcf` parameter.

Attaching the inputs I'm using:
[purple.tar.gz](https://github.com/hartwigmedical/hmftools/files/3450145/purple.tar.gz)

I narrowed down the somatic VCF to 1 variant for simplicity. The VCF sample name seem to be matching `-tumor` option. Did I miss something else?

Would really appreciate help
Vlad

**Comment by jonbaber** [comment]
Hi Vlad, 

Thanks for providing everything to reproduce the bug. I have diagnosed the issue and will make a release tomorrow if not tonight.

Cheers, Jon

**Comment by vladsaveliev** [comment]
Thanks for a quick response - looking forward to an update!

**Comment by jonbaber** [comment]
Version [2.32](https://github.com/hartwigmedical/hmftools/releases/tag/purple-v2-32) is now available with a fix.

**Comment by vladsaveliev** [comment]
Thank you so much!

**Comment by jonbaber** [comment]
You're welcome :)
