### ISSUE TITLE
i gave SNV as input in vcf file but getting some error amber run  Invalid reference index -1

### ISSUE THREAD

**Issue by gagank4911** [hartwigmedical/hmftools#450]
/gagan/ECLIPSE_Final$ java -Xmx16G -cp amber-3.9.jar com.hartwig.hmftools.amber.AmberApplication -reference VSI_15_S24 -reference_bam VSI_15_S24_sentieon_match_4.1_deduped.bam -tumor TCS176___S33 -tumor_bam TCS176___S33_sentieon_match_4.1_deduped.bam -output_dir /amber_out -ref_genome_version 38 -threads 8 -loci TCS176___S33_TNscope_N1_filter.vcf
06:01:14.583 INFO  [main] - AMBER version: 3.9
06:01:14.585 INFO  [main] - Loading vcf file TCS176___S33_TNscope_N1_filter.vcf
06:01:14.922 INFO  [main] - loaded 4083 baf loci
06:01:14.952 INFO  [main] - Processing 4083 potential sites in reference bam VSI_15_S24_sentieon_match_4.1_deduped.bam
06:01:14.972 INFO  [main] - 4083 loci, 2366 genome regions, min gap = 2000
Exception in thread "worker-0" java.lang.IllegalArgumentException: Invalid reference index -1
        at htsjdk.samtools.QueryInterval.<init>(QueryInterval.java:24)
        at htsjdk.samtools.SamReader$PrimitiveSamReaderToSamReaderAdapter.query(SamReader.java:538)
        at htsjdk.samtools.SamReader$PrimitiveSamReaderToSamReaderAdapter.queryOverlapping(SamReader.java:400)
        at com.hartwig.hmftools.amber.AsyncBamLociReader$BamReaderThread.run(AsyncBamLociReader.java:69)
Exception in thread "worker-1" java.lang.IllegalArgumentException: Invalid reference index -1
        at htsjdk.samtools.QueryInterval.<init>(QueryInterval.java:24)
        at htsjdk.samtools.SamReader$PrimitiveSamReaderToSamReaderAdapter.query(SamReader.java:538)
        at htsjdk.samtools.SamReader$PrimitiveSamReaderToSamReaderAdapter.queryOverlapping(SamReader.java:400)
        at com.hartwig.hmftools.amber.AsyncBamLociReader$BamReaderThread.run(AsyncBamLociReader.java:69)
Exception in thread "worker-2" java.lang.IllegalArgumentException: Invalid reference index -1
        at htsjdk.samtools.QueryInterval.<init>(QueryInterval.java:24)
        at htsjdk.samtools.SamReader$PrimitiveSamReaderToSamReaderAdapter.query(SamReader.java:538)
        at htsjdk.samtools.SamReader$PrimitiveSamReaderToSamReaderAdapter.queryOverlapping(SamReader.java:400)
        at com.hartwig.hmftools.amber.AsyncBamLociReader$BamReaderThread.run(AsyncBamLociReader.java:69)
Exception in thread "worker-3" java.lang.IllegalArgumentException: Invalid reference index -1
        at htsjdk.samtools.QueryInterval.<init>(QueryInterval.java:24)
        at htsjdk.samtools.SamReader$PrimitiveSamReaderToSamReaderAdapter.query(SamReader.java:538)
        at htsjdk.samtools.SamReader$PrimitiveSamReaderToSamReaderAdapter.queryOverlapping(SamReader.java:400)
        at com.hartwig.hmftools.amber.AsyncBamLociReader$BamReaderThread.run(AsyncBamLociReader.java:69)
Exception in thread "worker-4" java.lang.IllegalArgumentException: Invalid reference index -1
        at htsjdk.samtools.QueryInterval.<init>(QueryInterval.java:24)
        at htsjdk.samtools.SamReader$PrimitiveSamReaderToSamReaderAdapter.query(SamReader.java:538)
        at htsjdk.samtools.SamReader$PrimitiveSamReaderToSamReaderAdapter.queryOverlapping(SamReader.java:400)
        at com.hartwig.hmftools.amber.AsyncBamLociReader$BamReaderThread.run(AsyncBamLociReader.java:69)
Exception in thread "worker-5" java.lang.IllegalArgumentException: Invalid reference index -1
        at htsjdk.samtools.QueryInterval.<init>(QueryInterval.java:24)
        at htsjdk.samtools.SamReader$PrimitiveSamReaderToSamReaderAdapter.query(SamReader.java:538)
        at htsjdk.samtools.SamReader$PrimitiveSamReaderToSamReaderAdapter.queryOverlapping(SamReader.java:400)
        at com.hartwig.hmftools.amber.AsyncBamLociReader$BamReaderThread.run(AsyncBamLociReader.java:69)
Exception in thread "worker-6" java.lang.IllegalArgumentException: Invalid reference index -1
        at htsjdk.samtools.QueryInterval.<init>(QueryInterval.java:24)
        at htsjdk.samtools.SamReader$PrimitiveSamReaderToSamReaderAdapter.query(SamReader.java:538)
        at htsjdk.samtools.SamReader$PrimitiveSamReaderToSamReaderAdapter.queryOverlapping(SamReader.java:400)
        at com.hartwig.hmftools.amber.AsyncBamLociReader$BamReaderThread.run(AsyncBamLociReader.java:69)
06:01:15.332 INFO  [main] - 8 bam reader threads started
Exception in thread "worker-7" java.lang.IllegalArgumentException: Invalid reference index -1
        at htsjdk.samtools.QueryInterval.<init>(QueryInterval.java:24)
        at htsjdk.samtools.SamReader$PrimitiveSamReaderToSamReaderAdapter.query(SamReader.java:538)
        at htsjdk.samtools.SamReader$PrimitiveSamReaderToSamReaderAdapter.queryOverlapping(SamReader.java:400)
        at com.hartwig.hmftools.amber.AsyncBamLociReader$BamReaderThread.run(AsyncBamLociReader.java:69)
06:01:15.334 INFO  [main] - 8 bam reader threads finished
06:01:15.341 INFO  [main] - Median normal depth is 0 reads: filtering reads outside of 0 and 0
06:01:15.351 INFO  [main] - 0 heterozygous, 0 homozygous in reference bams
06:01:15.383 INFO  [main] - Median normal depth is 0 reads: filtering reads outside of 0 and 0
06:01:15.388 INFO  [main] - Processing 0 germline heterozygous loci in tumor bam TCS176___S33_sentieon_match_4.1_deduped.bam
06:01:15.388 INFO  [main] - Processing 0 germline homozygous loci in tumor bam TCS176___S33_sentieon_match_4.1_deduped.bam for contamination
06:01:15.390 INFO  [main] - 0 loci, 0 genome regions, min gap = 2000
WARNING: BAM index file /home/moubeen.fauzul/gagan/ECLIPSE_Final/TCS176___S33_sentieon_match_4.1_deduped.bam.bai is older than BAM /home/moubeen.fauzul/gagan/ECLIPSE_Final/TCS176___S33_sentieon_match_4.1_deduped.bam
WARNING: BAM index file /home/moubeen.fauzul/gagan/ECLIPSE_Final/TCS176___S33_sentieon_match_4.1_deduped.bam.bai is older than BAM /home/moubeen.fauzul/gagan/ECLIPSE_Final/TCS176___S33_sentieon_match_4.1_deduped.bam
WARNING: BAM index file /home/moubeen.fauzul/gagan/ECLIPSE_Final/TCS176___S33_sentieon_match_4.1_deduped.bam.bai is older than BAM /home/moubeen.fauzul/gagan/ECLIPSE_Final/TCS176___S33_sentieon_match_4.1_deduped.bam
WARNING: BAM index file /home/moubeen.fauzul/gagan/ECLIPSE_Final/TCS176___S33_sentieon_match_4.1_deduped.bam.bai is older than BAM /home/moubeen.fauzul/gagan/ECLIPSE_Final/TCS176___S33_sentieon_match_4.1_deduped.bam
WARNING: BAM index file /home/moubeen.fauzul/gagan/ECLIPSE_Final/TCS176___S33_sentieon_match_4.1_deduped.bam.bai is older than BAM /home/moubeen.fauzul/gagan/ECLIPSE_Final/TCS176___S33_sentieon_match_4.1_deduped.bam
WARNING: BAM index file /home/moubeen.fauzul/gagan/ECLIPSE_Final/TCS176___S33_sentieon_match_4.1_deduped.bam.bai is older than BAM /home/moubeen.fauzul/gagan/ECLIPSE_Final/TCS176___S33_sentieon_match_4.1_deduped.bam
WARNING: BAM index file /home/moubeen.fauzul/gagan/ECLIPSE_Final/TCS176___S33_sentieon_match_4.1_deduped.bam.bai is older than BAM /home/moubeen.fauzul/gagan/ECLIPSE_Final/TCS176___S33_sentieon_match_4.1_deduped.bam
WARNING: BAM index file /home/moubeen.fauzul/gagan/ECLIPSE_Final/TCS176___S33_sentieon_match_4.1_deduped.bam.bai is older than BAM /home/moubeen.fauzul/gagan/ECLIPSE_Final/TCS176___S33_sentieon_match_4.1_deduped.bam
06:01:15.540 INFO  [main] - 8 bam reader threads started
06:01:15.541 INFO  [main] - 8 bam reader threads finished
06:01:15.547 INFO  [main] - Median tumor depth at potential contamination sites is 0 reads
06:01:15.557 INFO  [main] - No evidence of contamination.
Exception in thread "main" java.nio.file.NoSuchFileException: /amber_out/TCS176___S33.amber.qc
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
        at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
        at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:478)
        at java.base/java.nio.file.Files.newOutputStream(Files.java:220)
        at java.base/java.nio.file.Files.write(Files.java:3565)
        at java.base/java.nio.file.Files.write(Files.java:3616)
        at com.hartwig.hmftools.common.amber.qc.AmberQCFile.write(AmberQCFile.java:36)
        at com.hartwig.hmftools.amber.AmberPersistence.persistQC(AmberPersistence.java:57)
        at com.hartwig.hmftools.amber.AmberApplication.runNormalMode(AmberApplication.java:112)
        at com.hartwig.hmftools.amber.AmberApplication.run(AmberApplication.java:79)
        at com.hartwig.hmftools.amber.AmberApplication.main(AmberApplication.java:238)

**Comment by hongwingl** [comment]
Hi,
Where do get the loci file from? In #439 you seemed to have it working? It could be that the chromosome naming in the loci input file is different from the bam file. That could be why it cannot find the chromosomes.

**Comment by gagank4911** [comment]
##fileformat=VCFv4.2
##FILTER=<ID=PASS,Description=""Accept as a confident somatic mutation"">
##FILTER=<ID=alt_allele_in_normal,Description=""Evidence seen in the normal sample"">
##FILTER=<ID=clustered_events,Description=""Clustered events observed in the tumor"">
##FILTER=<ID=germline_risk,Description=""Evidence indicates this site is germline, not somatic"">                                   >##FILTER=<ID=homologous_mapping_event,Description=""More than three events were observed in the tumor"">                            >##FILTER=<ID=multi_event_alt_allele_in_normal,Description=""Multiple events observed in tumor and normal"">                         >##FILTER=<ID=panel_of_normals,Description=""Seen in at least 2 samples in the panel of normals"">                                   >##FILTER=<ID=str_contraction,Description=""Site filtered due to contraction of short tandem repeat region"">                        >##FILTER=<ID=t_lod_fstar,Description=""Tumor does not meet likelihood threshold"">
##FILTER=<ID=triallelic_site,Description=""Site filtered because more than two alt alleles pass tumor LOD"">                        >##FILTER=<ID=low_t_alt_frac,Description=""Site filtered due to low alt allele fraction"">                                           >##FORMAT=<ID=AD,Number=R,Type=Integer,Description=""Allelic depths for the ref and alt alleles in the order listed"">               >##FORMAT=<ID=AF,Number=1,Type=Float,Description=""Allele fraction of the event in the tumor"">                                      >##FORMAT=<ID=AFDP,Number=1,Type=Integer,Description=""Read depth to calculate AF"">
##FORMAT=<ID=AFDPLOWMQ,Number=1,Type=Integer,Description=""Read depth to calculate AF with low mapq reads""> 

#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO
1       2556603 .       G       C       51.83   PASS    .
1       2556714 rs4870  A       G       3606.67 PASS    .
1       2559766 rs2234161       C       T       2398.22 PASS    .
1       8004518 rs72634228      A       G       3637.67 PASS    .
1       8013700 .       C       G       31.46   PASS    .
1       8013906 .       A       T       8.04    PASS    .
1       8015405 .       T       A       57.37   PASS    .
1       9710597 .       G       A       123.76  PASS    .
1       9720367 rs116150871     G       A       1660.04 PASS    .
1       9720678 .       T       A       20.88   PASS    .
1       9721999 .       G       T       34.74   PASS    .
1       9722009 .       A       T       32.13   PASS    .
1       9722699 .       C       A       75.76   PASS    .
