### ISSUE TITLE
SAGE  run error

### ISSUE THREAD

**Issue by xdgene** [hartwigmedical/hmftools#456]
when i run sage with command：
java -jar sage_v3.2.5.jar  -reference Normal -reference_bam COLO829R.bam -tumor tumor -tumor_bam COLO829T.bam -ref_genome_version 37 -ref_genome hg19.fasta -hotspots $PWD/variants/KnownHotspots.somatic.37.vcf.gz -panel_bed 2021.bed -panel_only  -panel_min_tumor_vaf 0.01  -ensembl_data_dir $PWD/common/ensembl_data  -out $PWD/2021.sage.vcf.gz

I got error：
17:23:28.832 [INFO ] Sage version: 3.2.5
17:23:28.840 [INFO ] Using non default panel_only flag
17:23:31.049 [INFO ] read 7964 panel entries from bed file: 2021.bed
17:23:31.303 [INFO ] read 9452 hotspots from vcf: KnownHotspots.somatic.37.vcf.gz
Exception in thread "main" java.lang.NullPointerException
	at com.hartwig.hmftools.sage.vcf.VariantVCF.<init>(VariantVCF.java:104)
	at com.hartwig.hmftools.sage.vcf.VcfWriter.<init>(VcfWriter.java:22)
	at com.hartwig.hmftools.sage.SageApplication.<init>(SageApplication.java:66)
	at com.hartwig.hmftools.sage.SageApplication.main(SageApplication.java:148)

How can i fix this，all files are fine，i dont know what happen with the (VariantVCF.java:104) ：mConsumer = enrichment;

**Comment by xdgene** [comment]
its about ref genome
