### ISSUE TITLE
 Modelling Somatic Peaks Error

### ISSUE THREAD

**Issue by DarioS** [hartwigmedical/hmftools#46]
I tried PURPLE version 2.31 a few minutes ago for the first time and there was an error.

```
16:47:23 - Modelling somatic peaks
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 201
        at com.hartwig.hmftools.common.variant.clonality.PeakModelFactory.modelPeakHistogram(PeakModelFactory.java:178)
        at com.hartwig.hmftools.common.variant.clonality.PeakModelFactory.model(PeakModelFactory.java:60)
        at com.hartwig.hmftools.purple.PurityPloidyEstimateApplication.modelSomaticPeaks(PurityPloidyEstimateApplication.java:388)
        at com.hartwig.hmftools.purple.PurityPloidyEstimateApplication.<init>(PurityPloidyEstimateApplication.java:192)
        at com.hartwig.hmftools.purple.PurityPloidyEstimateApplication.main(PurityPloidyEstimateApplication.java:96)

```

I removed `-ref_genome` and reran the command with version 2.29 and it worked fine. In case it matters, I still have AMBER version 2.1 and COBALT version 1.5 installed because I'm not aware of any version dependencies between the tools. Also, the README file contains a section titled Example Usage but it has not been updated to show the newly mandatory parameter `-ref_genome`.

**Comment by jonbaber** [comment]
Thanks Dario. 

Vlad just opened a similar ticket so I will close this one. I will release a new version either tonight or tomorrow. 

Cheers, Jon
