### ISSUE TITLE
PURPLE Error for TCGA VCF File

### ISSUE THREAD

**Issue by DarioS** [hartwigmedical/hmftools#50]
I have downloaded a few TCGA whole genome sequencing normal and cancer sample pairs. I find that the analysis works if I don't provide a VCF by specifying it using `-somatic_vcf` but it fails if it is provided. The BAM files and VCF files are controlled access, so I can't share them for troubleshooting.

```
21:11:49 - Enriching somatic variants
Exception in thread "main" java.lang.NullPointerException
        at com.hartwig.hmftools.common.variant.enrich.SomaticRefContextEnrichment.relativePositionAndRef(SomaticRefContextEnrichment.java:115)
        at com.hartwig.hmftools.common.variant.enrich.SomaticRefContextEnrichment.accept(SomaticRefContextEnrichment.java:57)
        at com.hartwig.hmftools.common.variant.enrich.VariantContextEnrichmentPurple.accept(VariantContextEnrichmentPurple.java:54)
        at com.hartwig.hmftools.purple.somatic.SomaticVCF.write(SomaticVCF.java:88)
        at com.hartwig.hmftools.purple.PurityPloidyEstimateApplication.<init>(PurityPloidyEstimateApplication.java:196)
        at com.hartwig.hmftools.purple.PurityPloidyEstimateApplication.main(PurityPloidyEstimateApplication.java:96)

```

**Comment by jonbaber** [comment]
Hi Dario, 

That particular line of code is trying to query the length of the contig of the somatic variant from the supplied ref genome. Perhaps you are trying to query a contig that isn't available?

Try filtering the somatic VCF to include chromosomes 1-22,X,Y and try again.

If this works let me know and I will update the code to handle this more gracefully.

Jon

**Comment by DarioS** [comment]
Ah, yes. I got the FASTA file from NCBI named human_g1k_v37 and it has different a chromosome name style

```
@SQ     SN:1
@SQ     SN:2
@SQ     SN:3
```

than the VCF file, which uses chr1, chr2, chr3. An exception catcher for this would be nice to have. Perhaps it can show the first three chromosome names in each file type to make it obvious what the problem is.
