### ISSUE TITLE
TEAL error: Exception in thread "main" java.lang.IllegalArgumentException: Comparison method violates its general contract!

### ISSUE THREAD

**Issue by Ansepil** [hartwigmedical/hmftools#518]
Hello, I'm currently experiencing an issue while using TEAL.
I'm using TEAL v1.2.1, and here are some commands and partial outputs. (I've replaced the actual parameter values with placeholders in {}.)

Is there anyone who might be familiar with the cause of this issue or a potential solution? Any advice would be appreciated.

Below are the commands and partial output:
```
java -Xmx16G -cp /opt/hmftools/teal/teal_v1.2.1.jar com.hartwig.hmftools.teal.TealApplication \
   -reference {reference} -reference_bam {reference_bam} \
   -tumor {tumor} -tumor_bam {tumor_bam}, \
   -purple /scratch/test_output/hmftools/PURPLE \
   -cobalt /scratch/test_output/hmftools/COBALT \
   -reference_wgs_metrics /scratch/testdata/Normal_metrics/CollectWgsMetrics.txt \
   -tumor_wgs_metrics /scratch/testdata/Tumor_metrics/CollectWgsMetrics.txt \
   -output_dir /scratch/test_output/teal_v1.2.1/picard \
   -threads 10
```

```
04:06:59.320 INFO  [main] - creating telbam files
04:06:59.333 INFO  [main] - params: TelbamParams(bamFile={reference_bam}, refGenomeFile=null, telbamFile={telbam.bam}, tsvFile={tel.tsv.gz}, threadCount=10, specificChromosomes=[])
04:06:59.335 INFO  [main] - processing bam: {reference_bam}
04:07:00.497 INFO  [worker-0] - processed 20 unmapped reads
04:07:30.310 INFO  [worker-6] - processed region(2:200,000,000-243,199,373) read count(1316)
04:07:40.764 INFO  [worker-3] - processed region(1:200,000,000-249,250,621) read count(2006)
04:07:52.710 INFO  [worker-2] - processed region(1:100,000,000-199,999,999) read count(706)
04:08:02.405 INFO  [worker-8] - processed region(3:100,000,000-198,022,430) read count(1532)
04:08:02.828 INFO  [worker-7] - processed region(3:0-99,999,999) read count(724)
04:08:02.852 INFO  [worker-0] - processed region(4:0-99,999,999) read count(1826)
04:08:03.597 INFO  [worker-5] - processed region(2:100,000,000-199,999,999) read count(1376)
04:08:05.292 INFO  [worker-1] - processed region(1:0-99,999,999) read count(3404)
04:08:05.772 INFO  [worker-4] - processed region(2:0-99,999,999) read count(3382)
04:08:24.564 INFO  [worker-6] - processed region(4:100,000,000-191,154,276) read count(2700)
04:08:33.036 INFO  [worker-4] - processed region(8:100,000,000-146,364,022) read count(591)
04:08:37.949 INFO  [worker-3] - processed region(5:0-99,999,999) read count(25683)
04:08:38.139 INFO  [worker-5] - processed region(7:100,000,000-159,138,663) read count(844)
04:08:40.398 INFO  [worker-2] - processed region(5:100,000,000-180,915,260) read count(728)
04:08:44.061 INFO  [worker-7] - processed region(6:100,000,000-171,115,067) read count(694)
04:08:57.722 INFO  [worker-4] - processed region(9:100,000,000-141,213,431) read count(1230)
04:08:59.293 INFO  [worker-5] - processed region(10:100,000,000-135,534,747) read count(1154)
04:08:59.791 INFO  [worker-8] - processed region(6:0-99,999,999) read count(1090)
04:09:00.161 INFO  [worker-0] - processed region(7:0-99,999,999) read count(1967)
04:09:04.064 INFO  [worker-1] - processed region(8:0-99,999,999) read count(870)
04:09:04.746 INFO  [worker-7] - processed region(11:100,000,000-135,006,516) read count(612)
04:09:11.011 INFO  [worker-6] - processed region(9:0-99,999,999) read count(1303)
04:09:19.367 INFO  [worker-5] - processed region(12:100,000,000-133,851,895) read count(1423)
04:09:34.049 INFO  [worker-3] - processed region(10:0-99,999,999) read count(1269)
04:09:37.052 INFO  [worker-2] - processed region(11:0-99,999,999) read count(1374)
04:09:52.426 INFO  [worker-0] - processed region(14:0-107,349,540) read count(829)
04:09:53.199 INFO  [worker-1] - processed region(15:0-102,531,392) read count(1641)
04:09:54.796 INFO  [worker-4] - processed region(12:0-99,999,999) read count(2250)
04:09:55.528 INFO  [worker-8] - processed region(13:0-115,169,878) read count(1355)
04:09:58.351 INFO  [worker-6] - processed region(17:0-81,195,210) read count(880)
04:09:58.913 INFO  [worker-6] - processed region(Y:0-59,373,566) read count(65)
04:09:59.081 INFO  [worker-6] - processed region(MT:0-16,569) read count(0)
04:09:59.084 INFO  [worker-6] - processed region(GL000207.1:0-4,262) read count(0)
04:09:59.830 INFO  [worker-7] - processed region(16:0-90,354,753) read count(2448)
04:09:59.857 INFO  [worker-7] - processed region(GL000229.1:0-19,913) read count(0)
04:09:59.889 INFO  [worker-7] - processed region(GL000231.1:0-27,386) read count(0)
04:09:59.897 INFO  [worker-7] - processed region(GL000210.1:0-27,682) read count(0)
04:09:59.956 INFO  [worker-7] - processed region(GL000239.1:0-33,824) read count(0)
04:09:59.991 INFO  [worker-7] - processed region(GL000235.1:0-34,474) read count(0)
04:10:00.003 INFO  [worker-7] - processed region(GL000201.1:0-36,148) read count(0)
04:10:00.022 INFO  [worker-7] - processed region(GL000247.1:0-36,422) read count(0)
04:10:00.054 INFO  [worker-7] - processed region(GL000245.1:0-36,651) read count(0)
04:10:00.065 INFO  [worker-7] - processed region(GL000197.1:0-37,175) read count(0)
04:10:00.079 INFO  [worker-7] - processed region(GL000203.1:0-37,498) read count(0)
04:10:00.090 INFO  [worker-7] - processed region(GL000246.1:0-38,154) read count(0)
04:10:00.102 INFO  [worker-7] - processed region(GL000249.1:0-38,502) read count(0)
04:10:00.115 INFO  [worker-7] - processed region(GL000196.1:0-38,914) read count(0)
04:10:00.129 INFO  [worker-7] - processed region(GL000248.1:0-39,786) read count(0)
04:10:00.144 INFO  [worker-7] - processed region(GL000244.1:0-39,929) read count(0)
04:10:00.156 INFO  [worker-7] - processed region(GL000238.1:0-39,939) read count(0)
04:10:00.178 INFO  [worker-7] - processed region(GL000202.1:0-40,103) read count(0)
04:10:00.228 INFO  [worker-7] - processed region(GL000234.1:0-40,531) read count(0)
04:10:00.276 INFO  [worker-7] - processed region(GL000232.1:0-40,652) read count(0)
04:10:00.289 INFO  [worker-7] - processed region(GL000206.1:0-41,001) read count(0)
04:10:00.313 INFO  [worker-7] - processed region(GL000240.1:0-41,933) read count(0)
04:10:00.325 INFO  [worker-7] - processed region(GL000236.1:0-41,934) read count(0)
04:10:00.384 INFO  [worker-7] - processed region(GL000241.1:0-42,152) read count(0)
04:10:00.421 INFO  [worker-7] - processed region(GL000243.1:0-43,341) read count(135)
04:10:00.431 INFO  [worker-7] - processed region(GL000242.1:0-43,523) read count(0)
04:10:00.459 INFO  [worker-7] - processed region(GL000230.1:0-43,691) read count(0)
04:10:00.565 INFO  [worker-7] - processed region(GL000237.1:0-45,867) read count(0)
04:10:00.596 INFO  [worker-7] - processed region(GL000233.1:0-45,941) read count(0)
04:10:00.636 INFO  [worker-7] - processed region(GL000204.1:0-81,310) read count(0)
04:10:00.700 INFO  [worker-7] - processed region(GL000198.1:0-90,085) read count(0)
04:10:00.978 INFO  [worker-7] - processed region(GL000208.1:0-92,689) read count(0)
04:10:01.017 INFO  [worker-7] - processed region(GL000191.1:0-106,433) read count(0)
04:10:01.053 INFO  [worker-7] - processed region(GL000227.1:0-128,374) read count(287)
04:10:01.189 INFO  [worker-7] - processed region(GL000228.1:0-129,120) read count(77)
04:10:01.657 INFO  [worker-6] - processed region(GL000226.1:0-15,008) read count(0)
04:10:01.748 INFO  [worker-7] - processed region(GL000214.1:0-137,718) read count(441)
04:10:01.776 INFO  [worker-7] - processed region(GL000209.1:0-159,169) read count(0)
04:10:01.827 INFO  [worker-6] - processed region(GL000221.1:0-155,397) read count(0)
04:10:01.982 INFO  [worker-7] - processed region(GL000218.1:0-161,147) read count(0)
04:10:02.043 INFO  [worker-7] - processed region(GL000213.1:0-164,239) read count(0)
04:10:02.144 INFO  [worker-7] - processed region(GL000211.1:0-166,566) read count(59)
04:10:03.127 INFO  [worker-5] - processed region(18:0-78,077,248) read count(1735)
04:10:03.271 INFO  [worker-5] - processed region(GL000217.1:0-172,149) read count(0)
04:10:03.432 INFO  [worker-7] - processed region(GL000199.1:0-169,874) read count(0)
04:10:03.470 INFO  [worker-5] - processed region(GL000216.1:0-172,294) read count(0)
04:10:03.473 INFO  [worker-7] - processed region(GL000215.1:0-172,545) read count(0)
04:10:03.515 INFO  [worker-7] - processed region(GL000219.1:0-179,198) read count(0)
04:10:03.806 INFO  [worker-5] - processed region(GL000205.1:0-174,588) read count(0)
04:10:03.864 INFO  [worker-5] - processed region(GL000223.1:0-180,455) read count(0)
04:10:04.091 INFO  [worker-7] - processed region(GL000224.1:0-179,693) read count(0)
04:10:04.252 INFO  [worker-5] - processed region(GL000195.1:0-182,896) read count(0)
04:10:04.297 INFO  [worker-7] - processed region(GL000212.1:0-186,858) read count(0)
04:10:04.326 INFO  [worker-5] - processed region(GL000222.1:0-186,861) read count(0)
04:10:04.328 INFO  [worker-7] - processed region(GL000200.1:0-187,035) read count(0)
04:10:04.553 INFO  [worker-7] - processed region(GL000194.1:0-191,469) read count(185)
04:10:04.626 INFO  [worker-5] - processed region(GL000193.1:0-189,789) read count(0)
04:10:04.883 INFO  [worker-7] - processed region(GL000225.1:0-211,173) read count(0)
04:10:04.886 INFO  [worker-7] - processed region(NC_007605:0-171,823) read count(0)
04:10:04.947 INFO  [worker-5] - processed region(GL000192.1:0-547,496) read count(2)
04:10:07.415 INFO  [worker-6] - processed region(GL000220.1:0-161,802) read count(1)
04:10:08.813 INFO  [worker-3] - processed region(19:0-59,128,983) read count(1538)
04:10:12.886 INFO  [worker-2] - processed region(20:0-63,025,520) read count(1091)
04:10:15.004 INFO  [worker-1] - processed region(22:0-51,304,566) read count(862)
04:10:15.817 INFO  [worker-0] - processed region(21:0-48,129,895) read count(1167)
04:10:29.191 INFO  [worker-8] - processed region(X:100,000,000-155,270,560) read count(7024)
04:10:58.309 INFO  [worker-4] - processed region(X:0-99,999,999) read count(1043)
04:11:34.290 INFO  [worker-7] - processed region(hs37d5:0-35,477,943) read count(4117)
04:11:34.291 INFO  [main] - 102 bam reader tasks finished
04:11:34.291 INFO  [main] - writer thread finished
04:11:34.291 INFO  [main] - initial BAM file processing complete
Exception in thread "main" java.lang.IllegalArgumentException: Comparison method violates its general contract!
        at java.base/java.util.ComparableTimSort.mergeHi(ComparableTimSort.java:870)
        at java.base/java.util.ComparableTimSort.mergeAt(ComparableTimSort.java:487)
        at java.base/java.util.ComparableTimSort.mergeCollapse(ComparableTimSort.java:413)
        at java.base/java.util.ComparableTimSort.sort(ComparableTimSort.java:213)
        at java.base/java.util.Arrays.sort(Arrays.java:1315)
        at java.base/java.util.Arrays.sort(Arrays.java:1509)
        at java.base/java.util.ArrayList.sort(ArrayList.java:1750)
        at java.base/java.util.Collections.sort(Collections.java:145)
        at kotlin.collections.CollectionsKt__MutableCollectionsJVMKt.sort(MutableCollectionsJVM.kt:31)
        at com.hartwig.hmftools.teal.telbam.BamProcessor.getMissingReadRegions(BamProcessor.kt:200)
        at com.hartwig.hmftools.teal.telbam.BamProcessor.processBam(BamProcessor.kt:79)
        at com.hartwig.hmftools.teal.telbam.TelbamApp.processBam(TelbamApp.kt:69)
        at com.hartwig.hmftools.teal.TealApplication$StandaloneMode.run(TealApplication.kt:66)
        at com.hartwig.hmftools.teal.TealApplication$PipelineMode.run(TealApplication.kt:191)
        at com.hartwig.hmftools.teal.TealApplication$Companion.main(TealApplication.kt:286)
        at com.hartwig.hmftools.teal.TealApplication.main(TealApplication.kt)
```

**Comment by hongwingl** [comment]
Hi
Thank you for your bug report. I have released a bug fix: [teal-v1.2.2](https://github.com/hartwigmedical/hmftools/releases/tag/teal-v1.2.2) 
It is due to a bug in the compareTo function.

**Comment by Ansepil** [comment]
Thank you for the quick response. I just tested it with the new version (v1.2.2), and it ran smoothly without any errors.

**Comment by Ansepil** [comment]
@hongwingl
Hello, I have one more question. Is it possible to run Teal in tumor-only mode?

The description in the link(https://github.com/hartwigmedical/hmftools/tree/master/teal) mentions that tumor-only mode is also possible, but there are only examples for tumor-germline pair and germline-only mode.
```
TEAL measures telomere content, and estimates telomeric length based on WGS BAM input and can be run on a germline only, tumor only or tumor-normal pair.
```

If tumor-only mode is possible, would the command be as follows?
```
java -Xmx16G -cp teal.jar com.hartwig.hmftools.teal.TealApplication \
   -tumor COLO829T -tumor_bam COLO829T.bam \
   -purple /path/to/COLO829/purple \
   -cobalt /path/to/COLO829/cobalt \
   -tumor_wgs_metrics /path/to/COLO829/bam_metrics/COLO829T_WGSMetrics.txt \
   -output_dir /path/to/COLO829/teal \
   -threads 28
```

Thank you for providing the tool.

**Comment by p-priestley** [comment]
I would suggest to just run as germline only.   This will return the average length of the tumor-normal mix.   If the purity is high this will converge to approximately the tumor length.  

The tumor length can be estimated from the tumor-mix length with the following formula.

<img width="787" alt="image" src="https://github.com/hartwigmedical/hmftools/assets/18154939/15daa878-b9a1-44d8-8414-b760d019f820">

But without the ref length we don't really have an estimate, unless you have an orthogonal estimate of the ref length

**Comment by Ansepil** [comment]
Thank you for the response.
In cases where only tumor samples are available, I will proceed to run it in germline-only mode.
Your assistance has been greatly appreciated. Thank you.
