### ISSUE TITLE
NullPointerException using teal

### ISSUE THREAD

**Issue by elicj01** [hartwigmedical/hmftools#533]
Hello,

I'm using the teal tool, germline only mode standalone in some WGS bam files, but when it tries to process the telbam to get the telomere length I get a null pointer exception. Would appreciate the help with this.

```
Exception in thread "main" java.lang.NullPointerException
        at com.hartwig.hmftools.teal.tellength.TelLengthApp.calcTelomereLength(TelLengthApp.kt:81)
        at com.hartwig.hmftools.teal.TealApplication$StandaloneMode.run(TealApplication.kt:93)
        at com.hartwig.hmftools.teal.TealApplication$Companion.main(TealApplication.kt:270)
        at com.hartwig.hmftools.teal.TealApplication.main(TealApplication.kt)
```

Thank you!!

**Comment by p-priestley** [comment]
Could you provide the command you used please?

**Comment by elicj01** [comment]
> Could you provide the command you used please?

```
java -Xmx16G -cp ../teal_v1.2.2.jar com.hartwig.hmftools.teal.TealApplication \
   -reference TCGA-SY-A9G0-10A-01D-A91L-36.WholeGenome.RP-1657 -reference_bam /CancerEvolution/Datasets/TCGA_WGS/Data/bam/TCGA-SY-A9G0-10A-01D-A91L-36.WholeGenome.RP-1657.bam \
   -reference_mean_read_depth 112.3 \
   -output_dir ../lengths \
   -threads 32
```
