### ISSUE TITLE
Issue configuring Lilac

### ISSUE THREAD

**Issue by vaksmaz** [hartwigmedical/hmftools#544]
HI, I am having an issue with configuring Lilac. I downloaded the full hmftools. I set up a folder called 'res' with the resources folder. In the I have the following files:
A_nuc.txt  A_prot.txt  B_nuc.txt  B_prot.txt  C_nuc.txt  C_prot.txt   Y_nuc.txt GRCh38_full_analysis_set_plus_decoy_hla.fa 

The java version is 18.0.2. The command I ran to convert them to an indexed/set up as stated in the instructions 

java -cp lilac_v1.5.2.jar com.hartwig.hmftools.lilac.utils.GenerateReferenceSequences -resource_dir /path_to/res/ -output_dir /path_to/resource_out/ 

I get the following error:
07:48:50.807 [INFO ] generating HLA sequence reference data
07:48:50.819 [INFO ] reading nucleotide files
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
	at java.base/java.util.Objects.checkIndex(Objects.java:359)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at com.hartwig.hmftools.lilac.utils.GenerateReferenceSequences.buildSequences(GenerateReferenceSequences.java:180)
	at com.hartwig.hmftools.lilac.utils.GenerateReferenceSequences.nucleotideLoci(GenerateReferenceSequences.java:157)
	at com.hartwig.hmftools.lilac.utils.GenerateReferenceSequences.loadSequenceFiles(GenerateReferenceSequences.java:119)
	at com.hartwig.hmftools.lilac.utils.GenerateReferenceSequences.main(GenerateReferenceSequences.java:91)

**Comment by vaksmaz** [comment]
Also, can you point to the location of the 'Allele Frequencies - taken from HMF's cohort of ~5000 samples, available from the HMF resources page' 
The names of the locations of files changed.
