### ISSUE TITLE
Problem running Lilac

### ISSUE THREAD

**Issue by vaksmaz** [hartwigmedical/hmftools#545]
I ran a test command and ran into an issue, the error was as follows: This does not need the full error, it will be evident. 

Exception in thread "main" htsjdk.samtools.SAMFormatException: SAM validation error: ERROR::INVALID_MAPPING_QUALITY:Record 2994, Read name A00404:238:H7W75DSXY:3:1464:1199:27398, MAPQ should be 0 for unmapped read.
	at htsjdk.samtools.SAMUtils.processValidationErrors(SAMUtils.java:457)
	at htsjdk.samtools.BAMFileReader$BAMFileIterator.advance(BAMFileReader.java:849)
	at htsjdk.samtools.BAMFileReader$BAMFileIterator.next(BAMFileReader.java:834)
	at htsjdk.samtools.BAMFileReader$BAMFileIterator.next(BAMFileReader.java:802)
	at htsjdk.samtools.BAMFileReader$BAMQueryFilteringIterator.advance(BAMFileReader.java:1079)
	at htsjdk.samtools.BAMFileReader$BAMQueryFilteringIterator.<init>(BAMFileReader.java:1048)
	at htsjdk.samtools.BAMFileReader.createIndexIterator(BAMFileReader.java:959)

**Comment by charlesshale** [comment]
The BAM has invalid reads - in this case unmapped reads with a map qual > 0. There may be tools to correct this issue, otherwise we recommend using BWA for alignment as it does not result in these invalid reads.

Most of our tools can be run with BAM validation stringency turned to SILENT, but Lilac does not have this option. We will add it to the next release.
