### ISSUE TITLE
Exception in thread "main" java.lang.IllegalArgumentException: No enum constant com.hartwig.hmftools.common.genome.chromosome.HumanChromosome._GL000217.1

### ISSUE THREAD

**Issue by JiwonShon** [hartwigmedical/hmftools#566]
Hi, I am trying to use RegionSlicer in bamtools. but I encountered an error.
i used the reference genome fasta file 'human_g1k_v37_decoy.fasta'
the slice_reads.tsv file looks well extracted, but slice.bam is empty. how should I  handle this issue?

08:24:42.975 [main] [INFO ] initial slice complete
Exception in thread "main" java.lang.IllegalArgumentException: No enum constant com.hartwig.hmftools.common.genome.chromosome.HumanChromosome._GL000217.1
	at java.base/java.lang.Enum.valueOf(Enum.java:240)
	at com.hartwig.hmftools.common.genome.chromosome.HumanChromosome.valueOf(HumanChromosome.java:8)
	at com.hartwig.hmftools.common.genome.chromosome.HumanChromosome.fromString(HumanChromosome.java:73)
	at com.hartwig.hmftools.common.genome.chromosome.HumanChromosome.matches(HumanChromosome.java:56)
	at com.hartwig.hmftools.bamtools.slice.RegionSlicer$RemotePositions.isChromosome2(RegionSlicer.java:122)
	at com.hartwig.hmftools.bamtools.slice.RegionSlicer$RemotePositions.compareTo(RegionSlicer.java:108)
	at com.hartwig.hmftools.bamtools.slice.RegionSlicer$RemotePositions.compareTo(RegionSlicer.java:90)
	at java.base/java.util.ComparableTimSort.countRunAndMakeAscending(ComparableTimSort.java:320)
	at java.base/java.util.ComparableTimSort.sort(ComparableTimSort.java:202)
	at java.base/java.util.Arrays.sort(Arrays.java:1315)
	at java.base/java.util.Arrays.sort(Arrays.java:1509)
	at java.base/java.util.ArrayList.sort(ArrayList.java:1750)
	at java.base/java.util.Collections.sort(Collections.java:145)
	at com.hartwig.hmftools.bamtools.slice.RegionSlicer.run(RegionSlicer.java:73)
	at com.hartwig.hmftools.bamtools.slice.RegionSlicer.main(RegionSlicer.java:133)

**Comment by charlesshale** [comment]
Remote region reads in non-standard chromosomes (ie alt contigs) were not handled.

I've fixed in a preliminary release:
https://github.com/hartwigmedical/hmftools/releases/tag/bam-tools-v1.3_beta
