### ISSUE TITLE
GRIPSS running issue

### ISSUE THREAD

**Issue by Teezi** [hartwigmedical/hmftools#572]
Hi,

I am currently using `GRIPSS` to filter the `GRIDSS` SV output.
But ran into an error message, any ideas what might be causing this (Tried Adding `-Xmx2048m` to the java command line but no help)? Thanks in advance!

```
12:33:01.173 [INFO ] Gripss version 2.4
12:33:01.303 [INFO ] loading reference data
12:33:06.682 [INFO ] loaded 9980651 germline SV PON records from file(hmf_dna_pipeline_resources/v5_34/ref/38/sv/gridss_pon_breakpoint.bedpe)
12:33:07.905 [INFO ] loaded 3412263 germline SGL PON records from file(hmf_dna_pipeline_resources/v5_34/ref/38/sv/gridss_pon_single_breakend.bed)
12:33:07.908 [INFO ] loaded 461 known hotspot records from file
12:33:25.991 [INFO ] loaded 5417857 repeat-mask entries from file(hmf_dna_pipeline_resources/v5_34/ref/38/sv/repeat_mask_data.38.fa.gz)
12:33:26.049 [INFO ] sample(AUD220512001_tumor) processing VCF(1_GRIDSS_output_allSVs/p1/result/p1_all_calls.vcf)
12:33:26.050 [INFO ] genotype info: ref(0: p1_normal.recal.bam) tumor(1: p1_tumor.recal.bam)
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
        at java.base/java.util.HashMap.resize(HashMap.java:710)
        at java.base/java.util.HashMap.putVal(HashMap.java:669)
        at java.base/java.util.HashMap.put(HashMap.java:618)
        at htsjdk.variant.vcf.AbstractVCFCodec.parseInfo(AbstractVCFCodec.java:558)
        at htsjdk.variant.vcf.AbstractVCFCodec.parseVCFLine(AbstractVCFCodec.java:428)
        at htsjdk.variant.vcf.AbstractVCFCodec.decodeLine(AbstractVCFCodec.java:384)
        at htsjdk.variant.vcf.AbstractVCFCodec.decode(AbstractVCFCodec.java:328)
        at htsjdk.variant.vcf.AbstractVCFCodec.decode(AbstractVCFCodec.java:48)
        at htsjdk.tribble.AsciiFeatureCodec.decode(AsciiFeatureCodec.java:70)
        at htsjdk.tribble.AsciiFeatureCodec.decode(AsciiFeatureCodec.java:37)
        at htsjdk.tribble.TribbleIndexedFeatureReader$WFIterator.readNextRecord(TribbleIndexedFeatureReader.java:375)
        at htsjdk.tribble.TribbleIndexedFeatureReader$WFIterator.next(TribbleIndexedFeatureReader.java:354)
        at htsjdk.tribble.TribbleIndexedFeatureReader$WFIterator.next(TribbleIndexedFeatureReader.java:315)
        at java.base/java.lang.Iterable.forEach(Iterable.java:74)
        at com.hartwig.hmftools.gripss.GripssApplication.processVcf(GripssApplication.java:161)
        at com.hartwig.hmftools.gripss.GripssApplication.run(GripssApplication.java:121)
        at com.hartwig.hmftools.gripss.GripssApplication.main(GripssApplication.java:372)
```

The commend line
```
java -jar $GRIPSS_scripts_DIR/gripss.jar \
>    -sample p1_tumor \
>    -reference p1_normal \
>    -ref_genome_version 38 \
>    -ref_genome $ref_genome \
>    -pon_sgl_file $hmf_dna_pipeline_resources_DIR/gridss_pon_single_breakend.bed \
>    -pon_sv_file $hmf_dna_pipeline_resources_DIR/gridss_pon_breakpoint.bedpe \
>    -known_hotspot_file $hmf_dna_pipeline_resources_DIR/known_fusions.38.bedpe \
>    -repeat_mask_file $hmf_dna_pipeline_resources_DIR/repeat_mask_data.38.fa.gz \
>    -vcf $GRIDSS_OUTPUT_DIR/p1/p1_all_calls.vcf \
>    -output_dir $GRIPSS_OUTPUT_DIR/p1
```

**Comment by Teezi** [comment]
Problem solved by adding `-Xmx64g` to the Java command-line.

**Comment by Teezi** [comment]
Problem solved by adding -Xmx64g to the Java command-line.
