### ISSUE TITLE
adding SAMvalidation option to LiLAC and TEAL

### ISSUE THREAD

**Issue by nan5895** [hartwigmedical/hmftools#590]
Would it be possible that SAM validation options that select "STRICT," "CLIENT,"  and "LIENENT" be added to LiLAC and TEAL?
If that is possible, that would be wonderful to utilize some of the controlled bams that have such below issue 

```
Exception in thread "main" java.util.concurrent.ExecutionException: htsjdk.samtools.SAMFormatException: SAM validation error: ERROR::INVALID_MAPPING_QUALITY:Record 509998, Read name HWI-ST208:8:1305:14510:185409#0, MAPQ should be 0 for unmapped read.
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at com.hartwig.hmftools.teal.telbam.BamProcessor.runTasksTillCompletion(BamProcessor.kt:164)
	at com.hartwig.hmftools.teal.telbam.BamProcessor.processBam(BamProcessor.kt:65)
	at com.hartwig.hmftools.teal.telbam.TelbamApp.processBam(TelbamApp.kt:69)
	at com.hartwig.hmftools.teal.TealApplication$StandaloneMode.run(TealApplication.kt:66)
	at com.hartwig.hmftools.teal.TealApplication$PipelineMode.run(TealApplication.kt:191)
	at com.hartwig.hmftools.teal.TealApplication$Companion.main(TealApplication.kt:286)
	at com.hartwig.hmftools.teal.TealApplication.main(TealApplication.kt)
Caused by: htsjdk.samtools.SAMFormatException: SAM validation error: ERROR::INVALID_MAPPING_QUALITY:Record 509998, Read name HWI-ST208:8:1305:14510:185409#0, MAPQ should be 0 for unmapped read.
	at htsjdk.samtools.SAMUtils.processValidationErrors(SAMUtils.java:457)
	at htsjdk.samtools.BAMFileReader$BAMFileIterator.advance(BAMFileReader.java:849)
	at htsjdk.samtools.BAMFileReader$BAMFileIterator.next(BAMFileReader.java:834)
	at htsjdk.samtools.BAMFileReader$BAMFileIterator.next(BAMFileReader.java:802)
	at htsjdk.samtools.BAMFileReader$BAMQueryFilteringIterator.advance(BAMFileReader.java:1079)
	at htsjdk.samtools.BAMFileReader$BAMQueryFilteringIterator.next(BAMFileReader.java:1069)
	at htsjdk.samtools.BAMFileReader$BAMQueryFilteringIterator.next(BAMFileReader.java:1033)
	at htsjdk.samtools.SamReader$AssertingIterator.next(SamReader.java:574)
	at htsjdk.samtools.SamReader$AssertingIterator.next(SamReader.java:553)
	at com.hartwig.hmftools.common.samtools.BamSlicer.slice(BamSlicer.java:81)
	at com.hartwig.hmftools.common.samtools.BamSlicer.slice(BamSlicer.java:65)
	at com.hartwig.hmftools.teal.telbam.BamProcessor.sliceRegionTask(BamProcessor.kt:123)
	at com.hartwig.hmftools.teal.telbam.BamProcessor.processBam$lambda-1(BamProcessor.kt:60)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

```

**Comment by hongwingl** [comment]
Hi,
I am not convinced that SAM validation adds value. In the next version of TEAL will just change it to always use lenient flag.

**Comment by charlesshale** [comment]
Lilac can have this set in config already:
-bam_validation [STRICT (default), LENIENT or SILENT]

**Comment by hongwingl** [comment]
I have made a release of TEAL (1.3.1) that uses LENIENT bam validation.
