### ISSUE TITLE
[ERROR] - failed processing sample(HCC1395): java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "java.util.Map.get(Object)" is null

### ISSUE THREAD

**Issue by yangxin-9** [hartwigmedical/hmftools#613]
Hi hmftools team,
    firstly thank you for developing hmftools/purple. I try to deploy this tool in my server.  I am trying to run purple on a set of paired tumour/normal samples. I ran cobalt and amber without issue. However I get this error message when trying to run purple.  the error shown above occured. 

script:
java -jar purple_v3.8.4.jar \
        -reference  HCC1395-BL \
        -tumor HCC1395 \
        -amber /tumour/06.hmftools/02.amber/ \
        -cobalt /tumour/06.hmftools/01.cobalt/ \
        -output_dir ./ \
        -ref_genome /tumour/reference/hg38/hg38.fasta \
        -ref_genome_version 38 \
        -ensembl_data_dir /tumour/software/HMFtools/common/ensembl_data/ \
        -gc_profile /tumour/software/HMFtools/v5_34/ref/38/copy_number/GC_profile.1000bp.38.cnp \
        -threads 10

The detailed error info:
java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "java.util.Map.get(Object)" is null
        at com.hartwig.hmftools.common.cobalt.CobaltRatioFile.read(CobaltRatioFile.java:104)
        at com.hartwig.hmftools.common.cobalt.CobaltRatioFile.readWithGender(CobaltRatioFile.java:81)
        at com.hartwig.hmftools.purple.config.CobaltData.<init>(CobaltData.java:64)
        at com.hartwig.hmftools.purple.PurpleApplication.loadSampleData(PurpleApplication.java:209)
        at com.hartwig.hmftools.purple.PurpleApplication.processSample(PurpleApplication.java:238)
        at com.hartwig.hmftools.purple.PurpleApplication.run(PurpleApplication.java:183)
        at com.hartwig.hmftools.purple.PurpleApplication.main(PurpleApplication.java:682)

Is there a way of seeing in more detail what is causing the error? I would be very grateful for your help with this.

**Comment by charlesshale** [comment]
Purple is now at v4.0 and v4.1 is due for release shortly with pipeline v6.0. I would recommend trying again with this version, or running the whole pipeline using OncoAnalyser. If the issue persists, then you could attach the Cobalt file for us to have a look at.

**Comment by MadsAagaard** [comment]
I'm seeing a very similar error:
failed processing sample(113109883577_WG4_NGC): java.lang.NullPointerException: Cannot invoke "java.util.List.iterator()" because "transDataList" is null
java.lang.NullPointerException: Cannot invoke "java.util.List.iterator()" because "transDataList" is null
       at com.hartwig.hmftools.purple.gene.GeneCopyNumberBuilder.createGeneCopyNumbers(GeneCopyNumberBuilder.java:65)
        at com.hartwig.hmftools.purple.PurpleApplication.performFit(PurpleApplication.java:253)
        at com.hartwig.hmftools.purple.PurpleApplication.run(PurpleApplication.java:138)
        at com.hartwig.hmftools.purple.PurpleApplication.main(PurpleApplication.java:487)

The error persists with both purple_v4.1_beta.1.jar and purple_v3.8.4.jar.

command:
java -jar /data/mmaj/downloads/hmftools/purple_v3.8.4.jar 
-reference normal_samplename                   # same as for cobalt and amber 
-tumor tumor_samplename                          # same as for cobalt and amber 
-ref_genome /path/to/refgenome.fasta
-output_dir purple_output 
-threads 20
-ref_genome_version 38 
-gc_profile /path/to/hmftools/v6_0/ref/38/copy_number/GC_profile.1000bp.38.cnp
-ensembl_data_dir /path/to/hmftools/hmftools/v6_0/ref/38/common/ensembl_data/ 
-amber amber_output 
-cobalt cobalt_output/

Both Cobalt and Amber completes without errors. Do you have an idea what is wrong?

Thanks in advance!

**Comment by MadsAagaard** [comment]
Update:
Above command works if I switch to ../hmftools/v5_34/ref/38/common/ensembl_data/ instead of v6_0/...

**Comment by bounlu** [comment]
I am having a similar issue with purple via `nf-core/oncoanalyser` with `pipeline_v6.0` and purple `4.1-rc.1`.

```
Execution cancelled -- Finishing pending tasks before exit
-[nf-core/oncoanalyser] Pipeline completed with errors-
ERROR ~ Error executing process > 'NFCORE_ONCOANALYSER:TARGETED:PURPLE_CALLING:PURPLE (XXXYYYZZZ)'

Caused by:
  Process `NFCORE_ONCOANALYSER:TARGETED:PURPLE_CALLING:PURPLE (XXXYYYZZZ)` terminated with an error exit status (1)


Command executed:

  purple \
      -Xmx12240656794 \
       \
      -tumor XXXYYYZZZ \
       \
      -amber amber \
      -cobalt cobalt \
      -somatic_sv_vcf XXXYYYZZZ.esvee.somatic.vcf.gz \
       \
      -somatic_vcf XXXYYYZZZ.sage.somatic.pave.vcf.gz \
       \
      -ref_genome GCA_000001405.15_GRCh38_no_alt_analysis_set.fna \
      -ref_genome_version 38 \
      -driver_gene_panel DriverGenePanel.tso500.38.tsv \
      -ensembl_data_dir ensembl_data \
      -somatic_hotspots KnownHotspots.somatic.38.vcf.gz \
      -germline_hotspots KnownHotspots.germline.38.vcf.gz \
      -target_regions_bed target_regions_definition.tso500.38.bed.gz \
      -target_regions_ratios target_regions_ratios.tso500.38.tsv \
      -target_regions_msi_indels target_regions_msi_indels.tso500.38.tsv \
      -germline_del_freq_file cohort_germline_del_freq.38.csv \
      -gc_profile GC_profile.1000bp.38.cnp \
      -circos $(which circos) \
      -threads 2 \
      -output_dir purple/
  
  cat <<-END_VERSIONS > versions.yml
  "NFCORE_ONCOANALYSER:TARGETED:PURPLE_CALLING:PURPLE":
      purple: $(purple -version | sed 's/^.* //')
  END_VERSIONS

Command exit status:
  1

Command output:
  01:56:37.853 [INFO ] Purple version 4.1-rc.1
  01:56:37.920 [INFO ] output directory: purple/
  01:56:37.926 [INFO ] reference(NONE) tumor(XXXYYYZZZ) running on target-regions only
  01:56:38.077 [INFO ] using ref genome: V38
  01:56:45.781 [INFO ] loaded 0 germline deletions frequencies from file: cohort_germline_del_freq.38.csv
  01:56:45.784 [INFO ] loaded 117 MSI indels from file(target_regions_msi_indels.tso500.38.tsv)
  01:56:45.784 [INFO ] target regions: tml(1.0) tmb(0.05) msiIndels(220.0) msiAF(2-3 base=0.15 4 base=0.08) codingBaseFactor(150000)
  01:56:45.920 [INFO ] loaded 6535 target regions bases(total=1548434 coding=1467473) from file(target_regions_definition.tso500.38.bed.gz)
  01:56:45.922 [INFO ] reading GC Profiles from GC_profile.1000bp.38.cnp
  01:56:48.773 [INFO ] reading Amber QC from amber/XXXYYYZZZ.amber.qc
  01:56:48.775 [INFO ] reading Amber BAFs from amber/XXXYYYZZZ.amber.baf.tsv.gz
  01:56:48.779 [INFO ] reading Amber PCFs from amber/XXXYYYZZZ.amber.baf.pcf
  01:56:48.859 [INFO ] Amber average tumor depth(1060) ambiguous BAF(0.513)
  01:56:48.860 [INFO ] reading Cobalt tumor segments from cobalt/XXXYYYZZZ.cobalt.ratio.pcf
  01:56:48.861 [INFO ] reading Cobalt ratios from cobalt/XXXYYYZZZ.cobalt.ratio.tsv.gz
  01:56:52.366 [INFO ] loaded 170 somatic SVs from XXXYYYZZZ.esvee.somatic.vcf.gz
  01:56:52.870 [INFO ] loaded 19465 somatic variants from XXXYYYZZZ.sage.somatic.pave.vcf.gz
  01:56:52.870 [INFO ] sample gender is male
  01:56:52.870 [INFO ] purple output directory: purple/
  01:56:52.875 [INFO ] applying segmentation
  01:56:52.875 [INFO ] merging reference and tumor ratio break points
  01:56:54.332 [INFO ] fitting purity
  01:56:58.303 [ERROR] failed processing sample(XXXYYYZZZ): java.lang.NullPointerException: Cannot invoke "java.util.List.iterator()" because "transDataList" is null

Command error:
  01:56:37.853 [INFO ] Purple version 4.1-rc.1
  01:56:37.920 [INFO ] output directory: purple/
  01:56:37.926 [INFO ] reference(NONE) tumor(XXXYYYZZZ) running on target-regions only
  01:56:38.077 [INFO ] using ref genome: V38
  01:56:45.781 [INFO ] loaded 0 germline deletions frequencies from file: cohort_germline_del_freq.38.csv
  01:56:45.784 [INFO ] loaded 117 MSI indels from file(target_regions_msi_indels.tso500.38.tsv)
  01:56:45.784 [INFO ] target regions: tml(1.0) tmb(0.05) msiIndels(220.0) msiAF(2-3 base=0.15 4 base=0.08) codingBaseFactor(150000)
  01:56:45.920 [INFO ] loaded 6535 target regions bases(total=1548434 coding=1467473) from file(target_regions_definition.tso500.38.bed.gz)
  01:56:45.922 [INFO ] reading GC Profiles from GC_profile.1000bp.38.cnp
  01:56:48.773 [INFO ] reading Amber QC from amber/XXXYYYZZZ.amber.qc
  01:56:48.775 [INFO ] reading Amber BAFs from amber/XXXYYYZZZ.amber.baf.tsv.gz
  01:56:48.779 [INFO ] reading Amber PCFs from amber/XXXYYYZZZ.amber.baf.pcf
  01:56:48.859 [INFO ] Amber average tumor depth(1060) ambiguous BAF(0.513)
  01:56:48.860 [INFO ] reading Cobalt tumor segments from cobalt/XXXYYYZZZ.cobalt.ratio.pcf
  01:56:48.861 [INFO ] reading Cobalt ratios from cobalt/XXXYYYZZZ.cobalt.ratio.tsv.gz
  01:56:52.366 [INFO ] loaded 170 somatic SVs from XXXYYYZZZ.esvee.somatic.vcf.gz
  01:56:52.870 [INFO ] loaded 19465 somatic variants from XXXYYYZZZ.sage.somatic.pave.vcf.gz
  01:56:52.870 [INFO ] sample gender is male
  01:56:52.870 [INFO ] purple output directory: purple/
  01:56:52.875 [INFO ] applying segmentation
  01:56:52.875 [INFO ] merging reference and tumor ratio break points
  01:56:54.332 [INFO ] fitting purity
  01:56:58.303 [ERROR] failed processing sample(XXXYYYZZZ): java.lang.NullPointerException: Cannot invoke "java.util.List.iterator()" because "transDataList" is null
  java.lang.NullPointerException: Cannot invoke "java.util.List.iterator()" because "transDataList" is null
  	at com.hartwig.hmftools.purple.gene.GeneCopyNumberBuilder.createGeneCopyNumbers(GeneCopyNumberBuilder.java:65)
  	at com.hartwig.hmftools.purple.PurpleApplication.performFit(PurpleApplication.java:243)
  	at com.hartwig.hmftools.purple.PurpleApplication.run(PurpleApplication.java:128)
  	at com.hartwig.hmftools.purple.PurpleApplication.main(PurpleApplication.java:465)

Work dir:
  /nextflow/oncoanalyser/tso500/work/7d/8c9z5869c56767e634d3183329b566

Container:
  docker.io/hartwigmedicalfoundation/purple:4.1-rc.1

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line

 -- Check '.nextflow.log' file for details
ERROR ~ Pipeline failed. Please refer to troubleshooting docs: https://nf-co.re/docs/usage/troubleshooting

 -- Check '.nextflow.log' file for details
```
