### ISSUE TITLE
BamTools version 1.2.1, RegionSlicer got error on No enum constat especially _MT

### ISSUE THREAD

**Issue by JiwonShon** [hartwigmedical/hmftools#644]
I am trying to slice cram file using RegionSlicer with the bed file that contains segments of region and there is no MT region in my bed file. However, I got 'com.hartwig.hmftools.common.genome.chromosome.HumanChromosome._MT' this kind of error.
weire thing is some cram files complete well, but not for several crams. 

how can I handle this error?

- this is my code to run 
```
    java -Xmx40G -cp /opt/hmftools/bamtools/bam-tools_v1.2.1.jar com.hartwig.hmftools.bamtools.slice.RegionSlicer \
        -output_dir ./ \
        -output_prefix ${object_id}_BND \
        -threads 4 \
        -ref_genome ${genome_fasta} \
        -bam_file ${cram} \
        -regions_file ${bed_file} \
        -write_bam \
        -log_level INFO
```

- this is the .command.err
```
16:05:09.055 [main] [INFO ] BamTools version 1.2.1
16:05:10.223 [main] [INFO ] input bam(CPCT02070313T_dedup.realigned.cram) refGenome(V37)
16:05:10.223 [main] [INFO ] output(./) and file prefix(CPCT02070313T_BNDregion)
16:05:10.281 [main] [INFO ] starting BamSlicer
16:05:17.508 [main] [INFO ] splitting 14 regions across 4 threads
16:05:17.515 [Thread-0] [INFO ] processing region(2:15578982-15580981)
16:05:17.515 [Thread-2] [INFO ] processing region(2:15926180-15929200)
16:05:17.515 [Thread-3] [INFO ] processing region(2:16110562-16113540)
16:05:17.515 [Thread-1] [INFO ] processing region(2:15679359-15681359)
16:05:18.869 [Thread-0] [INFO ] region(2:15578982-15580981) complete, processed 1811 reads, remote positions(339)
16:05:18.869 [Thread-0] [INFO ] processing region(2:16270679-16272679)
16:05:18.941 [Thread-1] [INFO ] region(2:15679359-15681359) complete, processed 13710 reads, remote positions(2478)
16:05:18.941 [Thread-1] [INFO ] processing region(2:16272822-16274822)
16:05:19.281 [Thread-1] [INFO ] region(2:16272822-16274822) complete, processed 12051 reads, remote positions(2069)
16:05:19.281 [Thread-1] [INFO ] processing region(2:16333100-16335100)
16:05:19.282 [Thread-0] [INFO ] region(2:16270679-16272679) complete, processed 10220 reads, remote positions(2227)
16:05:19.282 [Thread-0] [INFO ] processing region(2:16396605-16398605)
16:05:19.291 [Thread-3] [INFO ] region(2:16110562-16113540) complete, processed 25376 reads, remote positions(4167)
16:05:19.291 [Thread-3] [INFO ] processing region(2:16399567-16401567)
16:05:19.414 [Thread-2] [INFO ] region(2:15926180-15929200) complete, processed 24773 reads, remote positions(4096)
16:05:19.414 [Thread-2] [INFO ] processing region(2:16405392-16408988)
16:05:19.856 [Thread-1] [INFO ] region(2:16333100-16335100) complete, processed 23017 reads, remote positions(4167)
16:05:19.856 [Thread-0] [INFO ] region(2:16396605-16398605) complete, processed 12777 reads, remote positions(2532)
16:05:19.856 [Thread-1] [INFO ] processing region(2:16891122-16893122)
16:05:19.856 [Thread-0] [INFO ] processing region(2:16894432-16896432)
16:05:20.004 [Thread-3] [INFO ] region(2:16399567-16401567) complete, processed 11913 reads, remote positions(1575)
16:05:20.004 [Thread-3] [INFO ] processing region(2:18306656-18308656)
16:05:20.245 [Thread-2] [INFO ] region(2:16405392-16408988) complete, processed 40740 reads, remote positions(3597)
16:05:20.245 [Thread-2] [INFO ] processing region(2:18406690-18408689)
16:05:20.263 [Thread-0] [INFO ] region(2:16894432-16896432) complete, processed 13048 reads, remote positions(2037)
16:05:20.410 [Thread-2] [INFO ] region(2:18406690-18408689) complete, processed 1541 reads, remote positions(299)
16:05:20.488 [Thread-3] [INFO ] region(2:18306656-18308656) complete, processed 12418 reads, remote positions(2343)
16:05:20.493 [Thread-1] [INFO ] region(2:16891122-16893122) complete, processed 12602 reads, remote positions(2243)
16:05:20.493 [main] [INFO ] initial slice complete
Exception in thread "main" java.lang.IllegalArgumentException: No enum constant com.hartwig.hmftools.common.genome.chromosome.HumanChromosome._MT
	at java.base/java.lang.Enum.valueOf(Enum.java:240)
	at com.hartwig.hmftools.common.genome.chromosome.HumanChromosome.valueOf(HumanChromosome.java:8)
	at com.hartwig.hmftools.common.genome.chromosome.HumanChromosome.fromString(HumanChromosome.java:73)
	at com.hartwig.hmftools.common.genome.chromosome.HumanChromosome.matches(HumanChromosome.java:56)
	at com.hartwig.hmftools.bamtools.slice.RegionSlicer$RemotePositions.isChromosome2(RegionSlicer.java:122)
	at com.hartwig.hmftools.bamtools.slice.RegionSlicer$RemotePositions.compareTo(RegionSlicer.java:108)
	at com.hartwig.hmftools.bamtools.slice.RegionSlicer$RemotePositions.compareTo(RegionSlicer.java:90)
	at java.base/java.util.ComparableTimSort.binarySort(ComparableTimSort.java:262)
	at java.base/java.util.ComparableTimSort.sort(ComparableTimSort.java:189)
	at java.base/java.util.Arrays.sort(Arrays.java:1315)
	at java.base/java.util.Arrays.sort(Arrays.java:1509)
	at java.base/java.util.ArrayList.sort(ArrayList.java:1750)
	at java.base/java.util.Collections.sort(Collections.java:145)
	at com.hartwig.hmftools.bamtools.slice.RegionSlicer.run(RegionSlicer.java:73)
	at com.hartwig.hmftools.bamtools.slice.RegionSlicer.main(RegionSlicer.java:133)
```

**Comment by JiwonShon** [comment]
When i used pre-release version of 1.3 then, the error was gone!!
