### ISSUE TITLE
`purple` fails with `"transDataList" is null` error

### ISSUE THREAD

**Issue by bounlu** [hartwigmedical/hmftools#645]
I am running `nf-core/oncoanalyser` with `pipeline_v6.0` and `purple 4.1-rc.1`. I have regenerated `ensembl_data` cache by [gene-utils](https://github.com/hartwigmedical/hmftools/tree/master/gene-utils#generating-cached-ensembl-data-files).

The pipeline fails at the step of `purple` like this:

```
Execution cancelled -- Finishing pending tasks before exit
-[nf-core/oncoanalyser] Pipeline completed with errors-
ERROR ~ Error executing process > 'NFCORE_ONCOANALYSER:TARGETED:PURPLE_CALLING:PURPLE (XXXYYYZZZ)'

Caused by:
  Process `NFCORE_ONCOANALYSER:TARGETED:PURPLE_CALLING:PURPLE (XXXYYYZZZ)` terminated with an error exit status (1)


Command executed:

  purple \
      -Xmx12240656794 \
       \
      -tumor XXXYYYZZZ \
       \
      -amber amber \
      -cobalt cobalt \
      -somatic_sv_vcf XXXYYYZZZ.esvee.somatic.vcf.gz \
       \
      -somatic_vcf XXXYYYZZZ.sage.somatic.pave.vcf.gz \
       \
      -ref_genome GCA_000001405.15_GRCh38_no_alt_analysis_set.fna \
      -ref_genome_version 38 \
      -driver_gene_panel DriverGenePanel.tso500.38.tsv \
      -ensembl_data_dir ensembl_data \
      -somatic_hotspots KnownHotspots.somatic.38.vcf.gz \
      -germline_hotspots KnownHotspots.germline.38.vcf.gz \
      -target_regions_bed target_regions_definition.tso500.38.bed.gz \
      -target_regions_ratios target_regions_ratios.tso500.38.tsv \
      -target_regions_msi_indels target_regions_msi_indels.tso500.38.tsv \
      -germline_del_freq_file cohort_germline_del_freq.38.csv \
      -gc_profile GC_profile.1000bp.38.cnp \
      -circos $(which circos) \
      -threads 2 \
      -output_dir purple/
  
  cat <<-END_VERSIONS > versions.yml
  "NFCORE_ONCOANALYSER:TARGETED:PURPLE_CALLING:PURPLE":
      purple: $(purple -version | sed 's/^.* //')
  END_VERSIONS

Command exit status:
  1

Command output:
  01:56:37.853 [INFO ] Purple version 4.1-rc.1
  01:56:37.920 [INFO ] output directory: purple/
  01:56:37.926 [INFO ] reference(NONE) tumor(XXXYYYZZZ) running on target-regions only
  01:56:38.077 [INFO ] using ref genome: V38
  01:56:45.781 [INFO ] loaded 0 germline deletions frequencies from file: cohort_germline_del_freq.38.csv
  01:56:45.784 [INFO ] loaded 117 MSI indels from file(target_regions_msi_indels.tso500.38.tsv)
  01:56:45.784 [INFO ] target regions: tml(1.0) tmb(0.05) msiIndels(220.0) msiAF(2-3 base=0.15 4 base=0.08) codingBaseFactor(150000)
  01:56:45.920 [INFO ] loaded 6535 target regions bases(total=1548434 coding=1467473) from file(target_regions_definition.tso500.38.bed.gz)
  01:56:45.922 [INFO ] reading GC Profiles from GC_profile.1000bp.38.cnp
  01:56:48.773 [INFO ] reading Amber QC from amber/XXXYYYZZZ.amber.qc
  01:56:48.775 [INFO ] reading Amber BAFs from amber/XXXYYYZZZ.amber.baf.tsv.gz
  01:56:48.779 [INFO ] reading Amber PCFs from amber/XXXYYYZZZ.amber.baf.pcf
  01:56:48.859 [INFO ] Amber average tumor depth(1060) ambiguous BAF(0.513)
  01:56:48.860 [INFO ] reading Cobalt tumor segments from cobalt/XXXYYYZZZ.cobalt.ratio.pcf
  01:56:48.861 [INFO ] reading Cobalt ratios from cobalt/XXXYYYZZZ.cobalt.ratio.tsv.gz
  01:56:52.366 [INFO ] loaded 170 somatic SVs from XXXYYYZZZ.esvee.somatic.vcf.gz
  01:56:52.870 [INFO ] loaded 19465 somatic variants from XXXYYYZZZ.sage.somatic.pave.vcf.gz
  01:56:52.870 [INFO ] sample gender is male
  01:56:52.870 [INFO ] purple output directory: purple/
  01:56:52.875 [INFO ] applying segmentation
  01:56:52.875 [INFO ] merging reference and tumor ratio break points
  01:56:54.332 [INFO ] fitting purity
  01:56:58.303 [ERROR] failed processing sample(XXXYYYZZZ): java.lang.NullPointerException: Cannot invoke "java.util.List.iterator()" because "transDataList" is null

Command error:
  01:56:37.853 [INFO ] Purple version 4.1-rc.1
  01:56:37.920 [INFO ] output directory: purple/
  01:56:37.926 [INFO ] reference(NONE) tumor(XXXYYYZZZ) running on target-regions only
  01:56:38.077 [INFO ] using ref genome: V38
  01:56:45.781 [INFO ] loaded 0 germline deletions frequencies from file: cohort_germline_del_freq.38.csv
  01:56:45.784 [INFO ] loaded 117 MSI indels from file(target_regions_msi_indels.tso500.38.tsv)
  01:56:45.784 [INFO ] target regions: tml(1.0) tmb(0.05) msiIndels(220.0) msiAF(2-3 base=0.15 4 base=0.08) codingBaseFactor(150000)
  01:56:45.920 [INFO ] loaded 6535 target regions bases(total=1548434 coding=1467473) from file(target_regions_definition.tso500.38.bed.gz)
  01:56:45.922 [INFO ] reading GC Profiles from GC_profile.1000bp.38.cnp
  01:56:48.773 [INFO ] reading Amber QC from amber/XXXYYYZZZ.amber.qc
  01:56:48.775 [INFO ] reading Amber BAFs from amber/XXXYYYZZZ.amber.baf.tsv.gz
  01:56:48.779 [INFO ] reading Amber PCFs from amber/XXXYYYZZZ.amber.baf.pcf
  01:56:48.859 [INFO ] Amber average tumor depth(1060) ambiguous BAF(0.513)
  01:56:48.860 [INFO ] reading Cobalt tumor segments from cobalt/XXXYYYZZZ.cobalt.ratio.pcf
  01:56:48.861 [INFO ] reading Cobalt ratios from cobalt/XXXYYYZZZ.cobalt.ratio.tsv.gz
  01:56:52.366 [INFO ] loaded 170 somatic SVs from XXXYYYZZZ.esvee.somatic.vcf.gz
  01:56:52.870 [INFO ] loaded 19465 somatic variants from XXXYYYZZZ.sage.somatic.pave.vcf.gz
  01:56:52.870 [INFO ] sample gender is male
  01:56:52.870 [INFO ] purple output directory: purple/
  01:56:52.875 [INFO ] applying segmentation
  01:56:52.875 [INFO ] merging reference and tumor ratio break points
  01:56:54.332 [INFO ] fitting purity
  01:56:58.303 [ERROR] failed processing sample(XXXYYYZZZ): java.lang.NullPointerException: Cannot invoke "java.util.List.iterator()" because "transDataList" is null
  java.lang.NullPointerException: Cannot invoke "java.util.List.iterator()" because "transDataList" is null
  	at com.hartwig.hmftools.purple.gene.GeneCopyNumberBuilder.createGeneCopyNumbers(GeneCopyNumberBuilder.java:65)
  	at com.hartwig.hmftools.purple.PurpleApplication.performFit(PurpleApplication.java:243)
  	at com.hartwig.hmftools.purple.PurpleApplication.run(PurpleApplication.java:128)
  	at com.hartwig.hmftools.purple.PurpleApplication.main(PurpleApplication.java:465)

Work dir:
  /nextflow/oncoanalyser/tso500/work/7d/8c9z5869c56767e634d3183329b566

Container:
  docker.io/hartwigmedicalfoundation/purple:4.1-rc.1

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line

 -- Check '.nextflow.log' file for details
ERROR ~ Pipeline failed. Please refer to troubleshooting docs: https://nf-co.re/docs/usage/troubleshooting

 -- Check '.nextflow.log' file for details
```

**Comment by charlesshale** [comment]
As mentioned in the similar ticket, there is a gene with a missing canonical transcript in this Ensembl version. We have fixed this up in our latest v6.0 pipeline resources.

**Comment by charlesshale** [comment]
Yes we had to manually remove the gene from our ensemble_gene_data.csv file.

In the next release of GeneUtils I'll add a check to do this automatically.

**Comment by bounlu** [comment]
Yes indeed removing that single gene from that file makes it work with the updated ensembl data cache `v113_38` and latest tool versions `purple-4.1-rc.1`.
