### ISSUE TITLE
Error in running Pave: StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by boyoon0731** [hartwigmedical/hmftools#659]
I encountered an issue while running the Pave tool for mutation calling. 
The process fails with the following error messages in the log file:

```
15:15:39.628 [INFO ] Pave version 1.7
15:15:40.763 [INFO ] loaded PON filter: tier(HOTSPOT) sampleCount(10) maxReads(5)
15:15:40.764 [INFO ] loaded PON filter: tier(PANEL) sampleCount(6) maxReads(5)
15:15:40.764 [INFO ] loaded PON filter: tier(UNKNOWN) sampleCount(6) maxReads(0)
15:15:40.816 [INFO ] writing VCF file(PAVE/-01D-WGS-UBHCZP.sage.pave.vcf.gz)
15:15:44.584 [INFO ] loaded 5604321 Gnomad frequency records from file(gnomad_variants_v37.csv.gz)
15:15:55.225 [INFO ] sample(01D-WGS-UBHCZP) processing VCF file(SAGE/01D-WGS-UBHCZP.sage.vcf.gz)
15:16:04.028 [WARN ] phasing variants LPS(36282) var(pos(1:117122288) variant(G>C)) combinedAltCodons(CTCCTCCCT) prevAltBasesTrimmed(24)
15:16:04.029 [WARN ] phasing variants LPS(36282) var(pos(1:117122288) variant(G>C)) combinedAltCodons(CTCCTCCCT) prevAltBasesTrimmed(24)
15:16:04.029 [WARN ] phasing variants LPS(36282) var(pos(1:117122288) variant(G>C)) combinedAltCodons(CTCCTCCCT) prevAltBasesTrimmed(24)
15:16:08.808 [INFO ] chr(1) complete for 339687 variants
15:16:29.129 [WARN ] phasing variants LPS(137633) var(pos(2:231861044) variant(C>T)) combinedAltCodons(TCTCAG) prevAltBasesTrimmed(19)
15:16:29.130 [WARN ] phasing variants LPS(137633) var(pos(2:231861044) variant(C>T)) combinedAltCodons(TCTCAG) prevAltBasesTrimmed(19)
15:16:29.130 [WARN ] phasing variants LPS(137633) var(pos(2:231861044) variant(C>T)) combinedAltCodons(TCTCAG) prevAltBasesTrimmed(19)
15:16:29.130 [WARN ] phasing variants LPS(137633) var(pos(2:231861044) variant(C>T)) combinedAltCodons(TCTCAG) prevAltBasesTrimmed(19)
15:16:29.848 [INFO ] chr(2) complete for 369811 variants
15:16:47.401 [INFO ] chr(3) complete for 294535 variants
15:17:02.397 [INFO ] chr(4) complete for 297507 variants
15:17:14.841 [INFO ] chr(5) complete for 238681 variants
15:17:29.642 [INFO ] chr(6) complete for 309614 variants
15:17:45.569 [INFO ] chr(7) complete for 282471 variants
15:17:56.153 [INFO ] chr(8) complete for 217998 variants
15:18:04.714 [WARN ] phasing variants LPS(516307) var(pos(9:140918181) variant(A>G)) combinedAltCodons(GTG) prevAltBasesTrimmed(6)
15:18:04.715 [WARN ] phasing variants LPS(516307) var(pos(9:140918181) variant(A>G)) combinedAltCodons(GTG) prevAltBasesTrimmed(6)
15:18:04.715 [WARN ] phasing variants LPS(516307) var(pos(9:140918181) variant(A>G)) combinedAltCodons(GTG) prevAltBasesTrimmed(6)
15:18:04.715 [WARN ] phasing variants LPS(516307) var(pos(9:140918181) variant(A>G)) combinedAltCodons(GTG) prevAltBasesTrimmed(6)
15:18:04.715 [WARN ] phasing variants LPS(516307) var(pos(9:140918181) variant(A>G)) combinedAltCodons(GTG) prevAltBasesTrimmed(6)
15:18:04.715 [WARN ] phasing variants LPS(516307) var(pos(9:140918181) variant(A>G)) combinedAltCodons(GTG) prevAltBasesTrimmed(6)
15:18:04.729 [INFO ] chr(9) complete for 193423 variants
15:18:14.544 [INFO ] chr(10) complete for 227195 variants
15:18:25.329 [INFO ] chr(11) complete for 244646 variants
15:18:35.895 [INFO ] chr(12) complete for 227724 variants
15:18:42.175 [INFO ] chr(13) complete for 137638 variants
15:18:47.923 [INFO ] chr(14) complete for 117748 variants
15:18:53.681 [INFO ] chr(15) complete for 109567 variants
15:19:01.281 [INFO ] chr(16) complete for 129278 variants
15:19:07.113 [INFO ] chr(17) complete for 100559 variants
15:19:11.772 [INFO ] chr(18) complete for 98818 variants
15:19:17.909 [INFO ] chr(19) complete for 110818 variants
15:19:22.931 [ERROR] error processing var(pos(20:60641355-60641356) variant(G>GC))
java.lang.StringIndexOutOfBoundsException: String index out of range: -3
        at java.base/java.lang.String.substring(String.java:1841)
        at com.hartwig.hmftools.pave.impact.PhasedVariantClassifier.reclassifyImpacts(PhasedVariantClassifier.java:378)
        at com.hartwig.hmftools.pave.impact.PhasedVariantClassifier.reclassifyPhasedVariants(PhasedVariantClassifier.java:141)
        at com.hartwig.hmftools.pave.impact.ImpactClassifier.processPhasedVariants(ImpactClassifier.java:344)
        at com.hartwig.hmftools.pave.ChromosomeTask.processPhasedVariants(ChromosomeTask.java:174)
        at com.hartwig.hmftools.pave.ChromosomeTask.processVariant(ChromosomeTask.java:159)
        at com.hartwig.hmftools.pave.ChromosomeTask.call(ChromosomeTask.java:120)
        at com.hartwig.hmftools.pave.ChromosomeTask.call(ChromosomeTask.java:46)
        at com.hartwig.hmftools.common.utils.TaskExecutor.executeTasks(TaskExecutor.java:53)
        at com.hartwig.hmftools.pave.PaveApplication.run(PaveApplication.java:98)
        at com.hartwig.hmftools.pave.PaveApplication.main(PaveApplication.java:146)
```

**15:19:22.931 [ERROR] error processing var(pos(20:60641355-60641356) variant(G>GC))
java.lang.StringIndexOutOfBoundsException: String index out of range: -3**

This issue is not occurring for certain samples, which makes the error more challenging to troubleshoot. 
The command I used to run the tool is:

```
java -jar /opt/hmftools/pave/pave_v1.7.jar \
  -sample 01D-WGS-UBHCZP \
  -vcf_file SAGE/01D-WGS-UBHCZP.sage.vcf.gz \
  -ensembl_data_dir ensembl_data \
  -driver_gene_panel DriverGenePanel.37.tsv \
  -pon_file SageGermlinePon.1000x.37.tsv.gz \
  -pon_filters "HOTSPOT:10:5;PANEL:6:5;UNKNOWN:6:0" \
  -gnomad_freq_file gnomad_variants_v37.csv.gz \
  -ref_genome human_g1k_v37_decoy.fasta \
  -ref_genome_version 37 \
  -output_dir PAVE
```

This error prevents the tool from completing successfully for the affected samples. I would appreciate any assistance or suggestions for resolving this issue. Could this be related to the input VCF file or a specific variant type?

Thank you in advance for your help.

**Comment by charlesshale** [comment]
Could you attached a section of the input VCF which covers the phased variants around:
20:60641355-60641356

and we will attempt to debug the issue, thanks

**Comment by boyoon0731** [comment]
There are multiple samples, but errors occur mainly in two locations. I tested running it with Sage v3.4 and Pave v1.6, as well as with Sage v4.0 and Pave v1.7, but the same error occurred in both cases.
I have attached the VCF files for the 20:60640000-60642000 region for the four samples.
https://www.dropbox.com/scl/fi/rbcxwgpx4llyw85y7rprh/vcf_from_sage.zip?rlkey=x03talij86w7c4r4t2yo4hn4m&dl=0

The samples are as follows:

- LCEGFR-DANK-0001-CL06-01D-WGS-4E8QW3
- LCEGFR-DANK-0001-CL11-01D-WGS-7W22FM
- LCEGFR-DANK-0001-CL21-01D-WGS-LHD4EF
- LCEGFR-DANK-0001-CL22-01D-WGS-HQQAFC

Among them,

LCEGFR-DANK-0001-CL06-01D-WGS-4E8QW3
LCEGFR-DANK-0001-CL11-01D-WGS-7W22FM
These two samples encountered the following error at this location:
`09:00:32.125 [ERROR] error processing var(pos(20:60640461) variant(A>C))
`

LCEGFR-DANK-0001-CL21-01D-WGS-LHD4EF
LCEGFR-DANK-0001-CL22-01D-WGS-HQQAFC
These two samples encountered the following error:
`06:52:44.880 [ERROR] error processing var(pos(20:60641355-60641356) variant(G>GC))
`

thanks.

**Comment by charlesshale** [comment]
This will be addressed in Pave v1.8. There is a beta for this now:
https://github.com/hartwigmedical/hmftools/releases/tag/pave-v1.8-beta.4

**Comment by charlesshale** [comment]
The Pave call is likely missing -read_pass_only - those 4 variants should not be processed together by Pave, only the PASS one.
