### ISSUE TITLE
COBALT error

### ISSUE THREAD

**Issue by hastj7373** [hartwigmedical/hmftools#85]
Hello. 

Could you please tell me how to fix the problem below?
(AMBER worked for me, but COBALT didn't work..)

16:49:38 - COBALT version: 1.8
16:49:38 - Thread Count: 4, Window Size: 1000, Min Quality 10
16:49:38 - Reading GC Profile
16:49:38 - Complete
Exception in thread "main" java.io.UncheckedIOException: java.nio.charset.MalformedInputException: Input length = 1
	at java.io.BufferedReader$1.hasNext(BufferedReader.java:574)
	at java.util.Iterator.forEachRemaining(Iterator.java:115)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
	at com.hartwig.hmftools.common.utils.io.reader.LineReader.read(LineReader.java:38)
	at com.hartwig.hmftools.common.utils.io.reader.LineReader.lambda$build$0(LineReader.java:25)
	at com.hartwig.hmftools.common.genome.gc.GCProfileFactory.loadGCContent(GCProfileFactory.java:29)
	at com.hartwig.hmftools.cobalt.CountBamLinesApplication.run(CountBamLinesApplication.java:86)
	at com.hartwig.hmftools.cobalt.CountBamLinesApplication.main(CountBamLinesApplication.java:46)
Caused by: java.nio.charset.MalformedInputException: Input length = 1
	at java.nio.charset.CoderResult.throwException(CoderResult.java:281)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:339)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at java.io.BufferedReader.fill(BufferedReader.java:161)
	at java.io.BufferedReader.readLine(BufferedReader.java:324)
	at java.io.BufferedReader.readLine(BufferedReader.java:389)
	at java.io.BufferedReader$1.hasNext(BufferedReader.java:571)
	... 12 more

**Comment by alhafidzhamdan** [comment]
Hi did you actually manage to resolve the issue @hastj7373 ? I am encountering the same issue. Would be good if anyone on here could help? probably a very simple issue.
